### ISSUE TITLE
RHCOS 4.12 ppc64le - Fatal glibc error: CPU lacks ISA 3.00 support (POWER9 or later required)

### ISSUE THREAD

**Issue by mike-nguyen** [openshift/os#1000]
During buildextensions-container, the following error is observed.

```
[2/3] STEP 1/7: FROM quay.io/centos/centos:stream9 AS builder
Trying to pull quay.io/centos/centos:stream9...
Getting image source signatures
Copying blob sha256:9b09ed90406389312cd520cb33c32bab856c85bed2dc6f36202447ddcd7b87c5
Copying config sha256:dd933935f5be7e75951c3debb8370ad169a65b2d49176175bbda04b06c73b9e7
Writing manifest to image destination
Storing signatures
[2/3] STEP 2/7: COPY --from=os /usr/share/rpm-ostree/extensions/ /usr/share/rpm-ostree/extensions/
--> 56ab1d5ff40
[2/3] STEP 3/7: RUN dnf install -y createrepo_c golang
Fatal glibc error: CPU lacks ISA 3.00 support (POWER9 or later required)
Error: error building at STEP "RUN dnf install -y createrepo_c golang": error while running runtime: exit status 127
error: exit status 127
```

**Comment by cgwalters** [comment]
> Fatal glibc error: CPU lacks ISA 3.00 support (POWER9 or later required)

This is almost certainly the ppc64le equivalent of https://github.com/coreos/coreos-assembler/pull/3070/commits/28fc80b0f57b10e79e43253a12596db3f9f8de46 - I bet it would work to add a conditional there and use `-cpu power9`.

**Comment by cgwalters** [comment]
cc @ravanelli

**Comment by ravanelli** [comment]
> `cpu power9`.

ummmm, I can give it a try. But I think RHEL9 or CentOs9 wasn't suppose to run in a P8 host ...

**Comment by cgwalters** [comment]
>  But I think RHEL9 or CentOs9 wasn't suppose to run in a P8 host ...

Ah right sorry, I think you're right in this case we are using KVM.   OK whee, so we're using stream9 to make s390x work, but we can't use stream9 for ppc64le in our current setup.  

Hmmmm.  I guess we could use stream8 only for ppc64le here for now...

**Comment by cgwalters** [comment]
Or alternatively, use stream9 only for s390x.

This all said, what we're doing with the extensions here is really the just the "canary in the coal mine" for the overall [ppc64le issues](https://github.com/coreos/coreos-assembler/issues/2473) - we're going to run straight into this when we try to do stream9/rhel9 ppc64le on the current p8 hardware too.  

Probably what would help here as a general rule is to:

- detect if we're on p8 hardware
- if so, disable KVM (i.e. force on `COSA_NO_KVM=1`) when we're booting a newer userspace.  This will kick us into full CPU emulation mode.  And for that, we almost certainly will need [my suggestion above](https://github.com/openshift/os/issues/1000#issuecomment-1242237124)

**Comment by cgwalters** [comment]
OK I think https://github.com/openshift/os/pull/1004 will fix this, can someone give it a try?

**Comment by ravanelli** [comment]
>> OK I think https://github.com/openshift/os/pull/1004 will fix this, can someone give it a try?

I'm on it

**Comment by ravanelli** [comment]
> > we're going to run straight into this when we try to do stream9/rhel9 ppc64le on the current p8 hardware too.

We already got a P9 to move for the new CI. When we should start the RHEL9 change?

**Comment by ravanelli** [comment]
> OK I think #1004 will fix this, can someone give it a try?

The ppc64le test on a p8 passed:
```
[2/3] STEP 3/7: RUN dnf install -y createrepo_c golang
Fedora 36 - ppc64le                              16 MB/s |  76 MB     00:04    
Fedora 36 openh264 (From Cisco) - ppc64le       4.4 kB/s | 2.5 kB     00:00    
Fedora Modular 36 - ppc64le                     3.1 MB/s | 2.3 MB     00:00
```
