### ISSUE TITLE
4.12: legacy upload-oscontainer not tested in unprivileged context

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#1009]
Today RHCOS uses `upload-oscontainer` which is the legacy format we hope to get rid of as part of https://github.com/openshift/enhancements/blob/master/enhancements/ocp-coreos-layering/ocp-coreos-layering.md very very soon.

But for this instant as part of the migration to run the RHCOS pipeline fully unprivileged (same as FCOS pipeline) we should make `upload-oscontainer` work unprivileged.

I think the sanest path is to follow what we did in https://github.com/coreos/coreos-assembler/pull/2985 and run `podman` inside supermin; should just take a little bit of wrapping to do that.

**Comment by cgwalters** [comment]
Joseph and I had a quick chat about this and honestly I had some confusion/uncertainty on this point - his question was about whether we could somehow leverage the existing podman remote flow.

Now as best I can tell, the current pipeline only uses `podman remote` for non-x86_64 architectures.  For x86_64, all tasks are still executed in an OCP/Kubernetes pod.

I was arguing that we should apply the same supermin aka `runvm` approach we did for `cosa build-extensions-container`.

But...if we are using `podman remote` in general, then perhaps we could actually *directly* use `podman build` (via a remote) for this task.  But such a pattern would seem to require having podman remotes for x86_64 too right?

**Comment by ravanelli** [comment]
@cgwalters, you mean, we could use `podman build`  granting the access it needs in the remote? If we need it for x86_64, we may be able to enable that too. We are still in the process to get access to an official AWS for this purpose to build aarch64, once we get that, x86_64 is also available there.

**Comment by dustymabe** [comment]
> But...if we are using `podman remote` in general, then perhaps we could actually _directly_ use `podman build` (via a remote) for this task. But such a pattern would seem to require having podman remotes for x86_64 too right?

Right. We do have an `x86_64` "builder" for FCOS too just for the purpose of being a `podman --remote` target for building COSA and now FCOS buildroot. Look at the `build-cosa` and `build-fcos-buildroot` Jenkins jobs.

Right now we aren't using the `x86_64` builder for anything other than container builds so the instance we chose in AWS wasn't a bare metal instance (doesn't have `/dev/kvm`).

**Comment by cgwalters** [comment]
OK, makes sense to me then yes.  So in theory we could probably rework the legacy `cosa upload-oscontainer` code to use `podman --remote` too.

(I do have a feeling though that at least for x86_64, we should be using the fact that we're running in Kubernetes already to also *test the container natively* (and if we're doing that we could also build it via OCP too there), but either way this heavily intersects with the fact that our default test framework is really oriented towards booting machines and not running containers...)

**Comment by jmarrero** [comment]
If I understand correctly for this issue we want to:

- [ ] Use podman remote for non x86_64 architectures
- [ ] for x86_64 we build using ocp (deploy a buildconfig?)
- [ ] on x86_64 test the container on the cluster by starting it and waiting for ready state?

I do like the idea of doing the same thing on all architectures. If we are already doing `podman --remote` for everything else why not?

Also what kind of test we want for the container? If we did all the architectures with `podman --remote` and the test needed is to check contents inside the container we could have Dockerfile in all architectures doing a quick test.

**Comment by cgwalters** [comment]
I think we might as well use podman remote for all architectures for symmetry.

> Also what kind of test we want for the container? 

I guess in this case we could actually *test* with podman-remote too for that matter.  But clearly a test case could (in OCP/Kube) spin it up as a proper Service routing to a pod etc.  I don't think it's important though.  (What *is* more important IMO is that we test the base image as a container more than we are, which is a similar topic)

**Comment by cgwalters** [comment]
I think we want:

- teach `upload-oscontainer` to use `runvm` aka supermin
- A patch like this for the pipeline (this needs https://github.com/coreos/fedora-coreos-pipeline/pull/619 )

```
diff --git a/jobs/bump-lockfile.Jenkinsfile b/jobs/bump-lockfile.Jenkinsfile
index 1972aa5..e9be1ad 100644
--- a/jobs/bump-lockfile.Jenkinsfile
+++ b/jobs/bump-lockfile.Jenkinsfile
@@ -303,6 +305,12 @@ try { lock(resource: "bump-${params.STREAM}") { timeout(time: 120, unit: 'MINUTE
                         """)
                         archiveArtifacts allowEmptyArchive: true, artifacts: 'kola-testiso*${arch}.tar.xz'
                     }
+
+                    if (config.buildLegacyOsContainer) {
+                        stage('Build legacy oscontainer') {
+                            shwrap("cosa upload-oscontainer " + config.legacyOSContainerUploadURL)
+                        }
+                    }
                 }
                 if (arch == "x86_64") {
                     buildAndTest()
```

**Comment by cgwalters** [comment]
We had a realtime chat on this and I think the salient points are:

 - We already rely on `runvm` for the base rpm-ostree phase which this *derives* from
 - While it may make sense to use `podman remote` for stuff like this in the future, it really requires moving *everything* to be part of a remote worker (even for x86_64) in a consistent fashion.

To rephrase another way, think of this like `cosa buildextend-metal` - that generates a disk image, this generates a container, but both take as input the base ostree build and hence need (want) to be co-located with it.

**Comment by dustymabe** [comment]
> To rephrase another way, think of this like `cosa buildextend-metal` - that generates a disk image, this generates a container, but both take as input the base ostree build and hence need (want) to be co-located with it.

Note that in https://github.com/coreos/coreos-assembler/pull/3096 I made some updates to `cmd-remote-build-container` and `cmd-push-container-manifest` that should allow for doing the build of the new style extensions container via podman remote - getting the file back local and then pushing a manifest list to a registry and updating the meta.json with the appropriate information.

We use the push container manifest+update meta.json part today in https://github.com/coreos/fedora-coreos-pipeline/blob/5d68803097e7afa6e240c3a4deeaca3d6d3b50b9/jobs/release.Jenkinsfile#L184-L187

**Comment by cgwalters** [comment]
It makes total sense to me to use `push-container-manifest`.  I think we're more debating `cmd-remote-build-container` versus supermin.
