### ISSUE TITLE
consider going back to only having ART-built RHCOS

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#1017]
Today we have `rhel-coreos-8` built in CI payloads via a [Prow periodic once a day](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/os/openshift-os-master__periodic.yaml) and via ART in a more production fashion.

There are two major downsides to this:

1) The nightly runs once a day, which is just too slow
2) The nightly does not do change detection, meaning it will *always* regenerate the OS

These two things are related of course - we run more frequently if we have proper change detection.

This is all easier with the brand new [compose image](https://coreos.github.io/rpm-ostree/container/#creating-base-images) command.

That said...I am increasingly thinking we should turn off the Prow periodic and go back to having the ART builds propagate to CI.  Having two sources of truth for the OS state is problematic.

**Comment by travier** [comment]
+1 for not having periodics in Prow. This will however likely need pipeline work.
