### ISSUE TITLE
Define a new OS ID for /etc/os-release

### ISSUE THREAD

**Issue by bgilbert** [openshift/os#102]
`/etc/os-release` currently [has](https://github.com/openshift/redhat-release-coreos/blob/80c8ec6137f6df4540a7bbfd89b318b14382958f/redhat-release-coreos.spec#L58-L74):

```
ID="coreos"
```

That ID has long been used by Container Linux, so this seems likely to cause confusion.  Define a new ID instead.

**Comment by arithx** [comment]
Beat me to it!

`/etc/os-release` in Container Linux:
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1800.1.0
VERSION_ID=1800.1.0
BUILD_ID=2018-06-08-1029
PRETTY_NAME="Container Linux by CoreOS 1800.1.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

`/etc/os-release` in RHCOS:
```
NAME="Red Hat CoreOS"
VERSION="3.10"
ID="coreos"
ID_LIKE="rhel fedora"
VARIANT="CoreOS"
VARIANT_ID=coreos
VERSION_ID="3.10"
PRETTY_NAME="Red Hat CoreOS 3.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:3.10:GA:coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat 3"
REDHAT_BUGZILLA_PRODUCT_VERSION="3.10"
REDHAT_SUPPORT_PRODUCT="Red Hat"
REDHAT_SUPPORT_PRODUCT_VERSION="3.10"
```

**Comment by cgwalters** [comment]
Upstream is https://github.com/openshift/redhat-release-coreos

We could go with `ID="rhcos"` and `ID_LIKE="rhel fedora coreos"`?

**Comment by cgwalters** [comment]
Presumably there was some bug/discussion that brought this issue up - it'd be good to link to it or at least elaborate on it.

We need to think about the different cases here; what specific software was trying to determine by looking at the `ID` variable.  Some of those cases are perhaps better with `ID_LIKE` as I was suggesting, but it depends.

**Comment by arithx** [comment]
@cgwalters: I noticed it when getting `kola` running against RHCOS. There's an explicit check when spinning up a machine (https://github.com/coreos/mantle/blob/master/platform/platform.go#L292-L300) and when I checked it was nearly the same which could cause confusion.

**Comment by bgilbert** [comment]
In cases where a piece of software has opted to do OS detection rather than feature detection, I think we should give it an unambiguous answer in `ID` rather than trying to guess what behavior it cares about.  Packages can treat multiple IDs identically if desired.

`os-release(5)` says of `ID_LIKE`:
> It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from.

Since the relationship between CL and RHCOS is mostly conceptual rather than "packaging or programming interfaces", I'd argue we should also exclude `coreos` from `ID_LIKE`.

**Comment by cgwalters** [comment]
https://github.com/openshift/redhat-release-coreos/pull/1

Though, I'd say if we aren't managing to maintain some of the "packaging or programming interfaces" from CL we aren't succeeding - though a lot comes down to *which* packaging and interfaces of course.  A high level one is `docker` which we are today.

**Comment by cgwalters** [comment]
`Version: 3.10-7.5.95 (2018-06-14 19:12:31)`
