### ISSUE TITLE
Prow CI failing to schedule workloads

### ISSUE THREAD

**Issue by jlebon** [openshift/os#1028]
# Status update Oct 19 (by @cgwalters)

Tentatively claiming things are working, see [this passing job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/coreos_rpm-ostree/4092/pull-ci-coreos-rpm-ostree-main-fcos-e2e/1582728979352129536).

We've been seeing failures to schedule pods that use `/dev/kvm` on the build02 cluster, which affects several important repositories (e.g. openshift/os, many coreos/ repos).

There was a whole cascading series of failures/changes going on here.

### kubelet device plugin breakage

- build02 was updated to an [OCP 4.12 EC](https://amd64.ocp.releases.ci.openshift.org/#4-dev-preview) which in turn brought in a new kubelet
- The new kubelet brought in https://github.com/kubernetes/kubernetes/issues/112395 which broke our KVM hook
- I [updated the code](https://github.com/cgwalters/kvm-device-plugin/commits/master) to the latest kubevirt helper library which had an attempted fix for this, but it turns out [the fix was broken](https://github.com/kubevirt/device-plugin-manager/pull/19#issuecomment-1284034804)
- There's now an in-flight [fix for the above](https://github.com/kubevirt/device-plugin-manager/pull/21) - meanwhile I've already patched our copy and deployed in on build02
- On the plus side, **we caught a bug that would have broken KubeVirt on OCP 4.12**

### node taints

Separately, it seems there was a change to add some taints to nodes (on all build clusters?) and our daemonset needs adjustment to tolerate that.  PR in https://github.com/openshift/release/pull/33187 - meanwhile I've hot fixed the deployment.

### machineset types

And yet another distinct issue that happened recently: We [switched the default instance type in GCP for CI](https://github.com/openshift/release/commit/db30cbcb6eebf11ec6beb6a8446c3dbad279eb7a) and it turns out this instance type doesn't enable nested virtualization.

*However* it seems that at least on build02 there's still some autoscaling for n1 instances...so we have a passing job at least.

## Original issue follows

Prow CI is failing with errors like:

```
* 2x default-scheduler: 0/42 nodes are available: 12 node(s) had untolerated taint {node-
role.kubernetes.io/ci-builds-worker: ci-builds-worker}, 12 node(s) had untolerated taint
{node-role.kubernetes.io/ci-tests-worker: }, 14 Insufficient cpu, 2 node(s) had untolerated
taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had
untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-
role.kubernetes.io/master: }, 4 Insufficient memory, 42 Insufficient devices.kubevirt.io/kvm, 7
node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}. 
preemption: 0/42 nodes are available: 3 No preemption victims found for incoming pod, 39
Preemption is not helpful for scheduling.
```

Current theory is that `/dev/kvm` is no longer available on the build02 cluster.

**Comment by cgwalters** [comment]
OK I think one thing that may have changed here is we no longer use Github auth for clusters, so I think I need to s/cgwalters/walters/ ?

I am also now thinking we should do https://github.com/cgwalters/kvm-device-plugin/issues/1

**Comment by cgwalters** [comment]
Ah, this is all really well documented at https://docs.ci.openshift.org/docs/how-tos/rbac/

OK, did https://github.com/openshift/release/pull/33182

**Comment by cgwalters** [comment]
OK with the new access :key: I see this in the pod logs:

```
I1017 17:42:35.370550       1 kvm.go:13] Starting kvm-device-plugin
I1017 17:42:35.370655       1 manager.go:42] Starting device plugin manager
I1017 17:42:35.370662       1 manager.go:46] Registering for system signal notifications
I1017 17:42:35.370982       1 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
I1017 17:42:35.371056       1 manager.go:60] Starting Discovery on new plugins
I1017 17:42:35.371074       1 manager.go:66] Handling incoming signals
I1017 17:42:35.371100       1 kvm.go:40] Discovered /dev/kvm
I1017 17:42:35.371110       1 manager.go:71] Received new list of plugins: [kvm]
I1017 17:42:35.371161       1 manager.go:110] Adding a new plugin "kvm"
I1017 17:42:35.371178       1 kvm.go:49] Creating device plugin kvm
I1017 17:42:35.371186       1 plugin.go:64] kvm: Starting plugin server
I1017 17:42:35.371190       1 plugin.go:95] kvm: Starting the DPI gRPC server
I1017 17:42:35.371507       1 plugin.go:113] kvm: Serving requests...
I1017 17:42:45.375420       1 plugin.go:129] kvm: Registering the DPI with Kubelet
I1017 17:42:45.375564       1 plugin.go:141] kvm: Registration for endpoint devices.kubevirt.io_kvm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8966a6]

goroutine 50 [running]:
k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1.(*DevicePluginOptions).Size(...)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1/api.pb.go:1151
k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1.(*DevicePluginOptions).Marshal(0x0, 0x969180, 0x0, 0x7ffb500640e8, 0x0, 0x91e501)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1/api.pb.go:692 +0x26
google.golang.org/grpc/encoding/proto.codec.Marshal(0x969180, 0x0, 0x922500, 0x939640, 0x40faff, 0xc000012000, 0x922500)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x199
google.golang.org/grpc.encode(0x7ffb50686c00, 0xd7b478, 0x969180, 0x0, 0xd7b478, 0x40faff, 0xc000012000, 0x92d720, 0x932b00)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/rpc_util.go:543 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc0001d9ce0, 0xa53298, 0xc000001b00, 0xc00035c000, 0x969180, 0x0, 0x0, 0x0, 0xc000324038, 0x0, ...)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/server.go:833 +0x91
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d9ce0, 0xa53298, 0xc000001b00, 0xc00035c000, 0xc000250ba0, 0xd3e680, 0x0, 0x0, 0x0)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/server.go:1030 +0x578
google.golang.org/grpc.(*Server).handleStream(0xc0001d9ce0, 0xa53298, 0xc000001b00, 0xc00035c000, 0x0)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000260c0, 0xc0001d9ce0, 0xa53298, 0xc000001b00, 0xc00035c000)
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cgwalters/kvm-device-plugin/vendor/google.golang.org/grpc/server.go:708 +0xa5
```

looking

**Comment by cgwalters** [comment]
Pushed https://github.com/cgwalters/kvm-device-plugin/commit/63006ba38847e32f3efa7e7a7321b8bb450fbd9c - let's see

**Comment by cgwalters** [comment]
OK, daemonset is now healthy, though I only see 3 replicas.  It's not clear to me why we only have 3 - I don't think there are really 3 nodes?  Will investigate.

**Comment by bgilbert** [comment]
Looks like CI runs in cosa are still failing: https://github.com/coreos/coreos-assembler/pull/3125#issuecomment-1281400032

**Comment by cgwalters** [comment]
OK, I think I figured it out; we needed to add a toleration. 
https://github.com/openshift/release/pull/33187

I'm not sure where the `ci-builds-worker` taint is coming from.  Perhaps we should just tolerate all taints, but for now I think this will unblock us.

(I already applied the change live, so let's see if it works)

**Comment by cgwalters** [comment]
Next problem is

```
I1018 00:34:50.649786 1 kvm.go:13] Starting kvm-device-plugin
I1018 00:34:50.649914 1 manager.go:42] Starting device plugin manager
I1018 00:34:50.649940 1 manager.go:46] Registering for system signal notifications
I1018 00:34:50.650784 1 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
I1018 00:34:50.650881 1 manager.go:60] Starting Discovery on new plugins
I1018 00:34:50.650898 1 manager.go:66] Handling incoming signals
I1018 00:34:50.650941 1 kvm.go:40] Discovered /dev/kvm
I1018 00:34:50.650961 1 manager.go:71] Received new list of plugins: [kvm]
I1018 00:34:50.651059 1 manager.go:110] Adding a new plugin "kvm"
I1018 00:34:50.651078 1 kvm.go:49] Creating device plugin kvm
I1018 00:34:50.651092 1 plugin.go:64] kvm: Starting plugin server
I1018 00:34:50.651102 1 plugin.go:127] kvm: Registering the DPI with Kubelet
I1018 00:34:50.651556 1 plugin.go:139] kvm: Registration for endpoint devices.kubevirt.io_kvm
E1018 00:35:00.654347 1 plugin.go:156] kvm: Registration failed: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
E1018 00:35:00.654409 1 plugin.go:157] kvm: Make sure that the DevicePlugins feature gate is enabled and kubelet running
E1018 00:35:00.654480 1 plugin.go:78] error registering with device plugin manager: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
E1018 00:35:00.654491 1 manager.go:214] Failed to start plugin's "kvm" server, atempt 1 ouf of 3 waiting 3000000000 before next try: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
```

Looking at that...

**Comment by cgwalters** [comment]
I pushed https://github.com/cgwalters/kvm-device-plugin/commit/17c86040335a9a7435eba237cf0e106fc0f51613 which got the pods running again...and it looks like I need to add a few more taint tolerations in https://github.com/openshift/release/pull/33187
(But for now I did that manually)

But then, now that the pods are running successfully, the next problem seems to be that we're actually missing `/dev/kvm` on the host?

**Comment by cgwalters** [comment]
OK going through the checklist at https://cloud.google.com/compute/docs/instances/nested-virtualization/overview 

From that page,

> Restrictions:
> You can't use E2, N2D, N1 with attached GPUs, and A2 [machine types](https://cloud.google.com/compute/docs/machine-types).

And then looking, at the launched instance types in a cluster-bot cluster, it looks like it was https://github.com/openshift/release/commit/db30cbcb6eebf11ec6beb6a8446c3dbad279eb7a that broke this.

**Comment by jlebon** [comment]
> Tentatively claiming things are working, see [this passing job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/coreos_rpm-ostree/4092/pull-ci-coreos-rpm-ostree-main-fcos-e2e/1582728979352129536).

Indeed. Also saw a pass in https://github.com/coreos/coreos-assembler/pull/3126. Let's close this. We can always reopen if it's not fully gone.

Thanks for tracking this down!
