### ISSUE TITLE
4.12: ext.config.shared tests are not run anymore

### ISSUE THREAD

**Issue by travier** [openshift/os#1033]
Tests shared from FCOS config are apparently not run anymore. This apparently only impacts 4.12 so it might be a COSA issue.

**Comment by dustymabe** [comment]
This may be some fallout from the recent `yumrepos` concept being added to COSA: https://github.com/coreos/coreos-assembler/pull/3045/files

**Comment by travier** [comment]
Moving to COSA as `cosa kola list | grep shared` works on 4.11 but not on 4.12.

**Comment by travier** [comment]
https://github.com/coreos/coreos-assembler/issues/3135
