### ISSUE TITLE
SCOS: Secure Boot tests are failing

### ISSUE THREAD

**Issue by travier** [openshift/os#1039]
See https://github.com/openshift/os/pull/1026, https://github.com/coreos/coreos-assembler/pull/3145.

**Comment by aleskandro** [comment]
In some previous builds, we pinned a previous version of the kernel to fix it. We didn't get in time to look further till now.

**Comment by travier** [comment]
Can you open an issue here when you have such an issue so that we can track it?

**Comment by aleskandro** [comment]
For sure, we/I will either open issues or PRs here and avoid those workarounds.

**Comment by cgwalters** [comment]
> In some previous builds, we pinned a previous version of the kernel to fix it. We didn't get in time to look further till now and to release the MVP:

To repeat, I think this change really should have been done in this repository.

That said, the right place to track this seems to be linked from
https://lists.centos.org/pipermail/centos-devel/2022-October/120639.html
:arrow_right: 
https://bugzilla.redhat.com/show_bug.cgi?id=2138019

**Comment by bgilbert** [comment]
Seeing SCOS 4.12 build failures in https://github.com/openshift/os/pull/1051:

```
error: Failed to parse selector: kernel-5.14.0-168.el9
error: failed to execute cmd-fetch: exit status 1
```

**Comment by travier** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2138019 > Commented there that this appears to be fixed for us now.
