### ISSUE TITLE
systemd units created by Ignition don't have their symlinks created

### ISSUE THREAD

**Issue by arithx** [openshift/os#105]
Ignition expects that `systemd-preset` will run and take care of creating relevant symlinks.

As a result currently any systemd unit created by Ignition will not run despite being enabled.

Per @cgwalters `systemd-preset` won't run on RHCOS:
that's another consequence of the `ConditionFirstBoot=` not being set - it only works for systems with empty `/etc` (neither classic fedora/rhel nor ostree-based systems)

**Comment by peterbaouoft** [comment]
https://github.com/dustymabe/bootengine/pull/11 also seems to be related?

**Comment by cgwalters** [comment]
This was fixed.

**Comment by peterbaouoft** [comment]
Yup, can confirm it, I see the following behaivor on the newly built ami image. The ami id is ami-0918132e44967d193, built on July 27th 
```
[root@ip-172-18-10-219 ~]# journalctl -xe | grep preset
Jun 27 20:25:45 localhost.localdomain systemd[1]: Populated /etc with preset unit settings.
[root@ip-172-18-10-219 ~]# rpm-ostree status 
State: idle; auto updates disabled
Deployments:
* ostree://rhcos:openshift/3.10/x86_64/os
                   Version: 3.10-7.5.165 (2018-06-27 09:27:44)
                    Commit: 05b032f3aab81ef961500861435731d6de847fd89e2e7de2e99b55274901492c
```
