### ISSUE TITLE
journalctl missing conmon sys identifier

### ISSUE THREAD

**Issue by rickydjohn** [openshift/os#1061]
container logs on worker nodes are logging with the syslog identifier conmon while the same container logs on master is using hyperkube identifier. Our logging pipeline uses syslog identifier for picking up logs from nodes. Because of the issue mentioned earlier, I am unable to consume logs from pods on master nodes.

Thanks in advance for your support..

**Comment by travier** [comment]
Please report your issue to the right support channel. See https://github.com/openshift/os/blob/master/docs/faq.md#q-where-should-i-report-issues-with-openshift-container-platform-or-red-hat-coreos
