### ISSUE TITLE
[4.13-9.2] ext.config.shared.networking failures

### ISSUE THREAD

**Issue by marmijo** [openshift/os#1096]
`ext.config.shared.networking.nameserver` and `ext.config.shared.networking.bridge-static-via-kargs` are failing in rhel-9.0 builds. We need  to investigate the cause of these failures.

xref: https://github.com/openshift/os/pull/1095 & https://github.com/openshift/os/pull/1097

**Comment by Adam0Brien** [comment]
both tests passed, cant reproduce failure.
