### ISSUE TITLE
rdgo failure with golang/pivot

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#111]
Not sure what's going on.  It seems like we're missing the BR on golang.

**Comment by ashcrow** [comment]
Trying to replicate the failure.

**Comment by cgwalters** [comment]
I think this came up in the Ignition review too right?  Let's do the same thing it does, e.g.:

```
BuildRequires: %{?go_compiler:compiler(go-compiler)}%{!?go_compiler:golang >= 1.6.2}
```

**Comment by ashcrow** [comment]
That could be it. I just tried running the commands locally via rdgo and they succeed ... but my host is Fedora.

**Comment by ashcrow** [comment]
Currently the spec has:
```
BuildRequires:  git
%if 0%{?fedora}
BuildRequires:  %{?go_compiler:compiler(go-compiler)}%{!?go_compiler:golang >= 1.6.2}
%endif #fedora
%if 0%{?centos}
BuildRequires:  golang
%endif #centos
```

**Comment by ashcrow** [comment]
@cgwalters https://github.com/ashcrow/pivot/pull/7

**Comment by cgwalters** [comment]
Seems to have worked.
