### ISSUE TITLE
[4.13-8.6] ext.config.shared.ignition.resource.remote failing

### ISSUE THREAD

**Issue by aaradhak** [openshift/os#1190]
The kola test `ext.config.shared.ignition.resource.remote` is found to be failing as we don't have the new Ignition in `4.13-8.6`. We can track the updates for this here.

**Comment by cgwalters** [comment]
Dup of https://github.com/openshift/os/issues/1187 ?

**Comment by cgwalters** [comment]
Note we don't care about 4.13-8.6 and can safely turn off the stream now.

**Comment by jlebon** [comment]
We've had a request to try to keep it alive for now to help with debugging 9.2 failures (by having another comparison point). This is just doing the minimum to unbreak it until we fully kill the stream.

**Comment by travier** [comment]
This test will never pass in 4.13-8.6

**Comment by travier** [comment]
It should be skipped

**Comment by jlebon** [comment]
Right, this is just the tracker issue to point the denylist entry at.

**Comment by aaradhak** [comment]
I opened this as I found the #1187 to be closed already. Was wondering if it would be need to be reopened. We can track it here or close this and track it in #1187

**Comment by travier** [comment]
We'll need this backported to 4.13 unless we never move the 4.13-8.6 pipeline to the 4.13 branch.

**Comment by travier** [comment]
Closing as we're not shipping this combination (4.13 8.6).
/close
