### ISSUE TITLE
docker group or not

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#121]
We need to decide whether to include a `docker` group or not.   Today CL does, Fedora does not.  Context:  https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by dustymabe** [comment]
would it be bad (maintenance) to adopt a policy that's different from the team that manages the container tech (podman, docker, cri-o)?

**Comment by cgwalters** [comment]
Moved to https://github.com/coreos/fedora-coreos-tracker/
