### ISSUE TITLE
drop ext.config.shared.multipath.multipathd-service-fix

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#1213]
```
Mar 21 19:16:23 qemu0 kola-runext-multipathd-service-fix[1862]: + fatal 'Found fixed dracut multipath module but quickfix is present too'
Mar 21 19:16:23 qemu0 kola-runext-multipathd-service-fix[1862]: + echo 'Found fixed dracut multipath module but quickfix is present too'
Mar 21 19:16:23 qemu0 kola-runext-multipathd-service-fix[1862]: Found fixed dracut multipath module but quickfix is present too
```

**Comment by cgwalters** [comment]
We really need to find a better way to feel like we're constraining our technical debt than things like this.  This popped up right in the hot path while trying to do 9.2 work, and the test is immediately demanding the drop of the workaround or _we stop shipping OS updates by default_.

This one seems instead very much more warning-at-best worthy.

**Comment by dustymabe** [comment]
FCOS piece of this in https://github.com/coreos/fedora-coreos-config/pull/2313
