### ISSUE TITLE
[4.13-9.2] Allow root login and password authentication that both are disabled for rhcos8

### ISSUE THREAD

**Issue by HuijingHei** [openshift/os#1216]
Check /etc/ssh/sshd_config in rhcos9, which should allow root login, also password authentication.
```
[root@cosa-devsh ~]# grep PermitRootLogin /etc/ssh/sshd_config
#PermitRootLogin prohibit-password

[root@cosa-devsh ~]# grep PasswordAuthentication /etc/ssh/sshd_config
#PasswordAuthentication yes
```
They are both disabled for rhcos8 according to https://github.com/openshift/os/blob/master/common.yaml#L65-L67, and mismatch the sed condition in rhcos9, is it necessary to disabled them for rhcos9? (The change should be minor, but need to confirm the requirement)

**Comment by HuijingHei** [comment]
From @cgwalters :
OK I think what happened here is...a long time ago, the redhat-coreos config git was a fork of fedora-coreos-config.   This specific line of code dates to https://github.com/openshift/os/commit/3178c3d866f2f4b4cbdd4d09f45d7b02025ff985
Then in FCOS, https://github.com/coreos/fedora-coreos-config/commit/48be8b6672ebbd48ff6f032738f883744e28fdd5 happened, but we never dropped the corresponding logic from RHCOS.
My PoV is we should delete that line, and inherit the FCOS logic which is really the same as RHEL9's logic now too.
So by deleting this little bit of code, we make RHEL CoreOS more like RHEL.  (And also, not different from FCOS)

**Comment by cgwalters** [comment]
OK yeah, I traced the change here back to pre-public commit e6a1207b439cf4b4e73547afd8c878fed72683e0 Fri May 31 2019 -0400 AKA https://url.corp.redhat.com/cef7fe3

This is still relatively early days.  It was later that year in commit 7c21ba398aca1a1787845038539c7906a2181e04 Thu Jul 18 2019 -0400 titled "Use fedora-coreos-config as a git submodule" when things were unified, but we didn't merge those two bits of code.

**Comment by cgwalters** [comment]
Just to reiterate though: since we're on track to ship 4.13 with this change anyways (i.e. switching from `PermitRootLogin no` to `PermitRootLogin prohibit-password`) and it'd take extra effort to undo the switch now and return to RHEL8 code, I think what's best is to just delete the text and effectively inherit the change from RHEL8 to RHEL9.

**Comment by HuijingHei** [comment]
Agree, FCOS does not have the limitation. I found this issue when I use tmt which is using root by default to login the guest, for rhcos8 root is disabled, but for rhcos9 root is allowed. We can remove that for 4.13-9.2 if there is no security concerns.
