### ISSUE TITLE
Missing binary: etcdctl

### ISSUE THREAD

**Issue by arithx** [openshift/os#124]
`etcdctl` is present on Container Linux.

Is this something that we'd want to ship in the base OS or something that we expect users to run inside of a container?

**Comment by ashcrow** [comment]
Good catch, but I don't believe we will need to include ``etcdctl`` as part of the base RHCOS image. IMHO if someone wants to interact with a clusters ``etcd`` instance they would likely do so via a workstation rather then getting on cattle nodes.

**Comment by arithx** [comment]
https://projects.engineering.redhat.com/browse/COREOS-186

**Comment by cgwalters** [comment]
Moved to https://github.com/coreos/fedora-coreos-tracker/
