### ISSUE TITLE
Add cri-tools to RHCOS

### ISSUE THREAD

**Issue by ashcrow** [openshift/os#126]
@mrunalp @lsm5 have noted that `cri-o` will need [cri-tools](https://github.com/kubernetes-incubator/cri-tools). This should be added to the RHCOS composes.

**Comment by lsm5** [comment]
@mrunalp please remind me, so installation of cri-o should pull in cri-tools as well, yes? Or is it the other way around?

@fkluknav could you please take care of the dependency change for RHEL packages once @mrunalp confirms?
