### ISSUE TITLE
s390x/Secure Execution: Firstboot fails during `ignition-ostree-growfs.service`

### ISSUE THREAD

**Issue by jschintag** [openshift/os#1264]
The Secure Execution is unable to boot, failing at `ignition-ostree-growfs.service`.
```
Displaying logs from failed units: ignition-ostree-growfs.service
Apr 18 08:42:09 systemd[1]: Starting Ignition OSTree: Grow Root Filesystem...
Apr 18 08:42:09 ignition-ostree-growfs[2448]: mount: /sysroot: special device /dev/disk/by-label/root does not exist.
Apr 18 08:42:09 systemd[1]: ignition-ostree-growfs.service: Main process exited, code=exited, status=32/n/a
Apr 18 08:42:09 systemd[1]: ignition-ostree-growfs.service: Failed with result 'exit-code'.
Apr 18 08:42:09 systemd[1]: Failed to start Ignition OSTree: Grow Root Filesystem.

Generating "/run/initramfs/rdsosreport.txt"
```
This just started with `414.92.202304172216-0`, the build before is working. Looking at the diff, there are no relevant package diffs. The only notable difference between the builds is the f-c-c bump.
Need to investigate further.

**Comment by jschintag** [comment]
Issue seems to have been introduced by this PR https://github.com/coreos/fedora-coreos-config/pull/2320

**Comment by jlebon** [comment]
Will dig into this.

**Comment by jschintag** [comment]
I think it might be timing related, because in the emergency console the device label exists

**Comment by jschintag** [comment]
I just finished testing it and a simple `Require=/dev/disk/by-label/root` in the `ignition-ostree-growfs.service` seems to fix it. I will post a PR

**Comment by jschintag** [comment]
Ok, while it does seem to help, i still run into the problem. It might just have taken down the error rate from 100% to ~50%

**Comment by jschintag** [comment]
Waiting on https://github.com/openshift/os/pull/1268 to pull the fix into RHCOS

**Comment by jschintag** [comment]
Bump has landed and latest nightly is working correctly.
