### ISSUE TITLE
c9s: remove / override mitigation kargs

### ISSUE THREAD

**Issue by vrutkovs** [openshift/os#1311]
When OKD SCOS is being installed it may use FCOS as a starting image (for clouds where we don't upload SCOS artifacts yet). This causes default FCOS kernel arguments to be retained - which means default `mitigations=auto,nosmt` are being kept and installation fails as only half the CPUs are being used. 
For AWS the workaround is to use `m6a.xlarge` flavor where nosmt doesn't disable CPUs.

In OKD FCOS bootstrap automatically mixes in a MachineConfig which sets `mitigations=off` and all nodes boot without this karg after pivot. Ideally, we should find a solution to this in C9S manifest (and fall back to installer script if not possible)

**Comment by sdodson** [comment]
Or use any other instance type which is either not subject to `nosmt` disabling of SMT cores or has four cores available even after smt cores have been disabled.  ie: m6i.xlarge only yields 2 cores and doesn't work but m6i.2xlarge would yield 4.

**Comment by LorbusChris** [comment]
This problem will go away once the installer switches to use SCOS bootimages, so there's no pivot that retains default kargs from FCOS.

More generally, this would be solved by https://github.com/coreos/rpm-ostree/issues/3738

**Comment by cgwalters** [comment]
Just a side note: A [bootc install --takeover](https://github.com/containers/bootc/pull/78) flow would mean there's no  "downgrade" because we entirely nuke and replace everything in the system (including the systemd journal, etc.).  But, things like what image metadata flags are set are still relevant here.
