### ISSUE TITLE
c9s: kola/rpm-ostree/replace-rt-kernel fails with "error: Bus owner changed, aborting."

### ISSUE THREAD

**Issue by jmarrero** [openshift/os#1315]
rt-kernel-replace test fails with:
```
Jun 12 14:01:32 qemu0 kola-runext-replace-rt-kernel[2030]: Resolving dependencies...done
Jun 12 14:01:32 qemu0 kola-runext-replace-rt-kernel[2030]: error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`.
```

`error: Bus owner changed, aborting.` is the error. This error is commonly seen in low memory scenarios but for some reason even with 4GB I am seeing the test fail like this on SCOS.

It is currently added to kola-denylist.yaml

**Comment by cgwalters** [comment]
> error: Bus owner changed, aborting. is the error.

The real error message is in the journal though, did you find anything there?

**Comment by jmarrero** [comment]
No journal saved on CI and can't replicate locally. Hence why I created this to debug later.

**Comment by LorbusChris** [comment]
@jmarrero was this fixed for SCOS with https://github.com/openshift/os/commit/49d17ee558bf4a596a298019cf5879ceaf192562?

**Comment by jmarrero** [comment]
No, still need to look into it.

**Comment by jschintag** [comment]
@jmarrero are there any updates on this?

**Comment by marmijo** [comment]
@jmarrero are there any updates on this issue?

**Comment by jmarrero** [comment]
no, updates. I can will try taking the two test failures I have assigned the next sprint if nothing else higher priority comes by.
