### ISSUE TITLE
Discussion: SSH Shell Greeter

### ISSUE THREAD

**Issue by ashcrow** [openshift/os#137]
In an early meetings we had talked about gating ssh access via a menu of some kind. Over the weekend I threw together [this](https://github.com/ashcrow/rhcos-shell-greeter) as a possible starting point. The questions I have are:

1. Do we still want to gate ssh access via a menu in RHCOS?
2. If so, what menu options should be present?
3. If so, does [this](https://github.com/ashcrow/rhcos-shell-greeter) look like a good starting point?

/cc @cgwalters @bgilbert @dustymabe @lucab 

**Note**: This isn't something we *need* to figure out now, but since I put together the above code I figured we might as well restart the conversation.

**Comment by dustymabe** [comment]
yeah i'm not sure. I definitely would want scripted SSH things to still work. One other option is that we have a ominous MOTD but then give them the shell.

some people are going to just be annoyed. Others aren't going to care. If we do go down this path then having an option on this menu for (`disable this menu`) might be nice.

**Comment by dustymabe** [comment]
also can we really not write a million go binaries for our systems? every time you plop down another go binary you've got the entirety of golang compiled in. I understand not wanting python, but we really aren't doing ourselves any favor by trading python and it's standard library with a million go binaries each statically compiled.

**Comment by ashcrow** [comment]
> some people are going to just be annoyed. Others aren't going to care. If we do go down this path then having an option on this menu for (disable this menu) might be nice.

We want to discourage people from trying to manage the OS as that would be a failure of the OS. But I :+1: the idea of being able to disable it if wanted.

**Comment by ashcrow** [comment]
> also can we really not write a million go binaries for our systems? 

By default it's not static ... but ``make static`` will make a static binary.

**Comment by cgwalters** [comment]
> also can we really not write a million go binaries for our systems?

Yeah, this is something to debate.

**Comment by dustymabe** [comment]
> By default it's not static ... but make static will make a static binary.

if we can get proper shared library support and it works (i.e. if I made `rhcos-shell-greeter-2` and just changed one line of code, then I'd get a proportionally larger system) then I'm happy with whatever.

**Comment by ashcrow** [comment]
It's build flags that define if it's static, dynamic, etc.. However, I think we are veering away from the what I was hoping to discuss in this issue and getting into the technical details of language choice or binary deployment possibilities.


> 1. Do we still want to gate ssh access via a menu in RHCOS?
- People may want to manage RHCOS through ssh scripts and having a menu would be annoying
- Maybe we should just use words in a MOTD saying "hey you shouldn't have to be here you know" :-)

> 2. If so, what menu options should be present?
> 3. If so, does this look like a good starting point?

**Comment by dustymabe** [comment]
so the less disruptive method would be to use motd. I know we are planning to use motd for greenboot as well to notify the user of non fatal startup failures. If we don't use an motd and do use a menu then I think we should mimic motd functionality so that other things that try to deliver a message via motd won't get lost in our boot menu.

so the bigger question is motd vs menu. If we do go with menu then what you have is a good start, but note my message above about including additional messages for the user (i.e. mimic motd).

**Comment by ashcrow** [comment]
>  If we don't use an motd and do use a menu then I think we should mimic motd functionality so that other things that try to deliver a message via motd won't get lost in our boot menu.

Agreed.

> so the bigger question is motd vs menu. If we do go with menu then what you have is a good start, but note my message above about including additional messages for the user (i.e. mimic motd).

That's fair. As a quick aside, here is (almost) [the same thing in rustlang](https://gist.github.com/ashcrow/4e18689505e2fdfcc58b8d0c4f4119ea) which may be preferable.

**Comment by bgilbert** [comment]
The answer given by Container Linux tradition is: tell users not to do things, but don't get in the way of them doing them.  I'm uncomfortable with the menu approach, and I'm fairly sure we wouldn't want to use it for Fedora CoreOS.  The answer for RHCOS should probably emanate from Red Hat tradition, though, and I can't speak to that.

</2¢>

**Comment by cgwalters** [comment]
I am not aware of any Red Hat tradition here.  I would agree this is not a Fedora CoreOS thing (although admins may like the idea).

Here's something perhaps even more controversial: we don't listen on SSH at all by default (can be enabled via ignition), and we auto-terminate if an RHCOS node hasn't joined a cluster in 1 day (or so).

**Comment by ashcrow** [comment]
I 100% agree that FCOS would not likely use a system like this. It would be targeted for RHCOS. 

If RHCOS won't have sshd running then this may be a moot point as there is no need to warm users they probably shouldn't be doing something they are not able to do :-)

**Comment by ashcrow** [comment]
We won't be going down this path. Instead we are running with SSH access causing a kube taint.

**Comment by vinayakshnd** [comment]
@ashcrow
I am new to RHCOS. What would be way to enable SSH to RHCOS (if at all user still wants to do that) ? What would be the ignition for that ? My terraform ignition which is working for CoreOS AMIs, did not work for RHCOS.

```
data "ignition_user" "core_user" {
    name = "core"
    home_dir = "/home/px/"
    shell = "/bin/bash"
    password_hash = "***"
}

data "ignition_filesystem" "rootfs" {
    name = "root"
    mount {
        device = "/dev/disk/by-label/ROOT"
        format = "ext4"
        options = ["-L", "ROOT"]
    }
}

data "ignition_file" "sshd_conf" {
    filesystem = "root"
    path = "/etc/ssh/sshd_config"
    mode = "384"
    content {
       content =<<-EOF
              UsePrivilegeSeparation sandbox
              Subsystem sftp internal-sftp
              PermitRootLogin yes
              AllowUsers core
              PasswordAuthentication yes
              PubkeyAuthentication yes
              AuthorizedKeysFile .ssh/authorized_keys
              ChallengeResponseAuthentication yes
              EOF
    }
}

data "ignition_systemd_unit" "sshd" {
  name = "sshd.service"
  enabled = true
}

data "ignition_config" "userdata" {
  users = [
    "${data.ignition_user.core_user.id}",
  ]
  filesystems = [
    "${data.ignition_filesystem.rootfs.id}",
  ]
  files = [
    "${data.ignition_file.sshd_conf.id}",
  ]
  systemd = [
    "${data.ignition_systemd_unit.sshd.id}",
  ]
}
```

SSH still fails with `port 22: Connection refused`
