### ISSUE TITLE
'initramfs-args is deprecated' warning message

### ISSUE THREAD

**Issue by jcapiitao** [openshift/os#1377]
While building OKD/SCOS variant image I spotted the warning message below in `cosa fetch` output:
`warning: initramfs-args is deprecated, use /etc/dracut.conf.d`

IIUC, it's due to the declarative config below
https://github.com/openshift/os/blob/b86ac33c66034de9d8abfda599e2209ceeb7bd4d/common.yaml#L38-L59

FCOS moved the config files to `/etc/dracut.conf.d` dir last year with https://github.com/cgwalters/fedora-coreos-config/commit/1a29ef849f1fba0ae64d48e143a71d3f94bd91ac

Maybe we should try to move as well, I might give a try

**Comment by jlebon** [comment]
It just so happened that I recently opened a PR to do exactly this: https://github.com/openshift/os/pull/1376 :)

**Comment by jcapiitao** [comment]
Thank you @jlebon :+1:
