### ISSUE TITLE
rhcos-selinux-policy-upgrade.service broken on OKD/FCOS

### ISSUE THREAD

**Issue by nate-duke** [openshift/os#1381]
We've had https://github.com/okd-project/okd/issues/1475 open for a while that seems to be a problem in FCOS used in OKD, specifically with some assumptions made based on RHCOS, see https://github.com/okd-project/okd/issues/1475#issuecomment-1513272933 for details.

It's a problem mainly because new node provisioning must be manually coaxed with a restorecon (eliminating automated scaling, machine-health-check recovery and ... seamless updates!).

Please let us know if there's any information that we can provide to help facilitate a fix here. I'm unable to verify the full impact of the fix mentioned in the above comment as I don't have access to RHCOS but I'm happy to help otherwise if I can.

Thank you very much for looking into this.

**Comment by travier** [comment]
Fixing https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/libexec/rhcos-rebuild-selinux-policy#L5 here will fix it for OKD-SCOS but not for OKD-FCOS. Not sure were this file is for OKD-FCOS.

/remove-lifecycle stale

**Comment by travier** [comment]
However this is for older boot images, so fixing it is more difficult than that. The best workaround is to setup a MachineConfig like: https://github.com/okd-project/okd/issues/1317#issuecomment-1257004454

**Comment by travier** [comment]
Closing as we did https://github.com/openshift/os/issues/1428. The workaround above is likely the best path forward until we have boot image updates.
