### ISSUE TITLE
[rhel-9.4 variant] some kola tests fail with Found legacy sysroot.readonly flag

### ISSUE THREAD

**Issue by marmijo** [openshift/os#1384]
When building a rhel-9.4 variant, all kola reprovision tests  fail on aarch64, ppc64le, and s390x with the same error message. EDIT: some other kola tests are failing with this same error message on x86_64. Those are listed below in a separate comment.
```
ostree-prepare-root[2206]: Found legacy sysroot.readonly flag, not configured in ostree/prepare-root.conf
```
It looks like ostree-prepare-root is potentially the issue here.
The test runs just fine on 4.15-9.2 multi-arch builds and output:
```
[    7.910212] ostree-prepare-root[1116]: preparing sysroot at /sysroot
[    7.910503] ostree-prepare-root[1116]: Resolved OSTree target to: /sysroot/ostree/deploy/rhcos/deploy/96d020aae31deb0f28ccb464c9437f80673a8554307286af991ddc66e498b0d5.0
[    7.910925] ostree-prepare-root[1116]: filesystem at /sysroot currently writable: 1
[    7.911107] ostree-prepare-root[1116]: sysroot.readonly configuration value: 1
[   11.585987] systemd[1]: ostree-prepare-root.service: Deactivated successfully.
``` 

But the 4.15-9.4 multi-arch reprovision tests look like this:
```
[   74.622657] ostree-prepare-root[1876]: Resolved OSTree target to: /sysroot/ostree/deploy/rhcos/deploy/c9441e1047b7e82ae08cd2328eeeb1c486f9e5104fde9fc5a53558850d2fca1c.0
[   74.623804] ostree-prepare-root[1876]: Found legacy sysroot.readonly flag, not configured in ostree/prepare-root.conf
[   74.623885] ostree-prepare-root[1876]: sysroot.readonly configuration value: 1 (fs writable: 1)
[   74.623989] ostree-prepare-root[1876]: composefs: Mounting with no digest or signature check
[   74.625318] ostree-prepare-root[1876]: composefs: optional support failed: No such file or directory
[   77.326671] systemd[1]: ostree-prepare-root.service: Deactivated successfully.
```
This is currently affecting:

- coreos.boot-mirror.luks
- coreos.boot-mirror
- test.tap
- luks.tang
- luks.sss.t2
- luks.sss.t1
- ext.config.shared.root-reprovision.swap-before-root
- ext.config.shared.root-reprovision.raid1
- ext.config.shared.root-reprovision.luks.autosave-xfs
- ext.config.shared.root-reprovision.luks
- ext.config.shared.root-reprovision.linear
- ext.config.shared.root-reprovision.filesystem-only
- ext.config.shared.root-reprovision.autosave-xfs
EDIT:
- ext.config.shared.podman.rootless-systemd [x86_64 only]
- ext.config.shared.networking.hostname.fallback-hostname [x86_64 only]

For completeness, here are a few journal and console logs from the ppc64le arch:
[console.boot-mirror.txt](https://github.com/openshift/os/files/12938120/console.boot-mirror.txt)
[journal.boot-mirror.txt](https://github.com/openshift/os/files/12938121/journal.boot-mirror.txt)
[console.root-reprovision.luks.txt](https://github.com/openshift/os/files/12938131/console.root-reprovision.luks.txt)
[journal.root-reprovision.luks.txt](https://github.com/openshift/os/files/12938132/journal.root-reprovision.luks.txt)
[console.luks.sss.t1.txt](https://github.com/openshift/os/files/12938134/console.luks.sss.t1.txt)
[journal.luks.sss.t1.txt](https://github.com/openshift/os/files/12938136/journal.luks.sss.t1.txt)

**Comment by jlebon** [comment]
This looks related to the composefs work. A bunch of related stuff went into git main since the last release, so it's possibly fixed. Though not sure why we're not hitting this in e.g. FCOS.

**Comment by cgwalters** [comment]
None of those are fatal - the service is exiting successfully.  The real fatal error looks like:

```
[   64.464519] ignition-ostree-transposefs[1844]: /usr/libexec/ignition-ostree-transposefs: line 29: RHEL_VERSION: unbound variable
[   64.468098] systemd[1]: ignition-ostree-transposefs-detect.service: Control process exited, code=exited, status=1/FAILURE
[   64.468150] systemd[1]: ignition-ostree-transposefs-detect.service: Failed with result 'exit-code'.
```

**Comment by marmijo** [comment]
This is also affecting some tests on the x86_64 architecture. Those are:
- ext.config.shared.podman.rootless-systemd
- ext.config.shared.networking.hostname.fallback-hostname
