### ISSUE TITLE
Move rhel-9.4 variant to RHEL content

### ISSUE THREAD

**Issue by marmijo** [openshift/os#1387]
During this transitionary period, the rhel-9.4 variant is still using CentOS content. 
I opened this to track any failure related to the fact that we aren't actually using RHEL content for this variant yet.

**Comment by marmijo** [comment]
two kola tests are failing:
- `ext.config.version.rhel-matches-rhcos-build` is failing because `/etc/os-release` still contains c9s data: `NAME='CentOS Stream'` [here](https://github.com/openshift/os/blob/6c202cbb0553aff4b0b867d108426b355d36ae59/manifest-rhel-9.4.yaml#L45) and `VERSION_ID=9` [here](https://github.com/openshift/os/blob/6c202cbb0553aff4b0b867d108426b355d36ae59/manifest-rhel-9.4.yaml#L49)
``` text
[[ 9 != \9\4 ]]
fatal 'Error: OS version and /etc/os-release version do not match'
```
 - `ext.config.shared.content-origins` is failing because there are packages with [CentOS as the vender:](https://github.com/coreos/fedora-coreos-config/blob/9444fe11442b7b997bd38fb1491b1a77db7e1965/tests/kola/content-origins/test.sh#L25-#L28)
```
fatal 'Expected only vendor Red Hat, Inc. for all packages'
```

**Comment by marmijo** [comment]
The rhel-9.4 variant is now using RHEL content and these tests are no longer failing when testing against that variant.

**Comment by travier** [comment]
We should review the test snooze from https://github.com/openshift/os/blob/master/kola-denylist.yaml

**Comment by marmijo** [comment]
Closing this issue as the rhel-9.4 variant has been using RHEL content for some time.
