### ISSUE TITLE
rhaos-pkgs-match-openshift test likely not working properly

### ISSUE THREAD

**Issue by travier** [openshift/os#1427]
See: https://github.com/openshift/os/blob/master/tests/kola/version/rhaos-pkgs-match-openshift

Our RHCOS images have non matching `rhaos` packages and the test don't fail.

See: https://issues.redhat.com/browse/COS-2613

**Comment by travier** [comment]
See https://github.com/openshift/os/pull/1448/commits/d328db94854a26085c30a257039b2a8b8097031d for an example of using grep in an if statement.

**Comment by jlebon** [comment]
Yeah, we should fix this. It will help us catch the case where we have newer versions in rhaos tag X than in the X+1 tag. (We'd still ship the one from X even on the X+1 stream, but it looks confusing.)

(I will note though that with #799, we'll basically eventually want all of the non-OpenShift packages we want in the base compose to be in RHEL proper.)

**Comment by travier** [comment]
Related to https://issues.redhat.com/browse/OCPNODE-1986

**Comment by c4rt0** [comment]
@travier - can we close this issue? #1456 with the fix was successfully merged.

**Comment by travier** [comment]
Let's close it once we have done all the backports.

**Comment by c4rt0** [comment]
> Let's close it once we have done all the backports.

| rhcos | Status |
| -- | -- |
| [4.16](https://github.com/openshift/os/pull/1456) | Merged |
| [4.15](https://github.com/openshift/os/pull/1500) | Merged | 
| [4.14](https://github.com/openshift/os/pull/1512) | Open |

**Comment by travier** [comment]
We'll skip backporting to 4.12. Thanks Adam!
