### ISSUE TITLE
build infrastructure related random idea dump

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#143]
1) Move to a jenkins instance in [api.ci](https://github.com/openshift/os/issues/143); see https://github.com/openshift/release/pull/1000
  1a) Use [GCE nested virt](https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances) for vmimage builds
2) Split out the pipeline to a separate repo
3) Move to pinning all of the base (non-rdgo) RPMs in the manifest; updates to them are driven a bot that submits PRs.  Think like what [Cockpit does to update their VMs](https://github.com/cockpit-project/cockpit/pull/9501).
4) Change rdgo to work the same way but with git commits
  4a) Related, [rewrite or replace/rework rpmdistro-gitoverlay](https://github.com/projectatomic/rpmdistro-gitoverlay/issues/49)
5) Containerize the imagefactory bits so we can consistently use containers and not classic systems

**Comment by ashcrow** [comment]
Looks like a lot of this is now done. Is this still relevant or should this be closed?
