### ISSUE TITLE
Use imagefactory for Vagrant boxes

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#146]
The problem now is https://github.com/cgwalters/qcow2-to-vagrant doesn't handle all of the formatting goop for e.g. VirtualBox too.  That may not be hard to add...but at this point it's *probably* saner to have the Vagrant box be a separate ImageFactory run like it is with FAH today.

That said...conceptually a nice approach for Vagrant would be to inject a default Ignition config that sets it all up rather than the systemd unit we do now - but only if we can extract the "make an OVA" bits from ImageFactory without duplicating too much code.

**Comment by cgwalters** [comment]
The most important thing is a VirtualBox-Vagrant box so people on Mac/Windows can use that.  (Though we should *also* have a livecd style system for the new kids using docker machine etc., but that's a separate issue)

**Comment by arithx** [comment]
In CL some oem's have a base Ignition config in `coreos-overlay`: https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-digitalocean/files/base/base.ign which could be one approach for solving it.

**Comment by ashcrow** [comment]
Do we still want to do this?

**Comment by cgwalters** [comment]
Probably not, people should be using the installer to make clusters, and the installer has a lot built on top of terraform which...overlaps a lot with Vagrant.
