### ISSUE TITLE
No ignition

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#152]
The patches all got merged, the problem seems to be for some reason we don't have `/boot/coreos-firstboot` in `/boot` in the images.  Debugging.

**Comment by ashcrow** [comment]
Thank you @cgwalters

**Comment by cgwalters** [comment]
It works fine now - no action required. Would have worked earlier if the cri-o thing hadn't broken the rdgo, which stalled treecomposes, and nothing else triggers cloud images today.  Tempting to have commits to openshift/os do that.
