### ISSUE TITLE
Failed to deploy a single node openshift container platform through coreos-installer on bare metal.

### ISSUE THREAD

**Issue by aiqubits** [openshift/os#1559]
openshift version: 4.16
bare metal cpu: intel xeon E5  44 Core
memory: DDR4 128G
disk: 1T m.2 SSD

first boot faile log:
[sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[sda] Attached SCSI removable disk
dev-disk-by\x2dlabel-boot.device: Job dev-disk-by\x2dlabel-rhcos\x2d416.94.202405291527\2d0.device: Job dev-disk-by\x2dlabel-rhcos\x2d416.94.202405291527\x2d0.device/start timed out

![1](https://github.com/user-attachments/assets/cb1d0166-62a9-4bd1-991a-325aaa3f1104)
![2](https://github.com/user-attachments/assets/4b5c31b6-85e1-41bf-a16f-e1b4cf43bf9c)
![3](https://github.com/user-attachments/assets/996934a2-58d5-4302-ada6-17a50a3092b6)
![4](https://github.com/user-attachments/assets/8db2b18a-af6d-4e8a-aef5-7f9a104788ad)

This is deploy docs:
https://docs.redhat.com/zh_hans/documentation/openshift_container_platform/4.16/html-single/installing/index#install-sno-installing-sno-manually

**Comment by travier** [comment]
See https://github.com/openshift/os#reporting-issues
