### ISSUE TITLE
Add irqbalance to aarch64 builds of RHCOS

### ISSUE THREAD

**Issue by bartwensley** [openshift/os#1601]
The irqbalance package is required for low latency applications. It is present in the x86_64 RHCOS build, but not the aarch64 build. It looks like irqbalance is already included in the aarch64 build of Fedora CoreOS:
https://github.com/coreos/fedora-coreos-config/blob/bece365c3d8cf02448ed85093fbbe32322c0c090/manifests/fedora-coreos-base.yaml#L202

It looks like it is added to the x86_64 RHCOS build here:
https://github.com/openshift/os/blob/3d900b87995349e5fb15c8bd2949b10ff51e62c7/common.yaml#L275

But there is no equivalent section for packages-aarch64 to add irqbalance.

**Comment by jlebon** [comment]
We also ship it on ppc64le. I don't see why not add it on aarch64 as well for consistency.

> But there is no equivalent section for packages-aarch64 to add irqbalance.

You can add that section following the same format as the other ones. Want to submit a PR?

**Comment by jlebon** [comment]
We don't have aarch64 in CI but this should be quite safe. It'll be tested not long after in the internal pipeline and we can always revert/adjust if needed.
