### ISSUE TITLE
Failing tests on "fake" rhel 9.6 

### ISSUE THREAD

**Issue by jbtrystram** [openshift/os#1635]
To allow testing on the next rhel release I created a fake rhel-9.6 variant, which is pure c9s plus some openshift packages from the 9.4 repos. 

This is a tracking issue for the failing tests in that build. 

[x] `ext.config.version.rhel-major-version` 
         fails as `libgcc` is version 9 instead of 418. Denylisted.
         
[x] `ext.config.shared.content-origins` : 
      `Expected only vendor Red Hat, Inc. for all packages` : will fail as it centOS content. denylisted

[x] `ext.config.shared.swap.zram-default` : 
    zram is enabled and should be disabled : [`9909e2f` (#1629)](https://github.com/openshift/os/pull/1629/commits/9909e2f4da3aebacf1e5e98b717724ed884f131f)

[x] `ext.config.shared.networking.team-dhcp-via-ignition` : 
	missing teamd package, included with [`85cf877` (#1629)](https://github.com/openshift/os/pull/1629/commits/85cf877cf2022b576277935cbfa5b1c86364fcef)

See https://github.com/openshift/os/pull/1629

**Comment by jbtrystram** [comment]
Keeping this issue open until we move to real rhel 9.6 content and remove the entry from denylist

**Comment by gursewak1997** [comment]
@jbtrystram Can we close this issue now?

**Comment by marmijo** [comment]
The rhel-9.6 variant based on real rhel-9.6 content exists now and the denylist entries were removed in https://github.com/openshift/os/commit/7f0a678eef5974d42653275aaf9a03cea10c5f38.

**Comment by jlebon** [comment]
Yeah, let's close this.
