### ISSUE TITLE
Investigate systemd-container-coredump SELinux module not getting installed properly during 4.15 base compose

### ISSUE THREAD

**Issue by jlebon** [openshift/os#1652]
E.g. the systemd RPM in 9.2 has:

```
%post
...
# Install our own selinux-policy module that allows systemd-coredump access to containers
%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{selinuxtype}/%{modulename}.pp.bz2
```

But for some reason, when investigating the resulting policy, the module doesn't seem there. (E.g. it should show up in `/etc/selinux/targeted/active/modules/200`, but doesn't.)

For now, we've added a workaround in the selinux-policy-targeted package directly, but we should debug why this didn't work.

**Comment by jlebon** [comment]
I would probably start by seeing if we can reproduce this against the latest development branch.

**Comment by HuijingHei** [comment]
> I would probably start by seeing if we can reproduce this against the latest development branch.

Yes, can reproduce on 4.15, can not find `/etc/selinux/targeted/active/modules/200/systemd-container-coredump`, will look at more about it.
```
export COREOS_ASSEMBLER_CONTAINER=quay.io/coreos-assembler/coreos-assembler:rhcos-4.15
cosa shell
cosa init --yumrepos https://xxx/redhat-coreos.git --variant rhel-9.2 --branch release-4.15 https://github.com/openshift/os.git
cosa build
cosa run -m 4096
# ls /etc/selinux/targeted/active/modules/200
container  passt  pasta
```

**Comment by HuijingHei** [comment]
Seems it is because of `systemd 252-14.el9_2.7 -> 252-14.el9_2.8`, if rebuild with override rpms 252-14.el9_2.7, can find `/etc/selinux/targeted/active/modules/200/systemd-container-coredump`
```
[core@cosa-devsh ~]$ cat /etc/os-release 
VERSION="415.92.202411261331-0"
[core@cosa-devsh ~]$ sudo ls /etc/selinux/targeted/active/modules/200
container  passt  pasta  systemd-container-coredump
[core@cosa-devsh ~]$ rpm -q systemd
systemd-252-14.el9_2.7.x86_64
```

**Comment by jlebon** [comment]
> Seems it is because of `systemd 252-14.el9_2.7 -> 252-14.el9_2.8`, if rebuild with override rpms 252-14.el9_2.7, can find `/etc/selinux/targeted/active/modules/200/systemd-container-coredump`

Yeah, we had gotten to that point of the investigation too, but now I realize that I didn't read the systemd's dist-git git log carefully enough. I only checked the first commit that bumps the release to `.8` but there are two more commits which actually _do not_ bump the release and so would still show up as `.8`. And the actual `.8` Brew build included those commits as well.

Anyway, it looks like the culprit is very likely:

```diff
commit 212282d38c9c9c0e906c01d210f5cb488f707f40
Author: Stepan Broz <sbroz@redhat.com>
Date:   Fri May 31 17:07:03 2024 +0200

    spec: remove dependency on policycoreutils-python-utils
    
    Resolves: RHEL-36469

diff --git a/systemd.spec b/systemd.spec
index d2e8cd05..0135fc5a 100644
--- a/systemd.spec
+++ b/systemd.spec
@@ -439,7 +439,6 @@ Requires(post): grep
 # selinux
 Requires(post): libselinux-utils
 Requires(post): policycoreutils
-Requires(post): policycoreutils-python-utils
 
 # systemd-machine-id-setup requires libssl
 Requires(post): openssl-libs
@@ -1233,6 +1232,7 @@ systemd-hwdb update &>/dev/null || :
 - bootspec: fix null-dereference-read (RHEL-25529)
 - doc: add missing `<listitem>` to `systemd.net-naming-scheme.xml` (RHEL-25529)
 - spec: add new package with RHEL-specific network naming sysattrs (RHEL-25529)
+- spec: remove dependency on policycoreutils-python-utils (RHEL-36469)
 
 * Fri Apr 26 2024 systemd maintenance team <systemd-maint@redhat.com> - 252-14.7
 - coredump: generate stacktraces also for processes running in containers w/o coredump forwarding (RHEL-34059)
```

But I'm not quite sure why. `semodule` is part of `policycoreutils`, not `policycoreutils-python-utils`, so it should still work given that the former is still a `Requires(post)`.

**Comment by jlebon** [comment]
Ahhh, I bet it needs a `Requires(post): selinux-policy-any` so that the targeted policy is actually set up before we try to add a module to it. Otherwise, e.g. `/etc/selinux/config` won't have the right `SELINUXTYPE` yet and the `%selinux_modules_install` macro which keys off of that will not do the right thing. Compare with e.g. container-selinux which also uses `selinux_modules_install`:

https://gitlab.com/redhat/centos-stream/rpms/container-selinux/-/blob/af1542db7b48944daabd413d8467b463d5585f05/container-selinux.spec#L34-36

I'm not sure on the dependency tree here, but if this is correct, then somehow what's happening is that dropping `Requires(post): policycoreutils-python-utils` is causing the ordering in which the post scripts are run such that `systemd`'s post script runs before `selinux-policy-targeted`'s post script.

Proposal:
- try to reproduce the issue in c9s and/or c10s (e.g. do a compose of the `c9s` variant and check `/etc/selinux/targeted/active/modules/200`)
- see if adding the same `Requires(post)` as container-selinux in the systemd spec fixes it
- if it does, open an MR in CentOS Stream against systemd with that change
- cross-link the MR from RHEL-36469

**Comment by HuijingHei** [comment]
Thanks @jlebon very much for the pointer.

> * try to reproduce the issue in c9s and/or c10s (e.g. do a compose of the `c9s` variant and check `/etc/selinux/targeted/active/modules/200`)

Build coreos using c9s and can not find `systemd-container-coredump` under `/etc/selinux/targeted/active/modules/200`, and not `/usr/share/selinux/packages/targeted/systemd-container-coredump.pp.bz2`
```
[root@cosa-devsh core]# rpm -q systemd
systemd-252-48.el9.x86_64
[root@cosa-devsh core]# semodule -l | grep systemd-container-coredump
[root@cosa-devsh core]# sudo ls /etc/selinux/targeted/active/modules/200
container  passt  pasta
[root@cosa-devsh core]# rpm -qv --requires systemd | grep post
post,interp: /bin/sh
postun,interp: /bin/sh
post: acl
post: coreutils
post: grep
post: openssl-libs
post: sed
```
Seems since `systemd-252-47`, which `removes SELinux policy module`, see [RHEL-58179](https://issues.redhat.com/browse/RHEL-58179) and related [PR](https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/158)

**Comment by HuijingHei** [comment]
> * see if adding the same `Requires(post)` as container-selinux in the systemd spec fixes it

Good catch and it works. Rebuild systemd and check there is `systemd-container-coredump` under `/etc/selinux/targeted/active/modules/200`
```
[core@cosa-devsh ~]$ sudo ls /etc/selinux/targeted/active/modules/200
container  passt  pasta  systemd-container-coredump
[core@cosa-devsh ~]$ rpm -qv --requires systemd | grep post
post,interp: /bin/sh
postun,interp: /bin/sh
post: acl
post: coreutils
post: grep
post: libselinux-utils
post: openssl-libs
post: policycoreutils
post: sed
post: selinux-policy-base
post: selinux-policy-targeted
```

**Comment by jlebon** [comment]
> Seems since `systemd-252-47`, which `removes SELinux policy module`, see [RHEL-58179](https://issues.redhat.com/browse/RHEL-58179) and related [PR](https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/158), have not seen the workaround yet (asked in the bug).

OK interesting turn of events. Thanks for testing!

I think then let's not do any patches/backports at all. The workaround in selinux-policy for el9.2 will work for now, and then for later I guess it won't be relevant since the module is entirely gone in systemd so the necessary rules will live purely in selinux-policy at that point. I think let's just close this then.

**Comment by HuijingHei** [comment]
Thanks @jlebon very much for the pointer and guidance, since we do not need `systemd-container-coredump` anymore for both 9.2 and 9.4, agree to close this.

**Comment by dustymabe** [comment]
so the TLDR is that it wasn't some issue with how OSTree/RPM-OSTree handles selinux but rather a packaging issue with systemd RPM, but has since been removed from the systemd RPM anyway so nothing really to do.
