### ISSUE TITLE
oscontainer image retention policy

### ISSUE THREAD

**Issue by miabbott** [openshift/os#178]
Using the tag strategy in openshift/os#77, are there any opinions on how many versions of `buildmaster` (no testing completed on that tag) we should retain?

@cgwalters suggested 3-4 in an internal Jira issue, which seems like a good amount.  Any other opinions on the matter?

**Comment by ashcrow** [comment]
I think 4 is a good target to start with.

**Comment by cgwalters** [comment]
https://docs.openshift.com/container-platform/3.9/admin_guide/pruning_resources.html#pruning-images is useful on this topic.

**Comment by ashcrow** [comment]
> --keep-tag-revisions=<N> | For each image stream, keep up to at most N image revisions per tag. (default 3)

I'd be fine with using the default of 3.

**Comment by miabbott** [comment]
Related to investigations in #201, I found using `oc adm prune images` appears to operate on the entire cluster, so it is unlikely we'll have that kind of privilege for our purposes.

I think we'll have to use something like `skopeo delete` to manage images on the registry (using the current pipeline).
