### ISSUE TITLE
openshift fails to read config file

### ISSUE THREAD

**Issue by sdemos** [openshift/os#229]
So I was setting up my local dev, following the docs for [openshift on libvirt](https://github.com/openshift/installer/blob/master/Documentation/dev/libvirt-howto.md). I downloaded the latest rhcos image and went through the install, but bootkube failed because it couldn't read a config file. I know this seems like an installer issue, but I think it's an rhcos issue, and you will see why in a second. 

Essentially, it was mounting some volumes onto a container to render some assets (see https://github.com/openshift/installer/blob/master/modules/bootkube/resources/bootkube.sh#L7-L12 and https://github.com/openshift/installer/blob/master/modules/bootkube/resources/bootkube.service#L11) and the renderer needed `/opt/tectonic/kco-config.yaml` (mounted into the container at `/assets/kco-config.yaml`). However only the directory structure of `/opt/tectonic` was making it into the container (I used an alpine container to figure that out). In the course of debugging, I tried adding the `:z` suffix to the volume mount with the alpine container, and the problem went away. When I tried to repro the original issue after that, it was gone, even without the `:z` suffix. 

Reading up on the `:z` volume mount suffix, it seems like it can have consequences on the host machine (https://stackoverflow.com/a/35222815), particularly, it seems to manipulate selinux labels in some way. My guess is that something changed in the base image kind of recently having to do with the labels on `/opt/tectonic` (or `/var/opt/tectonic` which afaict is hardlinked one way or the other), and now the docker command fails to mount the files in properly, and the `:z` suffix inadvertently fixes the issue.

I'm not sure what could've changed to cause this, but I figured I would throw it out there and see if anyone had some insight. It was definitely a thorn at any rate.

**Comment by jlebon** [comment]
Yeah, this is because we recently stopped disabling SELinux. Mounts will need to be adjusted in the installer to relabel files. See report in https://github.com/openshift/installer/issues/132. WIP in https://github.com/openshift/installer/pull/134.

**Comment by dustymabe** [comment]
we recently enabled selinux: https://github.com/openshift/os/pull/224 

in order to share files with containers they need to have proper labels that's what the :z does

**Comment by dustymabe** [comment]
wow @jlebon.. way to beat me by a few seconds

**Comment by sdemos** [comment]
hmm I definitely should've checked the installer repo bugs first. thanks everyone!

either way, is this an issue with the os where we need to fix the selinux labels on these files, or is the workaround @jlebon linked to enough for us to just ignore this going forward?

**Comment by ashcrow** [comment]
> either way, is this an issue with the os where we need to fix the selinux labels on these files, or is the workaround @jlebon linked to enough for us to just ignore this going forward?

The mounting should have the `:z` added to it to fix the issue. https://github.com/openshift/installer/pull/134 should end up fixing the issue once it merges.

**Comment by jlebon** [comment]
Seems like we can close this one and just follow along in openshift/installer?

**Comment by ashcrow** [comment]
> Seems like we can close this one and just follow along in openshift/installer?
:+1: as long as @sdemos is OK with that as well.

**Comment by sdemos** [comment]
yeah, we can close it.

to clarify, yes, `:z` does fix it, but my question was is it worth us fixing the initial selinux labels in the first place, or should we just let `:z` fix the labels and call it good. we can probably just call it good and move on though.
