### ISSUE TITLE
create a single "source of truth" JSON artifact that holds build metadata

### ISSUE THREAD

**Issue by miabbott** [openshift/os#258]
Currently we are generating a `commit.txt` that has the `ostree` commit ID for a build, but we don't have `version.txt` that has the version number.

Additionally, we have a `pkglist.txt` that has a list of packages and a `pkg-diff.txt` that has the package diff between the previous `ostree` commit and the current one.

Finally, there is a JSON file that has the AMI data (ID, S3 object, Snapshot ID).

It looks to me that we could combine some (or all?) of this data into a single JSON that we could then publish to the public as part of the pipeline.

**Comment by miabbott** [comment]
This is one of the items that was discussed as part of https://github.com/openshift/os/issues/150#issuecomment-417094115

**Comment by cgwalters** [comment]
PR in https://github.com/openshift/os/pull/260

**Comment by cgwalters** [comment]
> Finally, there is a JSON file that has the AMI data (ID, S3 object, Snapshot ID).

Mmm...I'm not merging that (yet), but arguably the meta.json should have a reference to it or so?
