### ISSUE TITLE
provide a way to allow the pipelines to save artifacts outside of the "production" location

### ISSUE THREAD

**Issue by miabbott** [openshift/os#262]
If a user wanted to test changes to any of the pipelines, they run the risk of overwriting the content in the "production" location when using their test pipeline.  Since we have a concept of a "development" pipeline (openshift/os#241, etc), we should be able to use this designation to change where the artifacts are written to.

One proposal could be to create something like `/srv/rhcos/scratch` which could then contain multiple directories based on username or job name.

A concern for any solution that we choose would be how to periodically clean up those directories, so we don't clobber all the disk space.

**Comment by miabbott** [comment]
Another item from the discussion in https://github.com/openshift/os/issues/150#issuecomment-417094115

**Comment by cgwalters** [comment]
This was fixed.
