### ISSUE TITLE
host: do not install ignition binaries to rootfs default PATH

### ISSUE THREAD

**Issue by lucab** [openshift/os#266]
These are technically three different but related bugs:
 1. `ignition` and `ignition-validate` are available in PATH (i.e. `/bin`) in the rootfs. They shouldn't be running in such environment, thus they shouldn't be exposed to the user there.
 1. `ignition-validate` is available in RHCOS. This is supposed to be a devops tool and not running on the deployed node.
 1. Ignition binaries are available in RHCOS rootfs. We only run `ignition` in initramfs, so we technically don't need any other bits in the rootfs.

Now, I'm not familiar enough with rpm-ostree and its initramfs/dracut setup to asses how the ignition rpm should look like, but if possible I'd like to avoid shipping any Ignition bits at all in the rootfs. At this time, this would help us save ~16MiB on the rootfs.

**Comment by cgwalters** [comment]
Today AFAIK dracut doesn't directly support having src != target.  For example, today we aren't running `strip` on the initramfs since we don't include binutils.

But obviously, it could learn to do that - we could certainly include binutils (and Ignition) in a "dracut root".  Something like `dracut-packages` in the manifest, and install just those packages there in addition to the base rootfs?  Probably would be pretty easy change to rpm-ostree.

**Comment by lucab** [comment]
@cgwalters thanks for the additional details. If I'm reading this correctly, I think we could split this in two tasks:
 1. short term: split `ignition-validate` to its own binary rpm, move `ignition` binary out of path (libexec?) and tell dracut module to pick it up from there
 1. long term: investigate if we can isolate rootfs packages and dracut/initramfs at compose time, in order not to mix them

/cc @dustymabe for the former

> today we aren't running strip on the initramfs since we don't include binutils

I got the overall idea, but at first I was confused by this example. In maipo rootfs we both ship binutils and strip binaries at build-time, isn't it? Or do you mean something different with "running strip on the initramfs"?

**Comment by dustymabe** [comment]
> short term: split ignition-validate to its own binary rpm, move ignition binary out of path (libexec?) and tell dracut module to pick it up from there

seems ok

**Comment by bgilbert** [comment]
https://src.fedoraproject.org/rpms/ignition/pull-request/26

**Comment by bgilbert** [comment]
The short-term fix is in `0.31.0-5.gitf59a653`.

**Comment by dustymabe** [comment]
should we close this out and open a new issue when it's feasible for us to revisit the longer term fix ?

**Comment by bgilbert** [comment]
SGTM.  Closing.
