### ISSUE TITLE
'ceph-common' + 'glusterfs' included in RHCOS is ancient

### ISSUE THREAD

**Issue by miabbott** [openshift/os#271]
Inspired by #269, I started looking at the output from the `treecompose` job and saw that we were pulling in `stub-redhat-lsb-core-only-for-ceph-2015.1-1.atomic.el7.noarch`which is used by `ceph-common`.

Turns out the version of `ceph-common` we are pulling in is nearly 2 years old.

We'll need to enable the `ceph-tools-2` repo to get a more current version (currently in RHELAH - `ceph-common-10.2.10-28.el7cp.x86_64`)

**Comment by miabbott** [comment]
Of course `glusterfs` is also old...

**Comment by ashcrow** [comment]
Assigned to @miabbott as he already has a PR in flight.
