### ISSUE TITLE
Refactor pipeline to fetch + build?

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#281]
As I'm thinking about the tagging issue...what if we had just two `Jenkinsfile`s:

 - Jenkinsfile.fetch
 - Jenkinsfile.build

And rdgo, treecompose, cloud were folded underneath `build`.  Having them asynchronous is somewhat helpful for development, but I am starting to conclude it's not quite worth it.  Building a qcow2 just takes 3 minutes.

(The slowest part is AWS upload at 15-20 mins...we may want to consider splitting that off)

The advantage of this (for tagging) is that we can more easily "bind" together our various artifacts.  An oscontainer is only pushed if a VM image is built - we can use the same version numbering.

Another *major* advantage of this is that we can drop some of the hacks in `Jenkinsfile.cloud` to try to sync up the ostree version; if they're unified we actually have the oscontainer version handy there.

**Comment by cgwalters** [comment]
To keep this ultra-simple to start we could just have `Jenkinsfile` to start (i.e. fold fetch/build).  But the advantage of splitting those two is one doesn't need to wade through lots of "no changes" jobs.

**Comment by yuqi-zhang** [comment]
So effectively build would be rdgo->treecompose->cloud, with some parallel? And have the aws upload/test split out in the current aws-test job?

I agree that its an easier way to handle the artifact syncing. Only minor concern is that errors in say, `cloud` would fail the whole `build` job, which causes minor de-syncs and makes it slightly harder to pinpoint exact issues. But I guess we have that issue with our async builds anyways, so that's probably fine.

**Comment by cgwalters** [comment]
> with some parallel

I don't think we can parallelize anything that isn't parallelized today.  The more I think about this the more I feel historically I was wrong (and I argued this a lot) that treecompose should be async from image builds.  But...building the images just isn't that slow if done right.

**Comment by yuqi-zhang** [comment]
I'm down to give it a try. We also did mention at some point to add the ability to create scratch directories for pipeline testing. It might be nice to add that in as well while we're overhauling the builds.

Tagging @miabbott for his thoughts.

**Comment by cgwalters** [comment]
Offhand...my proposal is that you take a look at doing a smaller-scale change like going back and tagging the oscontainer after VM tests have passed, and while you're reading the code and planning changes for that - think about whether it'd be easier to do this.

If so, be sure to announce it as anyone else doing pipeline changes will conflict.

**Comment by cgwalters** [comment]
(And if you decide to jump on this I'd be happy to try to split up the work or collaborate on bjns, etc.)

**Comment by miabbott** [comment]
I like the idea of binding the whole artifact generation process together (rdgo->treecompose->image); it should be easier to trace the build process that way.  And we get the benefit of being able to more easily tag all the artifacts at the same time.  Maybe we can even divorce the push of the artifacts from the test/tagging into a separate job, too.

@yuqi-zhang I'd say go with @cgwalters proposal about implementing tagging and we can continue to think about how to break apart the jobs into the right pieces.

I believe @arithx had mentioned the multiple jobs `jenkins-os` used on the CL side.  Perhaps he has ideas around this, too.

**Comment by arithx** [comment]
`jenkins-os` does multiple stages for each platform. Once the image has been built for the various versions it splits off into the [prerelease jobs](https://github.com/coreos/jenkins-os/tree/master/os/prerelease) if they exist for the platform, which will handle uploading the images; next the individual [kola jobs](https://github.com/coreos/jenkins-os/tree/master/os/kola) are ran.

You can [view the code for splitting off here](https://github.com/coreos/jenkins-os/blob/master/os/board/vm-matrix.groovy#L102-L179).

**Comment by jlebon** [comment]
Is part of this about pivoting from `coreos-assembler:alpha` to `coreos-assembler:latest`? I.e. `Jenkinsfile.fetch` does `coreos-assembler fetch` and `Jenkinsfile.build` does `coreos-assembler build`?

**Comment by cgwalters** [comment]
This one still isn't fixed with v2, but it's lower priority now.
