### ISSUE TITLE
bump runc to at least runc-1.0.0-51

### ISSUE THREAD

**Issue by sjenning** [openshift/os#284]
fixes https://github.com/containers/libpod/issues/1396

blocking switch from docker to podman for bootkube

@crawford

**Comment by crawford** [comment]
Actually, it doesn't block the [move to podman](https://github.com/openshift/installer/pull/207), but it would still be good to have.

**Comment by dustymabe** [comment]
does podman vendor runc? should we be bumping podman instead ?

**Comment by ashcrow** [comment]
`runc` is a dep of `podman`

```
$ rpm -q --requires podman | grep runc
runc
```

**Comment by ashcrow** [comment]
This work is already being done by @yuqi-zhang in `COREOS-477` as using the new repo will pull in the updated `runc`.

**Comment by sjenning** [comment]
@crawford true as long as we removed `--tmpfs`

https://github.com/openshift/installer/pull/207/files#r216868889

slightly less secure than before but... in the grand scheme, not sure if it makes a difference.

**Comment by ashcrow** [comment]
No. The extras repo in #286 still is under the requested version. The work @yuqi-zhang is doing should fix this issue.

**Comment by yuqi-zhang** [comment]
Added in: https://github.com/openshift/os/pull/288

```
podman-0.8.5-3.gitdc5a711.el7.x86_64
cri-o-1.11.3-2.rhaos3.11.git4fbb022.el7_5.x86_64
cri-tools-1.0.0-6.rhaos3.11.git78ec590.el7.x86_64
runc-1.0.0-52.dev.git70ca035.el7_5.x86_64
containernetworking-plugins-0.7.1-1.el7.x86_64
```

**Comment by wking** [comment]
```console
$ curl -s http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/images/cloud/latest/pkglist.txt | grep runc
 runc-1.0.0-52.dev.git70ca035.el7_5.x86_64
```

/close
