### ISSUE TITLE
Create tooling to override an oscontainer with updated RPMs

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#289]
We want to take a PR to e.g. Origin, get an updated kubelet binary, and make it fast and easy to build a new oscontainer from an existing one using those updated binaries.

Our current oscontainer builds [require privileges](https://github.com/projectatomic/rpm-ostree/issues/1329), but we could pretty easily make something that just overlaid binaries on top of an existing ostree commit.

**Comment by cgwalters** [comment]
The other approach really is for CI testing to just do `rpm-ostree usroverlay && rpm -Uvh /path/to/updated/kubelet.rpm` (or, for persistence, use `rpm-ostree override replace http://api.ci/kubelet.rpm && reboot`).

**Comment by cgwalters** [comment]
An extension of this previous idea is that the MCD gains support for e.g.:

```
  rpmOverrides:
    - https://rpms.svc.ci.openshift.org/blah/origin-hyperkube-blah.x86_64.rpm
```

This would be pretty straightforward.

**Comment by ashcrow** [comment]
Is this part of COREOS-780 (or it's epic)?

**Comment by cgwalters** [comment]
> Is this part of COREOS-780 (or it's epic)?

Yes and no.   There is a lot of crossover between updates and CI issues.  This issue though is mostly about the CI side.

I think this is the first thing we should do here:

>  but we could pretty easily make something that just overlaid binaries on top of an existing ostree commit.

**Comment by smarterclayton** [comment]
Ci testing finds it really hard to do these things at the right point later in the cycle (we have to intercept host startup in MCD).  if we can tweak the image, what we text ~= what we would ship.

**Comment by smarterclayton** [comment]
I need a short term recommendation on what we're going to do here.

**Comment by cgwalters** [comment]
Options:

1. MCO rpm overrides: https://github.com/openshift/os/issues/289#issuecomment-446642603
1. Ignition overrides: Create a model to do overrides in Ignition; basically like `rpm-ostree usroverlay && rpm -Uvh https://rpms.ci.svc/.../kubelet.rpm` (runs before cluster is up)
1. RHCOS-pr-service: Create a service that spits out custom RHCOS builds

Of these I think the Ignition one is by far the simplest.  However of course...those changes would be lost on an upgrade.  Probably in CI, when we want to do any overlays, disable upgrades (and any tests that cover that).  Or if we *do* want that, use `rpm-ostree override replace https://...kubelet.rpm` and reboot.

**Comment by cgwalters** [comment]
(The Ignition one would really be a systemd unit that runs `Before: kubelet.service` etc.)

**Comment by smarterclayton** [comment]
how will 2 work though when we pull the image version from the update?  We're going to boot, use version from the AMI, then replace with the new version post ignition?  So RPMs get blown away?

Actually, we're going to add upgrade testing very soon.  I don't think any option but 4 will work with upgrades.

**Comment by smarterclayton** [comment]
So upgrade testing is going to grab an old version, then update to a new payload.  That's it.  If we can't build synthetic images and put them in the payload, we can't test that.  That's ~1-2 weeks out.

**Comment by cgwalters** [comment]
> how will 2 work though when we pull the image version from the update? We're going to boot, use version from the AMI, then replace with the new version post ignition? So RPMs get blown away?

Are we scoping in anything other than kubelet here?  With both 2/3, the changes happen before the real cluster comes online (and theoretically we could have this work for bootstrap too).  2/3 have the flow basically like:

 - origin e2e-aws PR generates kubelet
 - updated kubelet passed to installer as Ignition (custom Ignition, which we need to support)
 - bootstrap node launches (old kubelet), starts booting masters and passes "overlay kubelet Ignition" to masters
 - Workers start and get same overlay from real MCO

**Comment by cgwalters** [comment]
> but we could pretty easily make something that just overlaid binaries on top of an existing ostree commit.

More on this.  I think we can do this as a multi-stage build; the builder image `yum -y install ostree`, then just do e.g.:

```
base_commit=$(find_commit_in /srv/ostree/repo)
tmpd=$(mktemp -d)
cd $tmpd
for rpm in https://ci.svc/{kubelet,hyperkube}.rpm; do
  curl -L $rpm | rpm2cpio | cpio -div
done
commit=$(ostree --repo=/srv/ostree/repo commit --tree=ref=${base_commit} --tree=dir=$(pwd)
```

A stumbling block here may be the [oscontainer tooling injects a special label](https://github.com/coreos/coreos-assembler/blob/e1813a3f5588c650ae9ee1ce2fde5fdf4f24bb64/src/cmd-oscontainer#L94) which...we'd have to figure out how to update.  But maybe it's cleaner to have that be a file in the container and not a label?  The pivot code may need changing for this.

**Comment by cgwalters** [comment]
Clayton and I had a realtime chat about this.  One thing that seemed clear is that option 4 isn't the *full* RHCOS builds; we don't need e.g. AMIs/qcow2.  Just oscontainers.  Which simplifies a lot (e.g. in PR testing we don't need to worry about GC'ing AMIs)

**Comment by smarterclayton** [comment]
Notes from chat:

* We need to be able to boot an older RHCoS AMI, then upgrade to a new payload for upgrades no matter what
* Priorities for 4.0 ordering: use the machine content from MCD, be able to get minimal RPM list (kubelet, oc, crio) in PR overlays
* Being able to do the image fits best with all our other assumptions

So two options:

1. Machine os container image as a service, behind firewall: write controller inside firewall that watches api.ci for a CR that is a "build request" that has tuple (ostree config, rpm repos for overrides, push location) that then talks to rhcos jenkins to trigger a build, then ensures the built image is pushed back to api.ci at arranged location.  Risks: timing, moving pieces

2. Simplest possible hack that allows a Dockerfile running on 3.11 api.ci on GCP to unprivileged inherit from latest machine-os-content image but override files/rpms, docker file lives in origin repo and looks like: 

```
FROM oscontent
RUN rpm-ostree some-command https://rpms-ci-op-x2454.svc.ci.openshift.org/rpms_for_kubelet
```

and then pushes back in (we'd mark the image optional)

**Comment by cgwalters** [comment]
PRs Clayton did for this:

 - https://github.com/openshift/release/pull/2747
 - https://github.com/openshift/origin/pull/21919

**Comment by smarterclayton** [comment]
had to disable in https://github.com/openshift/release/pull/2897, once the pivot started happening we started failing due to what looks like a selinux issue in node related to starting the container.  Networking couldn't init the network namespace for the pause container or similar.

**Comment by cgwalters** [comment]
This was done in https://github.com/coreos/coreos-assembler/blob/master/src/cmd-dev-overlay
