### ISSUE TITLE
Upload to us-east-2 at least

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#328]
We know we need to do more regions.

Sanest thing is probably to have our aws-test job do this.

**Comment by ashcrow** [comment]
Adding @wking for input.

**Comment by coverprice** [comment]
FWIW this isn't urgent for me anymore, I'm in the process of getting `us-east-1` quotas bumped so I'm not blocked by this.

**Comment by wking** [comment]
> Adding @wking for input.

I don't have opinions on this ;).  We don't get many "why don't I have AMIs in `$REGION`?" questions, so I'm fine continuing to point those people at you folks (and now at this issue :).

**Comment by nstielau** [comment]
Hey, talked with @coverprice and we'd like to get this sorted. Adding US-East-2 sounds like a good first step.

 Out newfound exuberance to actually spin up and kick the tires on a cluster is putting some pressure on our AWS sretup, hitting limits, so adding another region will help.
