### ISSUE TITLE
Corrupted initramfs object after running installer

### ISSUE THREAD

**Issue by jlebon** [openshift/os#349]
Trying to test pivoting from the MCD on `4.0.6457` and getting an error from `finalize-staged`. Doing it manually reveals:

```
[root@worker-gnx4p ~]# ostree admin finalize-staged
**
OSTree:ERROR:src/libostree/ostree-sysroot-deploy.c:1628:install_deployment_kernel: assertion failed (kernel_layout->bootcsum == bootcsum): ("291de1b475ec3c7b2e402630c8df4e79f80297e80dfafca932640545408e7914" == "727105d6b3da625e208c07a5920d5d7cd9cf59ed9be1b52e67c0a5197a1f2219")
Aborted (core dumped)
```

Doing some more digging yields:

```
[root@worker-gnx4p tmp]# ostree fsck
Validating refs...
Validating refs in collections...
Enumerating objects...
Verifying content integrity of 2 commit objects...
fsck objects (10818/15939) [========     ]  67%
error: In commits d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60: fsck content object 8c098b10c9b166870adca0d7767b8b86c3161c3d3f98645cda471943302e6e1f: Corrupted file object; checksum expected='8c098b10c9b166870adca0d7767b8b86c3161c3d3f98645cda471943302e6e1f' actual='3484199647bf6b4facbc7693e936f0211f7e134a7a7112a5cbb0c0516251a67f'
```

That `d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60` commit is from the base commit shipped in the image.

```
# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://rhcos:openshift/3.10/x86_64/os
                   Version: 4.0.6457 (2018-10-02 15:02:11)
                    Commit: d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60
```

Running [find-object-filenames](https://github.com/ostreedev/ostree-releng-scripts/blob/master/find-object-filenames) confirms the initramfs is borked:

```
# python find-object-filenames --repo /ostree/repo --rev d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60 --object 8c098b10c9b166870adca0d7767b8b86c3161c3d3f98645cda471943302e6e1f
d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60 => d7699c65f2aaa7d13d79edca231a23c9d5946c83d8e5d4b444a20b8527602a60 : /usr/lib/modules/3.10.0-862.el7.x86_64/initramfs.img
```

**Comment by cgwalters** [comment]
Fun!  Hmm.  So this is all underneath the read-only `/usr` mount, I doubt anything is subverting that.

My initial thought was that something was going in and changing the version in `/boot` but...sadly `ostree fsck` doesn't cover that since it's a copy.  (We need `ostree admin fsck`)

**Comment by ashcrow** [comment]
Closing due the issue not being reproducible + ~30 days of inactivity.

**Comment by jlebon** [comment]
I'm worried there's something super nasty hiding there in how rpm-ostree handles the initrd that we just walked by. Though without a solid reproducer, I agree we can just put it to rest for now.
