### ISSUE TITLE
create authoritative document within the repo that describes tagging scheme for artifacts

### ISSUE THREAD

**Issue by miabbott** [openshift/os#351]
@wking notes in https://github.com/openshift/os/issues/201#issuecomment-427143596 that he'd like to have something more than an issue comment to reference as the authority on how we tag our artifacts.

Something like `TAGS.md` would suffice that describes our tags and when they are used.

**Comment by ashcrow** [comment]
Is this for tagging container images or release tags in git?

**Comment by miabbott** [comment]
Tagging container images and other artifacts.  I'll update title accordingly.
