### ISSUE TITLE
more generic fix for dracut networking issue

### ISSUE THREAD

**Issue by dustymabe** [openshift/os#358]
Original issue: #298 

We need to find a more generic solution to #298 that does not involve hardcoding eth0 as was done in #300. Options include opening a bug against dracut in rhel7 and getting it fixed or patching dracut in postprocess.sh

**Comment by dustymabe** [comment]
I don't think we need this any longer since newer upstream doesn't have this problem AFAIU

**Comment by travier** [comment]
I think we should close this one as we have more specific issues in progress and this one seems to not be relevant anymore.
/close
