### ISSUE TITLE
latest (as of now) image doesn't work with installer

### ISSUE THREAD

**Issue by deads2k** [openshift/os#361]
the bootstrap machine reports 
```
Booting from Hard Disk...
Boot failed: not a bootable disk

No bootable device
```

recent:///4d85923c39d7dd786b0fcd395bc5d4f2

/assign @dustymabe

**Comment by deads2k** [comment]
by comparison, http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/images/cloud/4.0.6859-1/rhcos-qemu.qcow2.gz worked ok for me.

**Comment by dustymabe** [comment]
Hey @deads2k. A few questions: 
- you are running the installer via libvirt ? 
- Did you make any changes to the disk image (i.e. `qemu-img resize` )? 
- Did you verify the image matched the checksum file?

**Comment by dustymabe** [comment]
I'm downloading the latest image now to try and reproduce.

**Comment by deads2k** [comment]
> * you are running the installer via libvirt ?

yes



> * Did you make any changes to the disk image (i.e. `qemu-img resize` )?

no



> * Did you verify the image matched the checksum file?

I did not.

**Comment by ashcrow** [comment]
@dustymabe thank you for jumping on this! Looking at the compose the package difference looks to be an upgrade of `rpm-ostree` and `rpm-ostree-libs` according to the diff.

FWIW this is the ignition versions in 6869:
```
  ignition-0.28.0-8.gitf707912.el7.x86_64 (dustymabe-ignition)
  ignition-dracut-0.28.0-8.gitf707912.el7.noarch (dustymabe-ignition)
```

Which was upgraded in 6859:
```
  ignition 0.28.0-7.gitf707912.el7 -> 0.28.0-8.gitf707912.el7
  ignition-dracut 0.28.0-7.gitf707912.el7 -> 0.28.0-8.gitf707912.el7
```

**Comment by ashcrow** [comment]
The `kola` tests for libvirt and AWS both passed as well :confused:

**Comment by dustymabe** [comment]
>@ashcrow
> Which was upgraded in 6859

He said 6859 works, right? I'm only focused on 6869 for now. 

> @deads2k 
> > * Did you verify the image matched the checksum file?
> 
> I did not.

Do you mind trying it? I just booted rhcos-4.0.6869-qemu.qcow2 locally (not using installer) and it came up fine.

```
[dustymabe@media images]$ sha256sum rhcos-4.0.6869-qemu.qcow2.gz; cat rhcos-4.0.6869-qemu.qcow2.gz.sha256sum
154e20e2bfb1818ca9caba8ec61a8219027bc7945c83426174bd1a5df91fd355  rhcos-4.0.6869-qemu.qcow2.gz
154e20e2bfb1818ca9caba8ec61a8219027bc7945c83426174bd1a5df91fd355
[dustymabe@media images]$
[dustymabe@media images]$
[dustymabe@media images]$ gunzip rhcos-4.0.6869-qemu.qcow2.gz
[dustymabe@media images]$
[dustymabe@media images]$ sha256sum rhcos-4.0.6869-qemu.qcow2
f6b1b958c37ee716bfed3d8817c76a97495e7e26c96dd39c24fb4cbecb101288  rhcos-4.0.6869-qemu.qcow2
```

It came up fine:

```
[core@localhost ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://rhcos:openshift/3.10/x86_64/os
                   Version: 4.0.6869 (2018-10-16 01:07:07)
                    Commit: 4579f6cc268ae25961a8d293db62a2a258dafa4fc27930d076ade2ce34b175e8
```

**Comment by cgwalters** [comment]
Yeah, we don't ship a disk image unless it booted and passed some sanity checks.  This seems very likely to me to be a corrupted download of some form.

**Comment by jlebon** [comment]
Was it through the installer wizard that the image was downloaded? We could teach it to look for `$URL.sha256sum` to verify checksums.

**Comment by ashcrow** [comment]
> He said 6859 works, right? I'm only focused on 6869 for now.

@dustymabe correct. I wanted to compare between a working and non-working image.

**Comment by cgwalters** [comment]
> We could teach it to look for $URL.sha256sum to verify checksums.

Remember that pipeline is going to go away.  I just submitted:

https://github.com/coreos/coreos-assembler/pull/171

**Comment by deads2k** [comment]
> Do you mind trying it? I just booted rhcos-4.0.6869-qemu.qcow2 locally (not using installer) and it came up fine.

Pretend for a moment that I don't know where the image is and I don't know how do a checksum on it.  Can I get some directions?

**Comment by dustymabe** [comment]
> Pretend for a moment that I don't know where the image is and I don't know how do a checksum on it. Can I get some directions?

if you locate the config.yaml from the installer run you should be able to find where the qcow is locally on your system:

```
# grep imagePath config.yaml
  imagePath: /home/dustymabe/rhcos-4.0.6969-qemu.qcow2
```

Then sha256sum that. You should be able to use the same sha256sum I posted before of the uncompressed qcow to verify:

```
# sha256sum rhcos-4.0.6869-qemu.qcow2
f6b1b958c37ee716bfed3d8817c76a97495e7e26c96dd39c24fb4cbecb101288  rhcos-4.0.6869-qemu.qcow2
```

**Comment by deads2k** [comment]
> if you locate the config.yaml from the installer run

I failed at this step.  It's not set in my env vars and it doesn't appear anywhere in under the local directory where I ran the installer.

**Comment by dustymabe** [comment]
it's been a while since I ran the installer so things have probably changed. I need to cycle my system and re-set it up again. In the mean time let's just use the big hammer to find the qcow on your system. Can you run `find / -name *qcow2 2>/dev/null` ?

**Comment by ashcrow** [comment]
From chat:

> If I'm the only reporter, feel free to close

If no one else reports an issue in the next day let's go ahead and close. I'd expect others to have hit this same issue if there was a problem with the compose.

**Comment by wking** [comment]
Also, if you use non-`file://` URIs for the libvirt image, the installer will cache them locally, and you'll have your past unzipped images in here:

```console
$ ls -l ~/.cache/openshift-install/libvirt/image/
total 8180904
-r--r--r--. 1 trking trking 1671954688 Oct 11 10:50 2454fcdc0a61a9005fbf916b54fbe332
-r--r--r--. 1 trking trking 1671954688 Oct  5 01:39 4ed399503a17765f9436efe749e2b939
-r--r--r--. 1 trking trking 1673003264 Oct 15 22:23 639d8bc0a8acdb3286996f4c750b957e
-r--r--r--. 1 trking trking 1671954688 Oct  2 14:09 b6074429c26ac3b6a8bd901908602cfd
-rw-r--r--. 1 trking trking 1688338688 Oct  3 23:35 f1d16b0a8b48c2ca0494c687b1e40905
```

I dunno about the changing permissions, possibly a side-effect of some local development ;).  The filenames are MD5s of the ETags:

```console
$ curl -sI http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/images/cloud/latest/rhcos-qemu.qcow2.gz | grep -i etag
ETag: "5bc53e8c-2a1af34b"
$ echo -n '5bc53e8c-2a1af34b' | md5sum 
639d8bc0a8acdb3286996f4c750b957e  -
```

I dunno if there's a way to look up ETag -> RHCOS release though (although you could launch a node from the image and look inside).

**Comment by ashcrow** [comment]
After speaking with @deads2k and @dustymabe further it is likely that this was a corrupted download. We'll open a feature request issue in the installer to see if there can be some kind of integrity check added in future versions.
