### ISSUE TITLE
aws/ore: force uploads for init/dev builds

### ISSUE THREAD

**Issue by yuqi-zhang** [openshift/os#367]
When ore attempts to upload to AWS, since the dev pipeline uses the same name (e.g. `redhat-coreos-maipo-47` on an init), `ore` finds an existing snapshot and does not actually upload the new image even if changes were applied. This should not be an issue for the production (main) builds of RHCOS but is annoying to test with dev branches.

To preserve idempotency we could only force an upload for dev branches/init runs. Alternatively we could e.g. add a timestamp to the name. Since the pipeline returns if no changes were detected, we wouldn't push to aws the same image regardless.

cc @cgwalters

**Comment by cgwalters** [comment]
> Alternatively we could e.g. add a timestamp to the name. Since the pipeline returns if no changes were detected, we wouldn't push to aws the same image regardless.

I agree with this.

**Comment by ashcrow** [comment]
>> Alternatively we could e.g. add a timestamp to the name. Since the pipeline returns if no changes were detected, we wouldn't push to aws the same image regardless.
>>
> I agree with this.

:+1:

**Comment by travier** [comment]
Looks like this issue should be moved to coreos-assembler if it is still relevant.
