### ISSUE TITLE
Maipo OpenStack image 47.91 doesn't seem to run ignition

### ISSUE THREAD

**Issue by tomassedovic** [openshift/os#368]
I've tried to use the openstack `47.91` build with openshift/installer (using the same process that was working fine with the older `4.0.6987` images).

I can't SSH in (with the same installer binary, openstack cloud and config). Suspecting an ignition failure, I tried to run `openstack console log show <server>` and it did not return any output.

With the older images, ever when ignition doesn't run, the console log normally shows some output (boot messages etc.). Without the console log, I'm not sure how else to debug this.

I can easily reproduce this so if you've got ideas, please let me know!

**Comment by miabbott** [comment]
As a starting point, I was able to derive the pkg diffs from the two versions, in case something jumps out at us:

```
$ rpm-ostree db diff --repo=repo 82c1d75a8a7d3292a96de598f81ce8f2e210d6b9c4b844e5336b554ee061ef46 edb144967c6eff7919250a410926113870a292ff34fcb32315699d5b4d762cc3                     
ostree diff commit old: 82c1d75a8a7d3292a96de598f81ce8f2e210d6b9c4b844e5336b554ee061ef46
ostree diff commit new: edb144967c6eff7919250a410926113870a292ff34fcb32315699d5b4d762cc3
Upgraded:
  bubblewrap 0.3.1.4-8fc5a96b3ef4a8038365059412342f9cccbe2a87.el7.centos -> 0.3.1.6-94147e233fe200d1fe43a9a18c52475188b22798.el7.centos                                                                           
  coreos-metadata 3.0.1-1.el7 -> 3.0.2-1.el7
  cri-o 1.11.6-1.rhaos3.11.git2d0f8c7.el7 -> 1.11.8-1.rhaos3.11.git71cc465.el7
  glusterfs 3.12.2-18.el7 -> 3.12.2-25.el7
  glusterfs-client-xlators 3.12.2-18.el7 -> 3.12.2-25.el7
  glusterfs-fuse 3.12.2-18.el7 -> 3.12.2-25.el7
  glusterfs-libs 3.12.2-18.el7 -> 3.12.2-25.el7
  ignition 0.28.0-8.gitf707912.el7 -> 0.28.0-10.gitf707912.el7
  ignition-dracut 0.28.0-8.gitf707912.el7 -> 0.28.0-10.gitf707912.el7
  origin-clients 4.0.0-0.alpha.0.9.8d6f6f3 -> 4.0.0-0.alpha.0.556.a7f822d
  origin-hyperkube 4.0.0-0.alpha.0.9.8d6f6f3 -> 4.0.0-0.alpha.0.556.a7f822d
  origin-node 4.0.0-0.alpha.0.9.8d6f6f3 -> 4.0.0-0.alpha.0.556.a7f822d
  ostree 2018.8.40-1db0db3d7aa98e3db98ba93f7fc2e17305f95007.b94f5cb21655219ed7a31265beea5fb9aeccc960.el7.centos -> 2018.9.8-8eac5be030797607715d5a2d973c55edff78a8a2.0467f3242594410502f573075918e3cae0d083aa.el7.centos
  ostree-grub2 2018.8.40-1db0db3d7aa98e3db98ba93f7fc2e17305f95007.b94f5cb21655219ed7a31265beea5fb9aeccc960.el7.centos -> 2018.9.8-8eac5be030797607715d5a2d973c55edff78a8a2.0467f3242594410502f573075918e3cae0d083aa.el7.centos
  ostree-libs 2018.8.40-1db0db3d7aa98e3db98ba93f7fc2e17305f95007.b94f5cb21655219ed7a31265beea5fb9aeccc960.el7.centos -> 2018.9.8-8eac5be030797607715d5a2d973c55edff78a8a2.0467f3242594410502f573075918e3cae0d083aa.el7.centos
  pivot 0.0.1.23-73e29936c9f350f698962a48501cfe9334b58296.el7 -> 0.0.1.26-eb6cc16bab5af730dd01a96f26254a1b0fca4550                                                                                                
  podman 0.9.3.1-2.git1cd906d.el7 -> 0.10.1.3-1.gitdb08685.el7
  rpm-ostree 2018.8.96-6583a557aefa35bf3c47e65518f3a40d755ff66b.c98d67835edbb6a61b078db03e27b71a3b95d96b.el7.centos -> 2018.9.40-1dee43319cafb150dff50fdc2c7d04b35acd7d5e.d8a5bf5d7acae1bdd57001f2a39aa8e890f79c0f.el7.centos
  rpm-ostree-libs 2018.8.96-6583a557aefa35bf3c47e65518f3a40d755ff66b.c98d67835edbb6a61b078db03e27b71a3b95d96b.el7.centos -> 2018.9.40-1dee43319cafb150dff50fdc2c7d04b35acd7d5e.d8a5bf5d7acae1bdd57001f2a39aa8e890f79c0f.el7.centos
  subscription-manager-rhsm-certificates 1.20.11-1.el7_5 -> 1.21.10-2.el7
```

**Comment by tomassedovic** [comment]
I wonder if it's something else about putting the image together.

When I booted it up in OpenStack, I could see it in libvirt (my openstack is using the KVM backend) `virsh list --all`. And when running `virsh dumpxml <instance name> | grep 'log file`, I could access the VM's console log directly on disk.

For `rhcos-4.0.6987-openstack`, this contained the usual console log output but for `redhat-coreos-maipo-47.94-openstack` it was empty (just like the nova console log).

I'm not sure what exactly does that mean. Seems to me that it's not specific to how OpenStack treats the images (since the underlying virt provider has the same issue). It may be more about how the image was put together.

Any chance the new pipeline might be missing some step for the openstack images?

**Comment by tomassedovic** [comment]
So the image formats seem to be different (`raw` for the `47.94` and `qcow2` for `4.0.6987`). I've retested the newer maipo image making sure I pass `--disk-format raw` when uploading it to OpenStack, but it didn't seem to change anything.

```
# qemu-img info redhat-coreos-maipo-47.94-openstack.qcow2
image: redhat-coreos-maipo-47.94-openstack.qcow2
file format: raw
virtual size: 689M (722914304 bytes)
disk size: 689M

# qemu-img info rhcos-4.0.6987-openstack.qcow2
image: rhcos-4.0.6987-openstack.qcow2
file format: qcow2
virtual size: 8.0G (8589934592 bytes)
disk size: 1.6G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

**Comment by cgwalters** [comment]
It's not `raw` - but it *is* compressed.  Did you uncompress it before downloading?  

Correct info looks like this:

```
# qemu-img info /srv/libvirt/images-gold/redhat-coreos-maipo-47.91-openstack.qcow2 
image: /srv/libvirt/images-gold/redhat-coreos-maipo-47.91-openstack.qcow2
file format: qcow2
virtual size: 16G (17179869184 bytes)
disk size: 1.6G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

**Comment by cgwalters** [comment]
If downloading via curl, use e.g. `curl --compressed -L -O https://.../redhat-coreos-maipo-47.94-openstack.qcow2`

**Comment by tomassedovic** [comment]
Well, this is embarrassing. That was it. I just `wget`ed the image and tried to use it directly. In slight defense, the extension was `qcow2` not `gz` or something.

But yeah, when I've added `.gz` and ran it through `gunzip`, it booted properly. I'll test it with the installer a bit later, but I'm pretty sure this is it.

Thanks and sorry!

**Comment by dustymabe** [comment]
>  In slight defense, the extension was `qcow2` not `gz` or something.

I agree.

Currently we have the following instructions in the app:

```
# curl --compressed -L -O https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/maipo/47.94/redhat-coreos-maipo-47.94-qemu.qcow2
```

@cgwalters would it be more reasonable to change the filename to qcow2.gz and just change the curl command to: 

```
# curl --compressed -L -o redhat-coreos-maipo-47.94-qemu.qcow2 https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/maipo/47.94/redhat-coreos-maipo-47.94-qemu.qcow2
```

@tomassedovic, do you think that would have helped you?

**Comment by tomassedovic** [comment]
Yeah that would definitely have helped.
