### ISSUE TITLE
use persistent nic names for bare metal

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#370]
There are reasons persistent nic names are good for bare metal; we should need to tweak our buildsystem so that when we output a bare metal image we strip those arguments.

**Comment by dustymabe** [comment]
This might have some implications for https://github.com/openshift/os/issues/358 where the fix would involve not hardcoding `eth0` on the kernel command line.

**Comment by cgwalters** [comment]
Also related [internal Red Hat discussion](https://url.corp.redhat.com/ae6d832).

**Comment by cgwalters** [comment]
This is fixed with https://github.com/coreos/coreos-assembler/pull/305
