### ISSUE TITLE
Change /etc/os-release to include full version

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#372]
We have `OSTREE_VERSION` there but the `4.0` constant is confusing; let's fix it to use our full version.

**Comment by ashcrow** [comment]
Related: https://github.com/openshift/os/issues/360

**Comment by mrguitar** [comment]
Can we use one of the version fields for 4.0 and the other for the ostree version? Maybe VERSION_ID is set to the OSTREE_VERSION.

**Comment by ashcrow** [comment]
- #360 could be `VERSION_ID`
- `OSTREE_VERSION` should also likely match #360 
- `VERSION` would be #360 + other text if we so choose.

@cgwalters @mrguitar WDYT?


Reference: https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by ashcrow** [comment]
```
NAME="Red Hat CoreOS"
VERSION="400.7.20180515.0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="400.7.20180515.0"
PRETTY_NAME="Red Hat CoreOS 400.7.20180515.0"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

[...]
```

:+1: / :-1:

**Comment by ashcrow** [comment]
See https://github.com/openshift/redhat-release-coreos/pull/20

**Comment by jeremyeder** [comment]
Hi, how can something detect whether a node is RHCOS 7 or 8?

Is the schema of VERSION_ID stable/safe to parse?

**Comment by ashcrow** [comment]
`VERSION_ID` itself is safe to parse. Other fields will change to be inline with the expected version numbers, but `VERSION_ID` is stable as it points to the version of Openshift.

**Comment by jeremyeder** [comment]
I thought 400.7 where the 7 might be "special".  Is that wrong?

**Comment by ashcrow** [comment]
That's `VERSION` ... and `7` is in reference to the OS version we are based on.

**Comment by ashcrow** [comment]
Based on conversation with @jeremyeder and a need for specific information we're likely going to change this up so that @jeremyeder and team gain specific information they need for feature work while still being clear in the tie to Openshift in version information.

**Comment by jeremyeder** [comment]
Thanks @ashcrow.  I think once your new /etc/os-release content lands, we should be OK for the immediate use-case.

**Comment by ashcrow** [comment]
This has been implemented in the v3 pipeline and is currently pumping out images.
