### ISSUE TITLE
Add vmware drivers in initramfs

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#373]
https://github.com/openshift/os/commit/b40f19eb5eefdbf375cbf6fe058255cd4f5f3431

needs to be converted to `initramfs-args`.

**Comment by dustymabe** [comment]
The manifest-base.yaml for RHCOS now contains 

 ```
initramfs-args:
  - "--no-hostonly"
  - "--add-drivers"
  - "mptspi vmw_pvscsi"
  - "--add"
  - "iscsi"
  - "ignition"
```

marking this as done.
