### ISSUE TITLE
Enhancement request: compress rhcos qemu images with xz, instead of gz

### ISSUE THREAD

**Issue by mykaul** [openshift/os#375]
(As https://github.com/openshift/installer/issues/976 was closed):
You can save ~25% of the file download time (and size).
Example:

[ykaul@ykaul image]$ du -ch *
657M	a143c801ad1d611be3efaaafcd4ddc3e.gz
493M	a143c801ad1d611be3efaaafcd4ddc3e-xz.xz
1.2G	total
The download experience will be better. I assume decompression will take slightly longer.

Other similar projects (Lago & ovirt-system-tests) have been using XZ for years.

(You might think of downloading it over HTTP/2, btw, as it is served from Cloudfront. Perhaps it'll make the experience slightly better - unsure it's worth the effort if the data is already compressed!)

**Comment by gbraad** [comment]
This means the installer would need to support XZ, which AFAIR is not a standard package (https://github.com/xi2/xz, https://github.com/ulikunitz/xz) to allow decompression.

**Comment by dustymabe** [comment]
yeah XZ is amazing from a compression perspective, but does take more host system memory (risk of OOM) to decompress and also takes a lot longer to decompress. Those negatives should be considered along with the benefits.

**Comment by mykaul** [comment]
Compared to the amount of memory you actually need to run the VMs, the memory use of XZ decompression is a non-issue. It does take longer to decompress, but with 25% less network and less disk IO, it usually ends up faster than gz. (For example, NOT downloading ~160MB in 10MB/sec download rates that I have in an ideal condition at home, means 16secs less download time).

**Comment by mykaul** [comment]
Looks like CodeReadyContainers are using it for their VM image already (https://github.com/code-ready/snc/blob/19f6b040a4d6826dec7f711b7306121e44dccba7/createdisk.sh#L390 )

**Comment by cfergeau** [comment]
crc is using xz for its bundle, but it's not a magic bullet, it's quite heavyweight, especially with the golang xz implementations being 50% slower than the native library, ... It makes our bundle smaller, but at a cost.
