### ISSUE TITLE
Plumb through os version into `oc adm release info` or so

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#377]
Today I am not aware of an easy way to get the OS version out of the release payload and plumbed through into e.g. `oc adm release info` or `oc get clusterversion` etc.

The OS is a pretty important component and we should highlight it.

Although is there a general model for plumbing through the version of components into the cluster version?  It's common for code to store its git tag like `3.11.0-691-g0648af91-dirty` into the binaries...which e.g. today the MCO highlights into the operator.

But the build system doesn't inject that kind of thing into the image metadata?  Should e.g. `oc adm release new` propagate the `version` field into the `image-references` in the payload?

**Comment by smarterclayton** [comment]
There is working coming for this which will be centrally managed rather than farmed out to the individual teams.

**Comment by smarterclayton** [comment]
Right now `kubernetes` is already shown and either `machine-os` or `coreos` would be added.  Still working on details of what makes sense to do for machine-os-content.

**Comment by cgwalters** [comment]
>  Still working on details of what makes sense to do for machine-os-content.

Thanks!  Would love to track any existing work on this (issue/PRs) or help out where possible.

**Comment by ashcrow** [comment]
> Thanks! Would love to track any existing work on this (issue/PRs) or help out where possible.

Same here!

**Comment by cgwalters** [comment]
This is fixed in current 4.5+.
