### ISSUE TITLE
Ignition timeout while wait for IP

### ISSUE THREAD

**Issue by FlorinPeter** [openshift/os#380]
Hi,

I have sometimes the issue that it takes some time for the VM to get the IP and till then the ignition is timing out, how can I extend the retries as it looks like that the limit is set to 10?

I attached the console log.
[ignition_timeout_console-log.txt](https://github.com/openshift/os/files/3156352/ignition_timeout_console-log.txt)

**Comment by lucab** [comment]
This would probably be better as a ticket against Ignition, but let's start triaging it here and eventually move it once we have a plan.

So the platform is `openstack` and the DHCP seems to be taking about 40 seconds to configure, likely because of a large number of interfaces. Attached log seem to be missing some parts, but the relevant snippet is around here:
```
[   10.480414] dhclient[628]: DHCPDISCOVER on enp4s4 to 255.255.255.255 port 67 interval 7 (xid=0x41197d3c)
[   10.683868] ignition[659]: GET http://169.254.169.254/openstack/latest/user_data: attempt #6
[   10.688065] ignition[659]: GET error: Get http://169.254.169.254/openstack/latest/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
[   15.684252] ignition[659]: GET http://169.254.169.254/openstack/latest/user_data: attempt #7
[   15.689129] ignition[659]: GET error: Get http://169.254.169.254/openstack/latest/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
[   16.827765] dhclient[628]: DHCPDISCOVER on enp4s4 to 255.255.255.255 port 67 interval 7 (xid=0x41197d3c)
[   20.684602] ignition[659]: GET http://169.254.169.254/openstack/latest/user_data: attempt #8
[   20.689171] ignition[659]: GET error: Get http://169.254.169.254/openstack/latest/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
[   21.829563] random: crng init done
[   21.831409] random: 7 urandom warning(s) missed due to ratelimiting
[   24.425761] dhclient[628]: DHCPDISCOVER on enp4s4 to 255.255.255.255 port 67 interval 10 (xid=0x41197d3c)
[   25.684938] ignition[659]: GET http://169.254.169.254/openstack/latest/user_data: attempt #9
[   25.689143] ignition[659]: GET error: Get http://169.254.169.254/openstack/latest/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
[   30.685275] ignition[659]: GET http://169.254.169.254/openstack/latest/user_data: attempt #10
[   30.689459] ignition[659]: GET error: Get http://169.254.169.254/openstack/latest/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
[   33.711500] dhclient[628]: DHCPDISCOVER on enp4s4 to 255.255.255.255 port 67 interval 18 (xid=0x41197d3c)
[   33.743839] dhclient[628]: DHCPREQUEST on enp4s4 to 255.255.255.255 port 67 (xid=0x41197d3c)
[   33.747969] dhclient[628]: DHCPOFFER from 10.0.7.254
[   33.760791] dhclient[628]: DHCPACK from 10.0.7.254 (xid=0x41197d3c)
[   33.780344] dracut-initqueue[574]: dhcp: BOND setting enp4s4
[   34.482465] ignition[659]: neither config drive nor metadata service were available in time. Continuing without a config...
[   34.487642] ignition[659]: failed to fetch config: not a config (empty)
[[0;32m  OK  [0m] Started Ignition (disks).
[   34.491147] systemd[1]: Started Ignition (disks).
[   35.800717] dhclient[628]: bound to 10.0.5.57 -- renewal in 42256 seconds.
[   35.854966] dracut-initqueue[574]: Starting dhcp for interface ens3
[   35.884231] dracut-initqueue[574]: dhcp: PREINIT ens3 up
[   35.898511] dhclient[724]: Created duid "\000\004\262\026S\372\022\314ND\202\246\345\206\203\267\273F".
[   35.903516] dhclient[724]: DHCPDISCOVER on ens3 to 255.255.255.255 port 67 interval 5 (xid=0xc6648f77)
[   35.907974] dhclient[724]: DHCPREQUEST on ens3 to 255.255.255.255 port 67 (xid=0xc6648f77)
[   35.912084] dhclient[724]: DHCPOFFER from 10.0.3.254
[   35.914795] dhclient[724]: DHCPACK from 10.0.3.254 (xid=0xc6648f77)
[   35.928069] dracut-initqueue[574]: dhcp: BOND setting ens3
[   37.947173] dhclient[724]: bound to 10.0.1.57 -- renewal in 35254 seconds.
```

In Igniton, specifically on the `openstack` provider, we hardcoded an upper [timeout to 30s](https://github.com/coreos/ignition/blob/e3e3cbf4be8a6c79e1e3d65a9e02c537bb75f420/internal/providers/openstack/openstack.go#L55).

This is usually fine as HTTP roundtrips/timeouts also add some time, and in the end we don't hit this limit. However in this case dialing fails on-spot and we only have the backoff time (max 5s) to sleep.

We cannot unfortunately remove the upper limit, as openstack baseline does not mandate the presence of either metadata-endpoint nor config-drive. Additionally, any arbitrary upper limit is bound to be unfit for some scenarios, like the one here.

**Comment by lucab** [comment]
@ajeddeloh what we can maybe do to improve the situation here is to augment the upper-limit logic and tie it to a user-controlled input.
I'm thinking of checking for `ignition.timeouts.httpTotal != 0`, and in that case conditionally set the upper limit to `max(k * httpTotal, 30s)`, with an arbitrary large constant `k` that we pick. I think that this won't break any existing working case, but could help on nasty environments like the one above.

**Comment by ajeddeloh** [comment]
There's a command line flag `-fetchTimeout` we could bump or conditionally bump on different platforms (use systemd drop ins) which is probably what we want.

**Comment by lucab** [comment]
Moving this issue to https://github.com/coreos/ignition/issues/1081.

/close
