### ISSUE TITLE
`cosa run --uefi-secure` fails

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#383]
`cosa run --uefi-secure` on the FCOS qemu image works fine for me, but with RHCOS 4.3:

```
error:
../../g
rub-core/loader/i386/efi/linux.c:314:(hd0,gpt1)/ostree/rhcos-704ccb3018da61bb4b
8a07cead40186e13ac100ee819226bc32017b0a8102b88/vmlinuz-4.18.0-80.11.2.el8_0.x86
_64 has invalid signature.
error:
../../grub-core/loader/i386/efi/linux.c:314:(hd0,gpt1)/ostree/rhcos-704ccb3018d
a61bb4b8a07cead40186e13ac100ee819226bc32017b0a8102b88/vmlinuz-4.18.0-80.11.2.el
8_0.x86_64 has invalid signature.
error: ../../grub-core/loader/i386/efi/linux.c:206:you need to load the kernel
first.
error: ../../grub-core/loader/i386/efi/linux.c:206:you need to load the kernel
first.


Press any key to continue...Press any key to continue...

```

**Comment by miabbott** [comment]
@mike-nguyen you just did some testing of RHCOS with Secure Boot...any ideas here?

**Comment by mike-nguyen** [comment]
AFAIK OVMF does not come with any keys and I had to enroll the default set of keys so to allow the signed kernel from RHEL CoreOS to run [0].   My guess is that /usr/share/edk2/ovmf/OVMF_VARS.secboot.fd [1] does not have Red Hat keys.


[0] https://fedoraproject.org/wiki/Using_UEFI_with_QEMU#Run_EnrollDefaultKeys.efi
[1] https://github.com/coreos/coreos-assembler/blob/master/src/cmd-run#L304

**Comment by cgwalters** [comment]
Ah.  Hmm, what keys *are* there?  Is it...[this key](https://src.fedoraproject.org/rpms/edk2/blob/master/f/edk2.spec#_73)?  You'd think there'd be like a comment or something about what the key is...
Anyways I'll try from a RHEL8 userspace soon to see if that helps.

**Comment by mike-nguyen** [comment]
Hmm, just a quick look but that key was added about [2 months ago](https://src.fedoraproject.org/rpms/edk2/c/b9bff0b0890c29895178021ab9b2a41831e474c1).  Do you know what version we're running in cosa?

**Comment by mike-nguyen** [comment]
Here's the BZ  with a little more information on the Platform Key / Key Exchange Key https://bugzilla.redhat.com/show_bug.cgi?id=1701710#c12

**Comment by cgwalters** [comment]
Note that fixing this for RHCOS may also involve
https://github.com/coreos/coreos-assembler/pull/594#issuecomment-518815422

**Comment by cgwalters** [comment]
This will be fixed by https://github.com/coreos/coreos-assembler/pull/901
