### ISSUE TITLE
[4.3] Change build to be unpivoted by default

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#386]
Follow on to https://github.com/openshift/machine-config-operator/pull/1155
and internal pipeline change - ensure that RHCOS 4.3 works unpivoted by default.

This currently blocks on ART not building the MCD for 4.3.

**Comment by ashcrow** [comment]
cc @sosiouxme @tbielawa

**Comment by cgwalters** [comment]
https://github.com/openshift/ocp-build-data/pull/169

**Comment by sosiouxme** [comment]
https://jira.coreos.com/browse/ART-1125 is going to make this difficult but it can be done manually. However:

https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24131253

Fixy?

**Comment by cgwalters** [comment]
Now depends on https://github.com/openshift/machine-config-operator/issues/1185

**Comment by cgwalters** [comment]
Confirmed this works now.
