### ISSUE TITLE
running fsck on first boot

### ISSUE THREAD

**Issue by dustymabe** [openshift/os#392]
I noticed an fsck of the root filesystem running on the bootsrap node that adds about 50 seconds to the boot time of the bootstrap node:

```
Nov 19 15:58:43 dmabe-k9jtd-bootstrap.dmabe.tt.testing systemd[1]: Starting File System Check on /dev/disk/by-label/root...
Nov 19 15:58:43 dmabe-k9jtd-bootstrap.dmabe.tt.testing systemd-fsck[798]: /usr/sbin/fsck.xfs: XFS file system.
Nov 19 15:58:43 dmabe-k9jtd-bootstrap.dmabe.tt.testing systemd[1]: Started File System Check on /dev/disk/by-label/root.
Nov 19 15:59:35 dmabe-k9jtd-bootstrap.dmabe.tt.testing systemd-journald[221]: Missed 16 kernel message
```

Is this necessary? Should we try to save this time?

```
# rpm-ostree status 
State: idle
AutomaticUpdates: disabled
Deployments:
* ostree://025d77d2680e3a2ce60b3b832106319fefb81cfefbf1bf26fcf4bd1aeae0712d
                   Version: 43.81.201911081536.0 (2019-11-08T15:41:32Z)
```

**Comment by cgwalters** [comment]
FWIW I'm not seeing this in a just-launched system:
```
rpm-ostree status -b
State: idle
AutomaticUpdates: disabled
BootedDeployment:
* ostree://6798f144b445d33ce3e48cb31de6de8003cb364773f341e53fec3174c89a0ea0
                   Version: 43.81.201911192044.0 (2019-11-19T20:49:45Z)
```

**Comment by cgwalters** [comment]
Also just downloaded that exact bootimage, don't see a fsck on boot.

And it gives me a clean mount.

Are you sure that e.g. your VM didn't get killed and restarted or something?

**Comment by dustymabe** [comment]
> Also just downloaded that exact bootimage, don't see a fsck on boot.
> 
> And it gives me a clean mount.
> 
> Are you sure that e.g. your VM didn't get killed and restarted or something?

I'm pretty sure it was the first boot. I did see it multiple times but I've since blown away that entire host and re-installed it. I just tried another install and I don't see the fsck on boot of the bootstrap node so I'll close this and re-open if I'm able to reproduce in future installs.

Thanks for sanity checking this @cgwalters
