### ISSUE TITLE
Openshift 4.3, Is there a way to add a second dns server to workers and masters

### ISSUE THREAD

**Issue by johnlongo** [openshift/os#400]
I originally built the cluster (workers & maters) to use only one dns server, but want to add a second. Is there a way I can do that? Thank You in advance for any information.

**Comment by travier** [comment]
You will probably want to do that via the MCO: https://docs.openshift.com/container-platform/4.6/post_installation_configuration/machine-configuration-tasks.html

See also: https://github.com/openshift/os/blob/master/docs/faq.md#q-where-should-i-report-issues-with-openshift-container-platform-or-red-hat-coreos

/close
