### ISSUE TITLE
Installing CoreOS on Intel VROC RAID1 leaves array in degraded state

### ISSUE THREAD

**Issue by Feelas** [openshift/os#401]
**Version**
Openshift 4.2 and 4.3

**Platform:**
baremetal

**What happened?**
After the installer is launched with rd.md=1 rd.auto coreos.inst.install_dev=md126 (where md126 is a reference to /dev/md126, which is an assembled VROC RAID1 array), the OS ends up installed, but the whole process leaves the array in degraded state. This leaves the system boostrapped not the way that was intended (with redundancy).

**What you expected to happen?**
Installation on /dev/md126 to succeed properly without degrading the array. Maybe there's a special way to install CoreOS that way or modify the standard wipefs+dd behaviour?

**How to reproduce it (as minimally and precisely as possible)?**
Assemble an Intel VROC RAID1 array and install to the resultant MD device (e.g. /dev/md126) with parameters provided above.

**Anything else we need to know?**
Most probably this is due to how the installation process is handled. Possibly due to wipefs being launched, which kills the metadata on partition, and afterwards being overwritten with dd. I would probably investigate modifying the Ignition files manually, but I'd rather not delve into monkey patching myself.

**Comment by miabbott** [comment]
This looks like a problem with the legacy `coreos-installer` that is being used with RHCOS/OCP 4.2 + 4.3.

I'm going to transfer this issue over to the `coreos-installer` repo for additional input.

**Comment by miabbott** [comment]
Couldn't transfer it automagically, so just copied over there - https://github.com/coreos/coreos-installer/issues/179
