### ISSUE TITLE
Cannot able to use the docker tag in openshift online

### ISSUE THREAD

**Issue by repo-wiseacre** [openshift/os#405]
I have used the below yaml

`kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: os v0.3.0
  namespace: meessage
  selfLink: /apis/build.openshift.io/v1/namespaces/meessage/buildconfigs/os
  uid: f3911277-907e-4c1b-b046-87eff502cdd6
  resourceVersion: '278595188'
  creationTimestamp: '2020-06-09T03:30:56Z'
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'registry.fedoraproject.org/fedora:28'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/os.git'
      ref: master
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/ruby@sha256:35e6ada1215bb168d6d9aff01001438a3c35c4fcb64680be3b7f23a5f2257863
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
`

**Comment by miabbott** [comment]
It's not clear what exactly is being attempted here, but problems against OpenShift Online should be filed in Bugzilla - https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online
