### ISSUE TITLE
Installing kernel-devel and kernel-header packages in RHCOS for Openshift nodes

### ISSUE THREAD

**Issue by Sarang-Sangram** [openshift/os#411]
I am trying to find a way to install the kernel-devel and kernel-header packages , but didn't found any documentation regarding it. 
Though in the RHCOS architecture page it says that /usr is read-only, and secondly the while trying there isn't any repo which shows the package availability.

Kindly help.

**Comment by cgwalters** [comment]
This will be fixed in 4.6 with extensions https://github.com/openshift/enhancements/blob/master/enhancements/rhcos/extensions.md
