### ISSUE TITLE
RHCOS Vmware image not meeting security compliance rules

### ISSUE THREAD

**Issue by noushi** [openshift/os#412]
Hello,

# Version

```
Openshift 4.5
```

# Platform:

* vsphere
* IPI

# What happened?

One of our customers is failing the security compliance check due to the RHCOS image lacking VM hardening options.

The security report mentions the following VM options that should be set:
- isolation.device.connectable.disable
- isolation.device.edit.disable
- isolation.tools.copy.disable
- isolation.tools.diskShrink.disable
- isolation.tools.diskWiper.disable
- isolation.tools.getCreds.disable
- isolation.tools.guestDnDVersionSet.disable
- isolation.tools.hgfsServerSet.disable
- isolation.tools.memSchedFakeSampleStats.disable
- isolation.tools.paste.disable
- isolation.tools.vmxDnDVersionGet.disable
- tools.guestlib.enableHostInfo

# What you expected to happen?

These options should be set in order to meet corporate security compliance.

# How to reproduce it (as minimally and precisely as possible)?

The RHCOS image that is used during IPI lacks these.

**Comment by miabbott** [comment]
Hi @noushi, we prefer that problems against RHCOS are reported via Bugzilla:

https://github.com/openshift/os#reporting-issues

Could you please recreate this issue using the link below?

https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform&component=RHCOS

**Comment by noushi** [comment]
> Hi @noushi, we prefer that problems against RHCOS are reported via Bugzilla:
> 
> https://github.com/openshift/os#reporting-issues
> 
> Could you please recreate this issue using the link below?
> 
> https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform&component=RHCOS

Hi @miabbott ,

Thank you. 

It's here: https://bugzilla.redhat.com/show_bug.cgi?id=1905721

Where is the source code for the RHCOS image?

**Comment by miabbott** [comment]
Thanks for creating the BZ!  I will close this issue as a result.

The source code lives in this repo and is built with http://github.com/coreos/coreos-assembler

I suspect the code you are interested in (related to this issue/BZ) is here - https://github.com/coreos/coreos-assembler/blob/6c15e323b3d7cf2f22a350cc63449a482ce70eb4/src/cosalib/vmware.py
