### ISSUE TITLE
bootstrap ignition file its running in loop and starting with emergency mode on bootstrap server

### ISSUE THREAD

**Issue by darpan91** [openshift/os#420]
We are installing OKD 4.5.0 Openshift version on RHCOS 4.5.2 & RHEL 7.8 (service server) Operating system . we are planning to create 3 master and 2 worker node.

We have created Service server (Helper node) with RHEL OS.
Ignition files(bootstrap ,master and worker) has been created on Same server.

While running kernel command with bootstrap ignition file its running in loop and starting with emergency mode on bootstrap server .

We are unable to boot the bootstrap node .

Attached error screenshot . Please help us to resolve the issue.
![bootstrap node error](https://user-images.githubusercontent.com/65757312/97397556-8adee780-190f-11eb-908d-50f77f2f9efd.JPG)

**Comment by ashcrow** [comment]
Note: The reporter was asked to move this GitHub issue to this repo: https://github.com/openshift/installer/issues/4310

**Comment by darpan91** [comment]
hi Stephen,
I have got replied on openshift/installer#4310 ticket to raised issue on  openshift/os .
Please note : Both are same issue.
If you are aware of issue . Please help me with resolution.

Regards,
Darpan

**Comment by travier** [comment]
Thanks for your report but this is however not the best place to get support for RHCOS or OCP.
This issue tracker is for the development work related to Red Hat CoreOS.

Please see [Red Hat support options](https://access.redhat.com/support) or open a ticket for OCP in the [Red Hat Bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform).

**Comment by travier** [comment]
Issues with [OKD](https://www.okd.io/) should be reported at [openshift/okd](https://github.com/openshift/okd).

Be aware that [only Fedora CoreOS is supported in OKD for control plane nodes](https://docs.okd.io/latest/architecture/architecture.html#architecture-custom-os_architecture):

> In OKD Latest, you must use FCOS for all control plane machines, but you can use Red Hat Enterprise Linux (RHEL) as the operating system for compute machines, which are also known as worker machines. If you choose to use RHEL workers, you must perform more system maintenance than if you use FCOS for all of the cluster machines.

**Comment by darpan91** [comment]
Hi Timothee,
Could you please confirm that only Fedora CoreOS is supported in OKD for control plane nodes and Red Hat CoreOS is not supported in OKD.
Please share if you have any document for same.

Regards,
Darpan Yadav

**Comment by travier** [comment]
> Could you please confirm that only Fedora CoreOS is supported in OKD for control plane nodes and Red Hat CoreOS is not supported in OKD.

Yes, from the OKD documentation: https://docs.okd.io/latest/architecture/architecture.html#architecture-custom-os_architecture

- OKD -> Fedora CoreOS
- OpenShift -> RHEL CoreOS
