### ISSUE TITLE
RHCOS-OCP boot is failing for worker node: ignition[xxx]: GET result: Internal Server Error

### ISSUE THREAD

**Issue by darpan91** [openshift/os#429]
We are trying to install RHCOS-OCP. During RHCOS installation , Bootstrap & master node booted successfully. We are able to login the same.
But we are getting error while booting worker node. Please find attached error.

Openshift 4.5.2
RHCOS 4.5.2 (1 bootstrap ,3 master & 2 worker )
RHEL 7.8 (helper node)
![worker node boot error](https://user-images.githubusercontent.com/65757312/98116730-b4c77980-1ece-11eb-9acf-e0ea26ce5053.JPG)

Regards,
Darpan Yadav

**Comment by travier** [comment]
Please see this [FAQ entry](https://github.com/openshift/os/blob/master/docs/faq.md#q-where-should-i-report-issues-with-openshift-container-platform-or-red-hat-coreos) on how to reach out for customer support.

/close

**Comment by travier** [comment]
You will get better support if go via the proper channels. I'm sorry that I have to close your issues here.

**Comment by darpan91** [comment]
can you please suggest where i can raise this issue

**Comment by travier** [comment]
You can use the [official support options](https://access.redhat.com/support) or [file a Bugzilla report](https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform).
