### ISSUE TITLE
Support multipath with LUKS on RHCOS

### ISSUE THREAD

**Issue by Prashanth684** [openshift/os#431]
For multipath , we need to provide the `root=/dev/disk/by-label/dm-mpath-root` on subsequent boot . This turns out to be a problem with LUKS as the coreos-luks-open.service has a conditional `ConditionKernelCommandLine=!root` (https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fde/coreos-luks-open.service#L6). This causes the service to fail:
```
● coreos-luks-open.service - CoreOS LUKS Opener
   Loaded: loaded (/usr/lib/systemd/system/coreos-luks-open.service; enabled-ru>
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-11-02 15:14:47 UTC; 5min ago
           └─ ConditionKernelCommandLine=!root was not met
```

And if the root karg is not provided it fails in coreos-cryptfs with:

```
coreos-cryptfs[655]: device-mapper: reload ioctl on coreos-luks-root-nocrypt (253:1) failed: Device or resource busy
```
This needs to be fixed for multipath to wok with LUKS.

**Comment by cgwalters** [comment]
See https://github.com/openshift/os/issues/426 - the current LUKS code will go away hopefully soon.

**Comment by Prashanth684** [comment]
closing this as this was fixed through https://github.com/openshift/os/pull/436
