### ISSUE TITLE
s390x: Upgrade from old luks to new not working with DASD disks

### ISSUE THREAD

**Issue by Prashanth684** [openshift/os#448]
Was testing out https://github.com/openshift/os/pull/436 on some Z systems by locally upgrading using ostree and it works fine on s390x systems with fiber channel disks, but on systems with DASD disks, it's problematic because of how DASD disks work. `sgdisk` doesn't work with DASD only `fdasd` works. There has to be some conversion of sectors to tracks as DASD disks represents data in tracks and not sectors, so there is some translation needed.But that's not even the hard part. fdasd's non interactive mode is severly limited and unlike sgdisk you cannot delete a specific partition or change labels, etc. So in effect, the whole partition layout has to be recreated. I'm wondering if we would have to `dd` the boot and root partitions and save them , use fdasd to recreate the partitions and then copy them over (omitting the luks header offset of course). I am not sure of any other good way to do this.Any ideas are appreciated. cc @nikita-dubrovskii

**Comment by Prashanth684** [comment]
specifically this : https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/libexec/rhcos-upgrade-root-filesystem-container#L39 will not work .I also started experimenting with this patch to convert the sectors to tracks and recreate the partitions:
```
--- a/overlay.d/05rhcos/usr/libexec/rhcos-upgrade-root-filesystem-container
+++ b/overlay.d/05rhcos/usr/libexec/rhcos-upgrade-root-filesystem-container
@@ -19,24 +19,49 @@ if [ -h "/dev/mapper/coreos-luks-root-nocrypt" ]; then
     startsector="$(($(cat /sys/block/$parent/$partition/start)+32768))"
     # the dm device is already the correct size
     size=$(cat /sys/block/$dm_device_name/size)
-
-    # check / handle 4k sector size devices
     sector_size=$(cat /sys/block/$parent/queue/logical_block_size)
-    if [ "$sector_size" == "4096" ]; then
-        startsector=$((startsector / 8))
-        size=$((size / 8))
-    fi
 
     # validate that the new partition will start at the xfs super block
-    skipcount=$(($startsector * $sector_size))
+    skipcount=$(($startsector * 512))
     if [ $(dd if=/dev/$parent bs=1 count=4 status=none skip=$skipcount) != XFSB ]; then
         echo "couldn't detect XFS superblock at expected partition start"
         exit
     fi
 
-    # recreate the partition offset after the LUKS header
-    # we don't want to copy the typeguid because that's pointing to crypt_luks
-    sgdisk -d $partnum -n $partnum:$startsector:+$size -c $partnum:$label /dev/$parent -u $partnum:$guid
+    if [[ "$parent" == "dasd"* ]]; then
+        blocks_per_track=$(fdasd -p "/dev/$parent" | grep blocks\ per\ track | awk '{print $5}')
+        rootsize=$((size / (blocks_per_track * 8)))
+        rootstart=$(((startsector + (blocks_per_track * 8) - 1) / (blocks_per_track * 8)))
+
+        partitions=$(ls -d /sys/block/$parent/dasd*)
+        conffile=$(mktemp)
+        for part in $partitions
+        do
+            partname=$(basename "$part")
+            if [ "$partname" == "$partition" ]; then
+                echo "[$rootstart,$(($rootstart + $rootsize - 1)),native]" >> $conffile
+            else
+                start=$(cat /sys/block/$parent/$partname/start)
+                size=$(cat /sys/block/$parent/$partname/size)
+                starttrack=$(((start+(blocks_per_track * 8)-1)/(blocks_per_track * 8)))
+                sizetracks=$((size/(blocks_per_track * 8)))
+                echo "[$starttrack,$(($starttrack + $sizetracks - 1)),native]" >> $conffile
+            fi
+        done
+        # recreate all partitions using fdasd
+        fdasd --silent --config $conffile /dev/$parent || : 
+    else
+        # check / handle 4k sector size devices
+        if [ "$sector_size" == "4096" ]; then
+            startsector=$((startsector / 8))
+            size=$((size / 8))
+        fi
+
+        # recreate the partition offset after the LUKS header
+        # we don't want to copy the typeguid because that's pointing to crypt_luks
+        sgdisk -d $partnum -n $partnum:$startsector:+$size -c $partnum:$label /dev/$parent -u $partnum:$guid
+    fi
+
```
but fdasd nukes the partitions and recreates it so we need to somehow preserve it.

**Comment by arithx** [comment]
Whoops.

Quick feedback on your patch from: changing the `skipcount` definition to hardcode sector size to `512` will break the XFS superblock check on 4Kn images.

**Comment by Prashanth684** [comment]
> Whoops.
> 
> Quick feedback on your patch from: changing the `skipcount` definition to hardcode sector size to `512` will break the XFS superblock check on 4Kn images.

i had already moved changing to the 4k sector size down below, so having it as 512 should be ok:
```
-    if [ "$sector_size" == "4096" ]; then
-        startsector=$((startsector / 8))
-        size=$((size / 8))
-    fi
```

**Comment by jlebon** [comment]
> So in effect, the whole partition layout has to be recreated. I'm wondering if we would have to dd the boot and root partitions and save them , use fdasd to recreate the partitions and then copy them over (omitting the luks header offset of course).

If we recreate the full partition table with the right offsets, do we actually still need to `dd` off data? Does `fdasd` actually wipe all the data corresponding to the freshly created partitions?

**Comment by Prashanth684** [comment]
> > So in effect, the whole partition layout has to be recreated. I'm wondering if we would have to dd the boot and root partitions and save them , use fdasd to recreate the partitions and then copy them over (omitting the luks header offset of course).
> 
> If we recreate the full partition table with the right offsets, do we actually still need to `dd` off data? Does `fdasd` actually wipe all the data corresponding to the freshly created partitions?

I'm not sure if fdasd wipes the data, it is not clear from the documentation. The other thing i'm worried about is - the partitions are created with the specified tracks. the blocks per track on the DASD system is 12 , so the LUKS header - 32768/(12*8) ends somewhere inside a track, so the offset that i provide is the next track which is not right. But if that is the case i don't know what else we can do other than dd it.

**Comment by Prashanth684** [comment]
> > > So in effect, the whole partition layout has to be recreated. I'm wondering if we would have to dd the boot and root partitions and save them , use fdasd to recreate the partitions and then copy them over (omitting the luks header offset of course).
> > 
> > 
> > If we recreate the full partition table with the right offsets, do we actually still need to `dd` off data? Does `fdasd` actually wipe all the data corresponding to the freshly created partitions?
> 
> I'm not sure if fdasd wipes the data, it is not clear from the documentation. The other thing i'm worried about is - the partitions are created with the specified tracks. the blocks per track on the DASD system is 12 , so the LUKS header - 32768/(12*8) ends somewhere inside a track, so the offset that i provide is the next track which is not right. But if that is the case i don't know what else we can do other than dd it.

so just for the record fdasd does not wipe the data but unfortunately if we use fdasd we have  to specify tracks and the file system seems to start somewhere in the middle of the track which is the problem.

**Comment by hbrueckner** [comment]
I can confirm that fdasd just changes the partition table and does not touch the disk content.

**Comment by hbrueckner** [comment]
Also talked to @stefan-haberland and he confirmed that fdasd uses tracks for partition start/end as there are constraints from the compatible-disk layout (CDL) for constructing the VTOCs.

Based on @Prashanth684 observation, that the LUKS header might end in a track (which depends on model/blocksize is roughly around 56K), is not possible to change the partition table to skip the LUKS header.

The question now is whether it is possible to move the file system to the beginning of the partition or to introduce a superblock that points to the starting of the file system.
