### ISSUE TITLE
productize redirector service

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#542]
This is related to an internal non-public ticket following up on https://github.com/openshift/os/issues/477

Basically we need to move our current [releases-art-rhcos.svc.ci.openshift.org](https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7/47.83.202012030221-0/x86_64/meta.json) to an ART hosted production cluster.

Currently, this is:
```
$ oc get dc/releases-art
NAME           REVISION   DESIRED   CURRENT   TRIGGERED BY
releases-art   3          1         1         config,image(releases-art:latest)
$
```

Notable is:
```
  Annotations:  openshift.io/generated-by: OpenShiftNewApp
```

My recollection is indeed this was created by `oc new-app` and is not stored in https://github.com/openshift/release/ git.

The backing image is `registry.svc.ci.openshift.org/rhcos/releases-art` which...is now inaccessible.  So we can't easily backreference to the source code.

I *believe* the source code may be https://github.com/cgwalters/os/tree/redirector

**Comment by cgwalters** [comment]
OK right and then there was a lot of work on https://gitlab.cee.redhat.com/coreos/release-browser but I am pretty sure (can't confirm now due to the registry being away) that the "public redirector" code from there was never actually deployed in api.ci.

**Comment by cgwalters** [comment]
OK I realized I can just e.g. `oc rsh pod/releases-art-3-4whfv` which helps me see the nginx config.

Ah and this is useful:
```
$ oc get builds -l app=releases-art
NAME             TYPE     FROM          STATUS     STARTED         DURATION
releases-art-1   Source   Git@013dead   Complete   2 years ago     46s
releases-art-2   Source   Git@6b4cdd7   Complete   2 years ago     1m4s
releases-art-3   Source   Git@6b4cdd7   Complete   11 months ago   30s
$ oc describe builds/releases-art-3
Name:		releases-art-3
Namespace:	rhcos
Created:	11 months ago
Labels:		app=releases-art
		buildconfig=releases-art
		openshift.io/build-config.name=releases-art
		openshift.io/build.start-policy=Serial
Annotations:	openshift.io/build-config.name=releases-art
		openshift.io/build.number=3
		openshift.io/build.pod-name=releases-art-3-build

Status:			Complete
Started:		Tue, 19 May 2020 11:57:21 EDT
Duration:		30s
  FetchInputs:		  0s
  CommitContainer:	  0s
  Assemble:		  1s
  PushImage:		  5s

Build Config:	releases-art
Build Pod:	releases-art-3-build
Image Digest:	sha256:4e2f55bf9578483a3a653484e503384a797bacedbfd8958ab40fff2b62a609fd

Strategy:		Source
URL:			https://github.com/cgwalters/os.git
Ref:			redirector
ContextDir:		public-redirector
Commit:			6b4cdd7 (fixup! Add public-redirector sources)
Author/Committer:	Colin Walters
From Image:		DockerImage registry.access.redhat.com/rhscl/nginx-112-rhel7@sha256:1870fe09b8e94066e94e4ac51417ae72ff750fd8bdfd2329d4959d48ee4488af
Output to:		ImageStreamTag releases-art:latest
Push Secret:		builder-dockercfg-2mn9k

Build trigger cause:	Manually triggered

Events:	<none>

```

**Comment by cgwalters** [comment]
Anyways I have created https://github.com/cgwalters/rhcos-redirector

**Comment by cgwalters** [comment]
I think the work to unify the redirector and release browser UI made sense at the time, but for now let's just give ART the absolute minimum thing they actually need to run in production.  We don't want to need to rev this thing to roll out new UI for example.  So that's the argument for splitting back the redirector.

**Comment by miabbott** [comment]
It looks like *something* is deployed somewhere doing redirection, otherwise URLs like this wouldn't work, right?

https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.8/48.83.202103221318-0/x86_64/meta.json

**Comment by cgwalters** [comment]
Yes, that's the service we set up that:

- Is part of a cluster slated to be decomissioned
- And even if we moved it to e.g. app.ci, that's part of our CI infrastructure which is not supposed to be used to actually deliver content to users
- Does not have an operations team managing it, alerting, etc.
- Is not managed via gitops in a reproducible fashion

**Comment by miabbott** [comment]
_nodding intensifies_

**Comment by cgwalters** [comment]
Done in https://github.com/openshift/release/pull/18496
