### ISSUE TITLE
be buildable with f34 cosa somehow, or bust

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#552]
Followup to https://github.com/openshift/os/pull/547 and https://github.com/openshift/os/pull/548

Right now we're in an ugly situation where because f34 rpm dropped support for bdb, yet rhel8 only works with bdb we cannot use f34 to build rhcos(8).

Options:

- Just require the `rhcos-4.8` cosa-f33 branch for a while (6 months?) and see if the rpm maintainers end up doing something here (e.g. sqlite support in rhel8).
- jlebon's idea of somehow using the host librpm to write as sqlite, and then pipe the data to the target rpm to downconvert to bdb  (I think we'd need to carry f33 rpm for this which is the only one that does both?  How ugly would it be to e.g. build a statically linked f33 rpm binary and include it in our container?)  Hmm, maybe we could convince the rpm maintainers to ship something like `/usr/lib/rpm/rpm-sqlite2bdb --dbin /path/to/srcdb --dbout /path/to/destdb` in rhel8?
- Switch over to using a C8S coreos-assembler for *both* fcos and rhcos
- Switch over to C8S coreos-assembler just for rhcos

Or something else?

**Comment by cgwalters** [comment]
jlebon correctly found https://bugzilla.redhat.com/show_bug.cgi?id=1938928 but I lost track of that BZ in the PRs/issues here.  I commented there, I think rpm sqlite readonly support is enough.  Let's leave this open to track work doing the conversion.

**Comment by cgwalters** [comment]
Ultimately the conversion code I think should land in rpm-ostree, i.e. all that happens here is we set `rpmdb: bdb` and rpm-ostree knows to do the dance internally instead of us doing it as a postprocess script or whatever.

**Comment by jlebon** [comment]
Yeah, I think that's the easiest approach, even if it's not great. One note is that the RHBZ is planned for 8.5, so we might have to hold until RHCOS rebases.

**Comment by miabbott** [comment]
Do we have a path forward on this issue?

4.8 is reaching code freeze soon, which means we would just start using `coreos-assembler:main` again.

Could we change the internal `coreos-assembler:main` BuildConfig to use F33?

```  strategy:
    dockerStrategy:
      env:
      - name: GIT_URL
        value: https://github.com/coreos/coreos-assembler
      - name: GIT_REF
        value: main
      - name: OPENSHIFT_GIT_HACK
        value: "TRUE"
      from:
        kind: ImageStreamTag
        name: fedora:33
      noCache: true
    type: Docker
```

**Comment by cgwalters** [comment]
> Do we have a path forward on this issue?

The [conversation above](https://github.com/openshift/os/issues/552#issuecomment-842317637) covers one where rpm-ostree learns how to do this conversion.

> Could we change the internal coreos-assembler-main BuildConfig to use F33?

That's not long term sustainable though because we're mostly focusing on F34+ for e.g. rpm-ostree builds and cosa development.  If we have to fork in that way, the other option is to try again to create a rhel8 based coreos assembler plus cherry picked newer versions of things.  But, I think we should chase down the rpm-ostree approach above first.

**Comment by cgwalters** [comment]
I'm looking at this actively, and am testing a hack for converting the rpmdb as part of postprocessing, but this may then trigger further issues around things like `rpm-ostree db diff` and such that also happen at build time.

Ahh whee and it needs to happen *before* the bootupd integration runs which also reads the rpmdb.

**Comment by cgwalters** [comment]
:tada: this works for me https://github.com/coreos/rpm-ostree/pull/2990

**Comment by jlebon** [comment]
Nice work @cgwalters! Confirmed I got a successful RHCOS compose using latest rpm-ostree release.

So all that's left to do now is: https://github.com/coreos/coreos-assembler/pull/2302
