### ISSUE TITLE
ignition build failure

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#59]
Currently we use the Fedora guildelines for [ExclusiveArch](https://github.com/ashcrow/ignition-specs/blob/482358ab3ef19047f769e441de7dbd1b91e92c9f/ignition.spec#L24) but our buildroot today isn't pulling in the necessary golang macros, so we end up with `ExclusiveArch:` (nothing).

This is a painful type of issue when mixing fedora/el spec builds.  We can likely just drop the `ExclusiveArch` for now in our spec - but it might also not be too hard to add the golang macros to our buildroot definition.

**Comment by ashcrow** [comment]
I've commented out ``ExclusiveArch`` in the ``ignition-specs`` repo.

**Comment by cgwalters** [comment]
Hm, still doesn't work because of the `BuildRequires`.  We *should* be getting `go-srpm-macros`.  I'm investigating.

**Comment by cgwalters** [comment]
https://github.com/cgwalters/rpmdistro-gitoverlay/pull/47

**Comment by cgwalters** [comment]
Well, somehow that fixed it.  :man_shrugging:

**Comment by cgwalters** [comment]
This came back.

**Comment by jlebon** [comment]
I think I found the issue... testing.

**Comment by cgwalters** [comment]
Now that I look briefly...is it related somehow to `redhat-release-coreos` having a different version or something?

**Comment by jlebon** [comment]
https://github.com/ashcrow/ignition-specs/pull/2

Though part of me wonders if the more correct thing to do is to enhance rdgo so that we can exclude packages that are fed back into the buildroot.

**Comment by ashcrow** [comment]
@jlebon I think that is the *right* way to do it. But I think merging your PR in ``ignition-specs`` to get things working again now is good enough for the time being.

**Comment by ashcrow** [comment]
Merged https://github.com/ashcrow/ignition-specs/pull/2

**Comment by ashcrow** [comment]
Let's see what happens with the next build.

**Comment by jlebon** [comment]
This is fixed now!
