### ISSUE TITLE
[c9s] `ext.config.root-reprovision.luks` failing

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#605]
> Ignition failed: failed to create luks: binding clevis device: exit status 1: Cmd: "clevis" "luks" "bind" "-f" "-k" "/run/ignition/luks-keyfiles/myluksdev" "-d" "/run/ignition/dev_aliases/dev/disk/by-partlabel/root" "sss" "{\"pins\":{\"tpm2\":{}},\"t\":1}" Stdout: "" Stderr: "Warning: Value 512 is outside of the allowed entropy range, adjusting it.\nERROR:esys_crypto:src/tss2-esys/esys_crypto_ossl.c:328:iesys_cryptossl_hmac_start() ErrorCode (0x00070001) EVP_PKEY_new_mac_key \nERROR:esys_crypto:src/tss2-esys/esys_crypto.c:185:iesys_crypto_authHmac() Error ErrorCode (0x00070001) \nERROR:esys:src/tss2-esys/esys_iutil.c:1243:iesys_compute_hmac() HMAC error ErrorCode (0x00070001) \nERROR:esys:src/tss2-esys/esys_iutil.c:1341:iesys_gen_auths() Error while computing hmacs ErrorCode (0x00070001) \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:237:Esys_CreatePrimary_Async() Error in computation of auth values ErrorCode (0x00070001) \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:110:Esys_CreatePrimary() Error in async function ErrorCode (0x00070001) \nERROR: Esys_CreatePrimary(0x70001) - esapi:Catch all for all errors not otherwise specified\nERROR: Unable to run tpm2_createprimary\nCreating TPM2 primary key failed!\nInvalid input!\nUsage: jose jwe fmt -i JWE [-I CT] [-o JWE] [-O CT] [-c]\n\nConverts a JWE between serialization formats\n\n  -i JSON --input=JSON     Parse JWE from JSON\n  -i FILE --input=FILE     Read JWE from FILE\n  -i -    --input=-        Read JWE from standard input\n\n  -I FILE --detached=FILE  Read decoded ciphertext from FILE\n  -I -    --detached=-     Read decoded ciphertext from standard input\n\n  -o JSON --output=JSON    Parse JWE from JSON\n  -o FILE --output=FILE    Read JWE from FILE\n  -o -    --output=-       Read JWE from standard input\n                           Default: \"-\"\n\n  -O JSON --detach=JSON    Parse JWE from JSON\n  -O FILE --detach=FILE    Read JWE from FILE\n  -O -    --detach=-       Read JWE from standard input\n\n  -c      --compact        Output JWE using compact serialization\n\nFailed to import token from file.\nError saving metadata to LUKS2 header in device /run/ignition/dev_aliases/dev/disk/by-partlabel/root\nUnable to update metadata; operation cancelled\nError adding new binding to /run/ignition/dev_aliases/dev/disk/by-partlabel/root\n"

**Comment by cgwalters** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1989321

**Comment by dustymabe** [comment]
The most recent `4.13-9.2` passed this test:

```
[2023-02-07T15:38:40.064Z] --- PASS: ext.config.shared.root-reprovision.luks (77.40s)
```

**Comment by travier** [comment]
Thanks for checking it.
