### ISSUE TITLE
tests: lots of FCOS tests are not run on RHCOS

### ISSUE THREAD

**Issue by lucab** [openshift/os#661]
Looking at the set of tests, there seems to be a large difference in cardinality between FCOS and RHCOS:
 * https://github.com/openshift/os/tree/639a5607455e59b8a71d2de89d3dbca97feb4d7e/tests/kola
 * https://github.com/coreos/fedora-coreos-config/tree/21b18cf06c5e63a80a0e4b9ff62aaf7c2207d03e/tests/kola

Some of this difference is on purpose, but some may be the result of just symlinks that didn't get created (e.g. for https://github.com/coreos/fedora-coreos-config/pull/1232).

It would be good to re-analyze how we are organizing our tests so that it becomes possible to write "common" tests in `fedora-coreos-config` and automatically pick them up when the submodule is updated.
At the same time, we'll still need to keep some tests specific to RHCOS or FCOS.

From an out-of-band chat: likely this can be done through test annotations/comments, or otherwise by re-arranging folders structure in a `{common, rhcos, fcos}` layout (with the former living in fedora-coreos-config and being a symlink here).

**Comment by lucab** [comment]
/remove-lifecycle stale
/assign @miabbott 

(I even think this is fully done at this point, but admittedly I haven't been following it)

**Comment by miabbott** [comment]
I think this is safe to close

/close
