### ISSUE TITLE
`crio` tests failing in downstream tests for RHCOS 4.10

### ISSUE THREAD

**Issue by miabbott** [openshift/os#674]
```
--- FAIL: crio.base (1225.37s)
    --- PASS: crio.base/crio-info (0.16s)
    --- FAIL: crio.base/pod-continues-during-service-restart (600.00s)
            harness.go:413: TIMEOUT[10m0s]
    --- FAIL: crio.base/networks-reliably (600.00s)
            harness.go:413: TIMEOUT[10m0s]
```

Seems to be correlated to introduction of `crio-1.23.0-23.rhaos4.10.git407d866.el8`

```
ostree diff commit from: a654ec98dfbd0f1309c921465afe2953f284257bbdd98eae85996e3486a0da24
ostree diff commit to:   5f64085e365ed08fcbad9f0ccfa9caeefe1476b5dcd0df2e646475596dda82ce
Upgraded:
  cri-o 1.23.0-12.rhaos4.10.git6ee64e9.el8 -> 1.23.0-23.rhaos4.10.git407d866.el8
  openshift-clients 4.10.0-202111092341.p0.git.a253d9d.assembly.stream.el8 -> 4.10.0-202111161511.p0.g96e0fad.assembly.stream.el8

New image input checksum: f86f660fa1c02152f8858478382a2c4e88ae864ca024636c8fba14a1864e553a
```

Changes in `cri-o` corresponding to the git commits:

```
$ git shortlog --no-merges 6ee64e9..407d866
Maximilian Ehlers (1):
      Updates kubeadm.md: The cgroup property is removed in [kubeadm-config.v1beta3](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/)

Peter Hunt (6):
      oci: make some channels buffered
      oci: always close chControl
      oci: fix deadlock in container stop code
      release-notes: update to main
      gh-actions: add sed for kube e2e
      server: fix segfault when using cgroupv2

Qi Wang (2):
      Bug 2012838: fix override storage options from storage.conf
      Specify runtime table format in  the error message

dependabot[bot] (6):
      build(deps): bump go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
      build(deps): bump google.golang.org/grpc from 1.41.0 to 1.42.0
      build(deps): bump go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
      build(deps): bump github.com/onsi/gomega from 1.16.0 to 1.17.0
      build(deps): bump github.com/containerd/ttrpc from 1.0.2 to 1.1.0
      build(deps): bump go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc
```

Nothing jumping out in the journal/console, will probably have to run the test manually to get more info.

Attached a zip file with console+journal.

[crio-fail.tar.gz](https://github.com/openshift/os/files/7549683/crio-fail.tar.gz)

cc: @haircommander

**Comment by miabbott** [comment]
Link to tests for non-CoreOS folks - https://github.com/coreos/coreos-assembler/blob/main/mantle/kola/tests/crio/crio.go

**Comment by haircommander** [comment]
we dropped the `/etc/crio/crio.conf` file from the RPM between this range, do the tests directly edit this file instead of using a drop-in file?

**Comment by miabbott** [comment]
> we dropped the `/etc/crio/crio.conf` file from the RPM between this range, do the tests directly edit this file instead of using a drop-in file?

Nope.

The journal seems to show that the last command that ran as part of the test was `crictl runp`

```
Nov 16 18:31:19.293513 sshd[1810]: Accepted publickey for core from 10.0.2.2 port 56642 ssh2: ECDSA SHA256:PIdEZlZyszhgLv16GulpC9lta6Weq5flbfxKqRoyp9s
Nov 16 18:31:19.299365 systemd-logind[1275]: New session 16 of user core.                                                                                      
Nov 16 18:31:19.300488 systemd[1]: Started Session 16 of user core.                                                                                            
Nov 16 18:31:19.301685 sshd[1810]: pam_unix(sshd:session): session opened for user core by (uid=0)
Nov 16 18:31:19.327641 sudo[1815]:     core : TTY=unknown ; PWD=/var/home/core ; USER=root ; COMMAND=/bin/crictl runp restart-testPod176293743                 
Nov 16 18:31:19.329752 sudo[1815]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Nov 16 18:31:19.330179 sudo[1815]: pam_unix(sudo:session): session opened for user root by (uid=0)                                                    
Nov 16 18:31:19.416669 crio[1280]: time="2021-11-16 18:31:19.415705986Z" level=info msg="Running pod sandbox: //POD" id=456238ae-fed8-447f-9243-02760bbbac5b name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
Nov 16 18:31:25.594863 systemd[1]: NetworkManager-dispatcher.service: Succeeded.                                                                               
Nov 16 18:31:44.937673 systemd[1]: systemd-hostnamed.service: Succeeded.                                                                                       
Nov 16 18:33:38.098573 chronyd[1229]: Source 44.190.40.123 replaced with 66.85.78.80              
Nov 16 18:36:30.541305 systemd[1397]: Starting Cleanup of User's Temporary Files and Directories...                                                                                                                                                                                                                           
Nov 16 18:36:30.552422 systemd[1397]: systemd-tmpfiles-clean.service: Succeeded.
Nov 16 18:36:30.552506 systemd[1397]: Started Cleanup of User's Temporary Files and Directories.                                                               
Nov 16 18:41:17.679552 sshd[1842]: Accepted publickey for core from 10.0.2.2 port 34042 ssh2: ECDSA SHA256:PIdEZlZyszhgLv16GulpC9lta6Weq5flbfxKqRoyp9s     
```
https://github.com/coreos/coreos-assembler/blob/7d4a64481e5027b46fcefc301b9a29f27426b069/mantle/kola/tests/crio/crio.go#L444-L445

So it appears that command didn't return successfully.

**Comment by jlebon** [comment]
Looks like it timed out. It's likely the test simply needs more time. The addition of timeouts is somewhat recent, and we're still ironing out which tests need more than the default 10 minutes. See e.g. https://github.com/coreos/coreos-assembler/pull/2546.

**Comment by miabbott** [comment]
Previous successful runs of the test take less than three minutes total, less than one minute per test

```
--- PASS: crio.base (135.00s)
    --- PASS: crio.base/crio-info (0.10s)
    --- PASS: crio.base/pod-continues-during-service-restart (58.58s)
    --- PASS: crio.base/networks-reliably (41.45s)
    ```

**Comment by haircommander** [comment]
@miabbott do you have a link to instructions on how to run these tests?

**Comment by miabbott** [comment]
@haircommander Kind of scattered about, but this is a good starting point - https://coreos.github.io/coreos-assembler/

1. setup a `cosa` alias - https://coreos.github.io/coreos-assembler/building-fcos/#define-a-bash-alias-to-run-cosa
2. get an RHCOS 4.10 qemu image from the internal release browser
3. `cosa shell `
4. `kola run --qemu-image <path to rhcos qemu iamge> crio.base`

You can hack on the tests by editing https://github.com/coreos/coreos-assembler/blob/main/mantle/kola/tests/crio/crio.go and doing `./build kola` to generate a new `kola` binary.  Then you can copy the `kola` binary from your host into the `cosa` container.

Dropping a manhole into the `crio` test can be helpful for debugging what is going wrong - https://coreos.github.io/coreos-assembler/kola/#manhole

**Comment by miabbott** [comment]
Oh right, but the latest qemu image will have a working `cri-o`, so you need to build an RHCOS yourself.

Redirect link to the internal build instruction - https://url.corp.redhat.com/cb85378

**Comment by cgwalters** [comment]
> Oh right, but the latest qemu image will have a working cri-o, so you need to build an RHCOS yourself.

I think it's way easier to `rpm-ostree override replace ./crio.rpm` on an existing node.

**Comment by cgwalters** [comment]
Though, it is harder to turn the test that way.  Which is a general problem with the builtin-Go kola tests as opposed to exttests.  One can usually just copy and paste the shell script from a test into bash.  

Hmm.  To really solve this problem we need to disentangle more the "provisioning" aspect from the "execute test" code in kola.

**Comment by haircommander** [comment]
I found the source of these failures, and I am leaning towards reverting the changes that caused them.

Basically, we attempted to drop the crio config file `/etc/crio/crio.conf` from the RPM (as previously discussed in a couple of places). This isn't problematic for nodes that have an MCD, because it places a 00-default config file which gives it the correct location for the cni plugins. However, in these tests there's no MCD, so crio doesn't have the correct directory for cni plugins, which means it can't create a container (it actually waits forever until the files are created, which is to work around the way container based cni plugins work). 

this shouldn't break anything in openshift, but it does break anyone who wants to use rhcos and cri-o without the MCD. Do we worry about these cases? If we want to keep around these tests we do, and I am personally thinking it's worth the revert and reconsideration

**Comment by miabbott** [comment]
> Do we worry about these cases? 

This is a good question...in the current model, it's simply not supported to use RHCOS + `crio` outside the OCP use case. We are using it here for some basic unit tests of `crio` outside of the cluster.

It's been discussed in the past that we should just be re-running the existing unit tests from various upstream locations (crio, podman, ostree, etc), so it might be better for us to explore how to make that happen than making changes to `crio` proper to support our use case.

We have plenty of coverage for `crio` in the OCP e2e tests, so if something truly broke in `crio` we would know about it, even if we chose not to maintain the unit tests here.

**Comment by haircommander** [comment]
At surface level it does seem weird that we install a binary that cannot run without another daemon being present on the system. That weirdness is partially mitigated by the fact that no one should be doing that, but it still feels odd

**Comment by haircommander** [comment]
the more I think about it the more I think this behavior is wrong. I think we should find a different way to drop the crio.conf, so I think I am going to revert the changes and we should reinstate the tests

**Comment by jlebon** [comment]
> We have plenty of coverage for `crio` in the OCP e2e tests, so if something truly broke in `crio` we would know about it, even if we chose not to maintain the unit tests here.

This is true, though I would still lean towards keeping some tests in kola, even if very basic, if it's not too much work. We're the first line of defense against super broken content bubbling up and it's much cheaper to catch things here than it is higher up.

**Comment by miabbott** [comment]
@haircommander let us know when the new `crio` is available with the `crio.conf` change reverted and we'll re-enable our tests

**Comment by haircommander** [comment]
hopefully will be in tonight's nightly!

**Comment by haircommander** [comment]
it should be available now

**Comment by miabbott** [comment]
New `cri-o` and the removal of the test from the denylist seems to be working out well, going to close this.
