### ISSUE TITLE
old cosa used for 4.11 builds

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#732]
For 4.11 we should be using cosa built in the app.ci cluster.  Specifically we really want https://github.com/coreos/coreos-assembler/pull/2726

```
$ oc project
Using project "coreos" on server "https://api.ci.l2s4.p1.openshiftapps.com:6443".
$ oc describe is/coreos-assembler
Name:			coreos-assembler
Namespace:		coreos
Created:		16 months ago
Labels:			<none>
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{},"name":"coreos-assembler","namespace":"coreos"},"spec":{"tags":[{"from":{"kind":"DockerImage","name":"quay.io/coreos-assembler/coreos-assembler:latest"},"importPolicy":{"scheduled":false},"name":"latest"}]}}
			
			openshift.io/image.dockerRepositoryCheck=2021-06-03T14:47:15Z
Image Repository:	registry.ci.openshift.org/coreos/coreos-assembler
Image Lookup:		local=true
Unique Images:		14
Tags:			6

latest
  tagged from coreos-assembler@sha256:67146920ff9ba758bbaec98d57259ef9cd7ded0eee462fd7bd08bd8f758c1f6f

  * image-registry.openshift-image-registry.svc:5000/coreos/coreos-assembler@sha256:d10412bb58700e21bba3cbc7381fb3487882e9c32c9b114c1db1ee3a4b430ebf
      29 hours ago
    image-registry.openshift-image-registry.svc:5000/coreos/coreos-assembler@sha256:a78ec8a26aaac2eaf657a4550519dfccdfe08b0b71bf5c122961309d8ed3ffae
      30 hours ago
    image-registry.openshift-image-registry.svc:5000/coreos/coreos-assembler@sha256:d10412bb58700e21bba3cbc7381fb3487882e9c32c9b114c1db1ee3a4b430ebf
      4 days ago
    image-registry.openshift-image-registry.svc:5000/coreos/coreos-assembler@sha256:7ad97f449a4eeb43ab688b467ceb6b33fd851dec954d65b48e8e3be2a1fdfcc4
      7 months ago
```

So that looks fine.

Yet:

```
$ oc image info registry.ci.openshift.org/coreos/coreos-assembler:latest
Name:        registry.ci.openshift.org/coreos/coreos-assembler:latest
Digest:      sha256:d10412bb58700e21bba3cbc7381fb3487882e9c32c9b114c1db1ee3a4b430ebf
Media Type:  application/vnd.docker.distribution.manifest.v2+json
Created:     4d ago
```

**Comment by cgwalters** [comment]
For now I manually did:

```
$ oc tag registry.ci.openshift.org/coreos/coreos-assembler@sha256:a78ec8a26aaac2eaf657a4550519dfccdfe08b0b71bf5c122961309d8ed3ffae coreos-assembler:latest
Tag coreos-assembler:latest set to registry.ci.openshift.org/coreos/coreos-assembler@sha256:a78ec8a26aaac2eaf657a4550519dfccdfe08b0b71bf5c122961309d8ed3ffae.
```

**Comment by cgwalters** [comment]
@jmarrero and I were looking at this, and he was saying the update time on the imagestream is likely because something else tagged it, not because a new image was built.

So we need to figure out what could be overriding the build.

I also at one point did a manual `oc start-build coreos-assembler`, and that generated a new image `sha256:9390541c6c28886436703c80d77ee88aa9720537bf6ebda91548a4bf0bfa7616` which did correctly appear in the imagestream and the registry.

**Comment by cgwalters** [comment]
OK as of right now quay.io is still old, which may need fixing
```
$ oc image info quay.io/coreos-assembler/coreos-assembler:latest
Name:        quay.io/coreos-assembler/coreos-assembler:latest
Digest:      sha256:d10412bb58700e21bba3cbc7381fb3487882e9c32c9b114c1db1ee3a4b430ebf
Media Type:  application/vnd.docker.distribution.manifest.v2+json
Created:     4d ago
```

**Comment by cgwalters** [comment]
Related recent PRs:

- https://github.com/openshift/release/pull/26221
- https://github.com/openshift/release/pull/26582
- https://github.com/openshift/release/pull/26588

**Comment by cgwalters** [comment]
Another operating theory; we're not getting github webhook event triggers from coreos/coreos-assembler to Prow, and previous builds were manual?

**Comment by jmarrero** [comment]
> Another operating theory; we're not getting github webhook event triggers from coreos/coreos-assembler to Prow, and previous builds were manual?

we can test that theory with: https://github.com/coreos/coreos-assembler/pull/2735 
maybe?
Whoever merges it would need to monitor the CI to see if that triggers a new image build+push.

**Comment by jmarrero** [comment]
Just read a thread from @jlebon and it looks like that he has been working for a few days to enable it. From the looks of the thread it looks like the webhook setup was a work in progress a day ago. So It is looking that there were manual builds before.

**Comment by miabbott** [comment]
Jonathan pointed me to https://issues.redhat.com/browse/COS-1253 regarding fixing the webhook

**Comment by cgwalters** [comment]
OK but we still have another problem here - *something* is overwriting `registry.ci.openshift.org/coreos/coreos-assembler` - and I think it's pulling from `quay.io/coreos-assembler/coreos-assembler:latest`.

IOW we swapped the direction of pull/pushing, and I think we still somehow have the "pull from quay" path.  What I see right now is:

```
$ apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{},"labels":{"app":"cosa","template":"cosa-template"},"name":"coreos-assembler","namespace":"coreos"},"spec":{"failedBuildHistoryLimit":1,"lookupPolicy":{"local":true},"successfulBuildsHistoryLimit":1,"tags":[{"from":{"kind":"DockerImage","name":"quay.io/coreos-assembler/coreos-assembler:master"},"importPolicy":{"scheduled":true},"name":"upstream"}]}}
...
```

So...that looks suspicious, but https://github.com/openshift/release/pull/26221 should have merged and applied...

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/26693

**Comment by mike-nguyen** [comment]
Was this only a mirroring issue?  Do we still need to look at the build trigger?

**Comment by cgwalters** [comment]
I think indeed we need to fix the build trigger too!
