### ISSUE TITLE
RHCOS 4.11 + RHEL 8.6: nothing provides qemu-kiwi needed by kata-containers

### ISSUE THREAD

**Issue by miabbott** [openshift/os#736]
@HuijingHei is working on early RHCOS 4.11 builds using pre-released RHEL 8.6 content and ran into this issue today:

`nothing provides qemu-kiwi >= 5.1.0-16 needed by kata-containers-2.3.2-2.el8.x86_64`

It looks like the `qemu-kiwi` package has been removed from the 8.6 sources - https://bugzilla.redhat.com/show_bug.cgi?id=2002694

(Filing this issue for a place to discuss next steps with the RHEL-AV team)

**Comment by HuijingHei** [comment]
Thanks @miabbott. 
Ask help from @xiangchunfu, new kata-containers version(maybe 2.4, not found on brew yet) will be built with dependency of qemu-kvm and will be used on new OCP 4.11, after 4.10 is released.

**Comment by etrunko** [comment]
I have built kata-containers-2.3.2-3.el8, can you check if this version fixes the problem?

**Comment by HuijingHei** [comment]
> I have built kata-containers-2.3.2-3.el8, can you check if this version fixes the problem?

With new version, the problem is gone. Thanks!

Check [rhaos](https://download.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/plashets/4.11-el8/building/x86_64/os/Packages/) already includes `kata-containers-2.3.2-3.el8.x86_64.rpm`, change to 8.6 nightly AV repo, build locally and run `cosa buildextend-extensions` without errors

**Comment by etrunko** [comment]
FYI, a newer 2.3.2-4.el8 version is available, with the same dependency fix plus another small problem that I have identified.

**Comment by HuijingHei** [comment]
Thanks @etrunko for your update, rebuild RHCOS 4.11 based on 8.6 AV repo using pipeline and verify the dependency issue is fixed

**Comment by cgwalters** [comment]
Sounds like this is fixed
