### ISSUE TITLE
RHCOS 4.11 x86_64 error about missing script for creating stable symlink to boot disk

### ISSUE THREAD

**Issue by miabbott** [openshift/os#755]
Was going through the journal for a separate issue and saw the following:

`Mar 22 19:06:09 localhost [1488]: failed to execute '/usr/lib/udev/coreos-disk-contains-fs' 'coreos-disk-contains-fs vda boot': No such file or directory`

This happens after the switch to the real root and by my read of https://github.com/coreos/fedora-coreos-config/pull/1308 the udev rule is only available in the initrd, with the symlink being removed during initramfs teardown.

So the error looks scary, but is harmless AFAICT

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/1620 should fix this.

**Comment by miabbott** [comment]
Let's keep this open until we do the submodule bump

**Comment by bgilbert** [comment]
The submodule bump landed in #758.
