### ISSUE TITLE
RHCOS 4.11 s390x - multipath.day1 failures

### ISSUE THREAD

**Issue by miabbott** [openshift/os#760]
```
--- FAIL: multipath.day1 (129.73s)
        cluster.go:162: mount: /boot/efi: mount point does not exist.
        cluster.go:213: "\n\t\t\tsudo mount -o ro /dev/disk/by-label/EFI-SYSTEM /boot/efi\n\t\t\tsudo sh -c 'test -f /boot/efi/EFI/*/bootuuid.cfg'\n\t\t\tsudo umount /boot/efi" failed: Process exited with status 32; logs from journalctl -t kola:
+ sudo test -f /boot/.root_uuid
+ sudo test -f /boot/grub2/bootuuid.cfg
+ 
			sudo mount -o ro /dev/disk/by-label/EFI-SYSTEM /boot/efi
			sudo sh -c 'test -f /boot/efi/EFI/*/bootuuid.cfg'
			sudo umount /boot/efi
umount: /boot/efi: no mount point specified.
```

[kola_artifacts.zip](https://github.com/openshift/os/files/8362897/kola_artifacts.zip)

**Comment by jschintag** [comment]
I have seen that error with a different error already:
```
--- FAIL: multipath.day1 (85.63s)
        cluster.go:213: "sudo test -f /boot/grub2/bootuuid.cfg" failed: Process exited with status 1; logs from journalctl -t kola:
+ sudo test -f /boot/.root_uuid
+ sudo test -f /boot/grub2/bootuuid.cfg
```
[kola_artifacts.zip](https://github.com/openshift/os/files/8362938/kola_artifacts.zip)

Looks like it is trying to do something grub related on s390x. But i can't seem to find where it is invoking `sudo test -f /boot/.root_uuid` and `sudo test -f /boot/grub2/bootuuid.cfg`

**Comment by miabbott** [comment]
https://github.com/coreos/coreos-assembler/blob/f27b8aa008412836c7d0cb15e53036cd68430a44/mantle/kola/tests/misc/multipath.go#L127-L136

**Comment by jlebon** [comment]
Regression from https://github.com/coreos/coreos-assembler/pull/2594. Will fix.

**Comment by jschintag** [comment]
Thanks @miabbott, seems i pulled the code on friday and forgot to refresh today :) That explains it.

**Comment by miabbott** [comment]
Searching the whole `coreos` org for `bootuuid.cfg` found it for me - https://github.com/search?q=org%3Acoreos+bootuuid.cfg&type=code

**Comment by jschintag** [comment]
Yeah, i should maybe search on github directly instead of my local clone

**Comment by jlebon** [comment]
@jschintag Could you sanity-check https://github.com/coreos/coreos-assembler/pull/2779 ?
