### ISSUE TITLE
RHCOS 4.11 + RHEL 8.6: Unable to launch an OpenShift cluster

### ISSUE THREAD

**Issue by javipolo** [openshift/os#764]
I tried to start an Openshift cluster using @HuijingHei https://github.com/HuijingHei/os/tree/rhcos-4.11-86 branch, and the installation never succeeds

Once the nodes are rebooted into CoreOS, some systemd units are not started, and this blocks the whole startup process

I can see in the logs errors like that:
```
Apr 01 16:51:21 master1 bash[31676]: Error: setxattr /etc/systemd/system/basic.target.wants/coreos-ignition-firstboot-complete.service: read-only file system                                 
```

And this unit file is a symlink to /usr
```
lrwxrwxrwx. 1 root root 66 Apr  1 15:20 /etc/systemd/system/basic.target.wants/coreos-ignition-firstboot-complete.service -> /usr/lib/systemd/system/coreos-ignition-firstboot-complete.service
```

As a workaround, if I manually mount /usr as read-write, the startup process continues properly and the instalation completes

**Comment by javipolo** [comment]
A not so drastic workaround also fixes the issue:
```
for i in $(find /etc/systemd -type l); do cp --remove-destination $(readlink $i) $i; done
```

**Comment by HuijingHei** [comment]
Refer to https://bugzilla.redhat.com/show_bug.cgi?id=2072072

**Comment by javipolo** [comment]
Problem seems to be podman related:
https://github.com/containers/podman/issues/13727

Seems the bug is already fixed in podman, so we should make sure to include a fixed version in RHEL8.6
https://github.com/containers/podman/pull/13689

**Comment by miabbott** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2074090

**Comment by ashcrow** [comment]
I linked the bugs as well to make the dependency a bit clearer.

**Comment by miabbott** [comment]
Now being tracked in an MCO template fix - https://bugzilla.redhat.com/show_bug.cgi?id=2074613

**Comment by javipolo** [comment]
MCO fixed this already:
https://github.com/openshift/machine-config-operator/pull/3079

I tried last build from @HuijingHei , that also ships fixed podman version, and it installs perfectly, so I guess we can close this issue
