### ISSUE TITLE
RHCOS 4.11 s390x - nvme is not a valid device model name

### ISSUE THREAD

**Issue by miabbott** [openshift/os#765]
Correlates with the switch to RHEL 8.6, but since the error is coming from `cosa`, perhaps a new `qemu` stack got pulled in during the most recent rebuild?

```text
+ cosa kola run --qemu-nvme=true basic
kola -p qemu-unpriv --output-dir tmp/kola run --qemu-nvme=true basic
������  Skipping kola test pattern "fips.enable*":
  ���� https://bugzilla.redhat.com/show_bug.cgi?id=1782026
������  Skipping kola test pattern "coreos.ignition.journald-log":
  ���� https://github.com/coreos/coreos-assembler/issues/1173
������  Skipping kola test pattern "coreos.ignition.mount.*":
  ���� https://bugzilla.redhat.com/show_bug.cgi?id=1899990
���� Snoozing kola test pattern "ext.config.shared.ignition.stable-boot" until Apr 19 2022:
  ���� https://github.com/openshift/os/issues/710
���� Snoozing kola test pattern "ext.config.shared.var-mount.scsi-id" until Apr 19 2022:
  ���� https://github.com/openshift/os/issues/710
=== RUN   basic
qemu-system-s390x: -device nvme,drive=d1,serial=primary-disk,bootindex=1: 'nvme' is not a valid device model name
2022-04-04T12:43:31Z kola: retryloop: failed to bring up machines: failed to establish qmp connection: dial unix /var/tmp/mantle-qemu673580088/qmp-1649076182562292192.sock: connect: connection refused
qemu-system-s390x: -device nvme,drive=d1,serial=primary-disk,bootindex=1: 'nvme' is not a valid device model name
2022-04-04T12:44:01Z kola: retryloop: failed to bring up machines: failed to establish qmp connection: dial unix /var/tmp/mantle-qemu116090922/qmp-1649076212597599938.sock: connect: connection refused
--- FAIL: basic (59.07s)
        harness.go:1406: Cluster failed starting machines: failed to establish qmp connection: dial unix /var/tmp/mantle-qemu116090922/qmp-1649076212597599938.sock: connect: connection refused
FAIL, output in tmp/kola
Error: harness: test suite failed
2022-04-04T12:44:01Z cli: harness: test suite failed
```

**Comment by miabbott** [comment]
@jschintag

**Comment by miabbott** [comment]
[kola_artifacts.zip](https://github.com/openshift/os/files/8410017/kola_artifacts.zip)

**Comment by jschintag** [comment]
Neither NVME nor UEFI scenarios should be run on multiarch. I created a MR to disable them again in the Pipeline.

**Comment by miabbott** [comment]
> Neither NVME nor UEFI scenarios should be run on multiarch. I created a MR to disable them again in the Pipeline.

As a follow-up, it feels like `kola` should know not to run those scenarios on multi-arch

**Comment by jschintag** [comment]
@miabbott agree

**Comment by cgwalters** [comment]
The knowledge/logic should be in coreos-assembler, not jenkins glue because we want to support stuff that's not-jenkins including Prow.

**Comment by jschintag** [comment]
> The knowledge/logic should be in coreos-assembler, not jenkins glue because we want to support stuff that's not-jenkins including Prow.

Well that one is a tough design decision i think. It already does that logic if you call `--basic-qemu-scenarios`, but i don't think that it would be good when you explicitly run `--nvme=true`, that it just does a basic test run instead. It might be worthwhile that it doesn't even attempt to run qemu and instead just displays `arch <x> does not support qemu with nvme`. But i don't think it is a good design when you say do X it does Y instead.

**Comment by travier** [comment]
I think cosa should just skip tests that it knows will fail on a given arch. If asked explicitly, we could have a warning but no point in breaking the pipeline every time we make a mistake here.

A more comprehensive fix is to add a "beta" mode to avoid changing this code every time we do a Beta rebase.

Closing as this is fixed in the internal pipeline.
