### ISSUE TITLE
Pull in (or rewrite) toolbox

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#78]
I think the *idea* of https://github.com/coreos/toolbox is really critical - even if the implementation is very basic. 

My strawman: Write a new tool that uses `podman` via the varlink API.  Have some opinionated defaults, like mounting `/srv:/srv` for passthrough, and also e.g. `-v /etc:/host/etc:ro -v /usr:/host/usr:ro` say.   But also just pass through some basic options like `--pid=host`.

In my dev containers I ended up doing `-v /home:/srv/container-home` so that I get persistent history.  There's a whole big decision point about using `--rm` by default here (which forces storing state elsewhere, IMO a good idea) or not.

**Comment by cgwalters** [comment]
https://pagure.io/atomic-wg/issue/505 is related here as far as passing through `/srv` by default.

**Comment by dustymabe** [comment]
should we migrate this to??  https://github.com/coreos/fedora-coreos-tracker/issues

**Comment by dustymabe** [comment]
or maybe https://pagure.io/ContainerSIG/container-sig/issues

**Comment by ashcrow** [comment]
IMHO it depends on ownership: If the CC&T wants to own it or if the ContainerSIG wants to own it.

**Comment by ashcrow** [comment]
@yuqi-zhang is working on toolbox updates in https://github.com/yuqi-zhang/toolbox/tree/rhcos-toolbox

**Comment by ashcrow** [comment]
PR: https://github.com/coreos/toolbox/pull/44

**Comment by ashcrow** [comment]
Is there more work we need to do before closing this issue @yuqi-zhang @cgwalters?

**Comment by yuqi-zhang** [comment]
@ashcrow see the discussions here: https://github.com/debarshiray/fedora-toolbox/issues/8

At some point I think we'd like to consolidate the two scripts. I'm testing it out and seeing what would be a good way to preserve existing workflow for *COS systems.

**Comment by cgwalters** [comment]
I feel like we have the basic functionality here now, we can track further work in other issues.
