### ISSUE TITLE
RHCOS 4.11 failing to build due to missing `qemu-kvm-core` dependency for `kata-containers`

### ISSUE THREAD

**Issue by miabbott** [openshift/os#795]
This appears to be fallout from reverting back to RHEL 8.5, so wanted to track this in the open.

```
+ cosa buildextend-extensions
Running: rpm-ostree compose extensions --repo=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/tmp/repo --touch-if-changed tmp/extensions/changed --cachedir=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/cache src/config/manifest.yaml src/config/extensions.yaml --base-rev 271460977b476d0fcd3184d106dbf0c11665af4fcaf5cc42ea35bd727118827d --output-dir tmp/extensions/output
Checking out 2714609... done!
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Enabled rpm-md repositories: rhel-8-server-ose rhel-8-fast-datapath rhel-8-baseos rhel-8-appstream rhel-8-nfv
Updating metadata for 'rhel-8-server-ose'...done
Updating metadata for 'rhel-8-fast-datapath'...done
Updating metadata for 'rhel-8-baseos'...done
Updating metadata for 'rhel-8-appstream'...done
Updating metadata for 'rhel-8-nfv'...done
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Importing rpm-md...done
rpm-md repo 'rhel-8-server-ose'; generated: 2022-05-05T16:01:36Z solvables: 426
rpm-md repo 'rhel-8-fast-datapath'; generated: 2022-04-25T14:15:35Z solvables: 736
rpm-md repo 'rhel-8-baseos'; generated: 2022-05-04T07:23:27Z solvables: 11158
rpm-md repo 'rhel-8-appstream'; generated: 2022-05-05T13:46:51Z solvables: 24626
rpm-md repo 'rhel-8-nfv'; generated: 2022-04-26T16:45:33Z solvables: 610
Resolving dependencies...done
[0m[31merror: [0mCould not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides qemu-kvm-core >= 15:6.2.0 needed by kata-containers-2.4.1-1.el8.x86_64
Traceback (most recent call last):
```

`kata-containers` is build out of the `rhaos-4.11-rhel-8` branch and has had it's spec file adjusted to expect certain dependencies available in RHEL 8.6. See https://github.com/openshift/os/pull/740

Since this is blocking RHCOS 4.11 builds and therefore updates to the `kublet`, etc for the rest of OCP, we need a way out of this while we continue to use RHEL 8.5

1. temporarily drop `kata-containers` from the extensions?

Drastic, but maybe the cleanest approach.

2. configure the 8.6 repo to get `qemu-kvm-core` back

This feels fraught with peril as the compose process is going to look for the highest NVR for *all* the packages, which means we would have to configure a boatload of `repo-packages` entries for everything we *don't* want from 8.6

Other ideas?

**Comment by miabbott** [comment]
cc: @dgoodwin @brenton

**Comment by etrunko** [comment]
You are right, this is caused by the revert to 8.5. Also we are very unlucky that the qemu dependency changed from 8.5 to 8.6. If we are sticking with 8.5, I suggest that we revert #740 and I will also change the dependency on kata-containers RPM back to qemu-kiwi.

**Comment by miabbott** [comment]
> You are right, this is caused by the revert to 8.5. Also we are very unlucky that the qemu dependency changed from 8.5 to 8.6. If we are sticking with 8.5, I suggest that we revert #740 and I will also change the dependency on kata-containers RPM back to qemu-kiwi.

The challenge is that we are not going to stick with 8.5 for the long term; this is a temporary revert and we still plan on using RHEL 8.6 for RHCOS/OCP 4.11.

I don't think we should change the `kata-containers` deps for this short amount of time.  Maybe we can temporarily use the 4.10 version of `kata-containers` and that way we can revert #740 and depend on `qemu-kiwi`?

**Comment by etrunko** [comment]
> I don't think we should change the `kata-containers` deps for this short amount of time. Maybe we can temporarily use the 4.10 version of `kata-containers` (`kata-containers-2.3.0-3.el8`)and that way we can revert #740 and depend on `qemu-kiwi`?

It seems a reasonable approach, given the revert to 8.5 is temporary.

**Comment by mike-nguyen** [comment]
The OS compose fetches packages only from the repos defined in `manifest.yaml` file. Extensions fetch packages from the repos specified in in `manifest.yaml`  and `extensions.yaml`. Because of this separation, we were able to get the `qemu-kvm-core` from the RHEL8.6 appstream repo without affecting the OS (no 8.6 packages in the OS).

This allows us to use the newer `kata-containers` for 4.11 during the temporary revert.

**Comment by cgwalters** [comment]
I think this is fixed
