### ISSUE TITLE
Add machine-readable AMI JSON list

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#82]
Like https://alpha.release.core-os.net/amd64-usr/current/coreos_production_ami_all.json

Software such as a cluster installer should be able to easily and programmatically find our AMIs (and extend later for similar clouds).

**Comment by miabbott** [comment]
It looks like `ore` already spits out some [relevant JSON](https://github.com/coreos/mantle/blob/master/cmd/ore/aws/upload.go#L257-L267) to `stdout` which we are [capturing in out.json](https://github.com/openshift/os/blob/master/Jenkinsfile.cloud#L164).

I think we could just massage this JSON file and add it to the list of things we sync out.
