### ISSUE TITLE
test-in-cluster broken by https://github.com/coreos/coreos-layering-examples/pull/20

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#829]
I should have realized this earlier but basically https://github.com/coreos/coreos-layering-examples/pull/20 broke `test-in-cluster` because:

- Suddenly we have multiple `Dockerfile`, not just one
- Most of the `Dockerfile` require a `rhel.repo`

So...two things too:

- While I think this test is definitely valuable, we'd get more immediate value out of running the openshift e2e tests; this is where https://github.com/openshift/release/pull/29228 is leading
- But that said, I think we could fix this test relatively easily by changing it to use say https://github.com/coreos/coreos-layering-examples/blob/rhcos/selinux/Dockerfile *and* we need to change the script to do something like "detect if dockerfile is running `rpm-ostree install`" and if it isn't, don't inject a requirement on `rhel.repo` *or* just hack our test to make a dummy one

**Comment by cgwalters** [comment]
cc @cheesesashimi per our chat

**Comment by cheesesashimi** [comment]
Fixing the multiple Dockerfile issue should be straightforward: https://github.com/openshift/os/blob/master/tests/layering/build_helper_test.go#L106-L109.

**Comment by cgwalters** [comment]
https://github.com/coreos/coreos-layering-examples/pull/26 will help with this.
