### ISSUE TITLE
Ignition: useradd failure during initial boot

### ISSUE THREAD

**Issue by arithx** [openshift/os#86]
When a non-default user is specified in an Ignition config it fails during the `useradd` trying to create the home directory.

```
[   19.778871] ignition[723]: CRITICAL : files: failed to create users/groups: failed to create users: failed to create user "core": exit status 12: Cmd: "/usr/sbin/useradd" "--root" "/sysroot" "--       create-home" "--password" "*" "core" Stdout: "" Stderr: "useradd: cannot create directory /home/core\n"] Started Emergency Shell.
```

Some additional investigation into the ordering might be required if the `/home` symlink is non-functional currently.

Full serial console run @ https://slack-files.com/T027F3GAJ-FB33Q74Q1-bef7bf3c2c

**Comment by jlebon** [comment]
It seems the issue here is that `var.mount` is created at runtime using a generator. This runs after ignition. This allows us to support `/var` as a mount (https://github.com/ostreedev/ostree/pull/859).

Hmm, I wonder if we could split out that generator and make it run in the initramfs instead before we switch root? It (and the generated `var.mount`) would have to run *after* ostree-prepare-root (since it needs `/etc/fstab`), but *before* ignition.

**Comment by cgwalters** [comment]
Offhand...I feel like we should go for the tactical fix of:  If Ignition is running, and it detects ostree, then mount `/var`.  I'd also be fine with having ostree detect ignition.

Doing the generator is more correct (we'd handle ignition writing an `/etc/fstab` containing a mount for `/var` which I do think we want)...I'm just uncertain about the complexity.

**Comment by dustymabe** [comment]
tactically can we just add it here: https://github.com/dustymabe/bootengine/blob/master/dracut/30ignition/remount-sysroot.service#L14

**Comment by jlebon** [comment]
An option was added in libostree so we can work around this temporarily: https://github.com/ostreedev/ostree/pull/1617. This also requires some ignition changes though. Working on that now.

**Comment by cgwalters** [comment]
Doing the generator is more correct (we'd handle ignition writing an `/etc/fstab` containing a mount for `/var` which I do think we want)...I'm just uncertain about the complexity.

**Comment by jlebon** [comment]
This is fixed in the latest image. @rfairley was able to start up and SSH into an node using `kola`.
