### ISSUE TITLE
RHCOS 4.11 ppc64le - libguestfs: error: could not create appliance through libvirt.

### ISSUE THREAD

**Issue by miabbott** [openshift/os#870]
Seeing these messages in addition to the messages from #859 

```
libguestfs: error: could not create appliance through libvirt.

Try running qemu directly without libvirt using this environment variable:
export LIBGUESTFS_BACKEND=direct

Original error from libvirt: internal error: process exited while connecting to monitor: 2022-06-30T11:08:07.451193Z qemu-system-ppc64: The -accel and "-machine accel=" options are incompatible [code=1 int1=-1]
2022-06-30T11:08:07Z kola: retryloop: failed to bring up machines: ignition injection with guestfs failed: guestfish launch failed: exit status 1
```

I wonder if this is related to using newer versions of qemu/libvirt from F36 in `coreos-assembler`

**Comment by miabbott** [comment]
I believe this is impacting our ability to run tests; seeing failures in:

`ext.config.shared.networking.no-default-initramfs-net-propagation.bootif`
`ext.config.shared.networking.force-persist-ip`
`ext.config.shared.networking.prefer-ignition-networking`
`ext.config.shared.networking.kargs-rd-net`
`ext.config.shared.networking.mtu-on-bond-ignition`
`ext.config.shared.networking.mtu-on-bond-kargs`

**Comment by miabbott** [comment]
Last successful 4.11 build was on June 28, using `docker-registry.default.svc:5000/rhcos/coreos-assembler:main` corresponding to https://github.com/coreos/coreos-assembler/commit/68bfb654e6dbeb85d7888d604b807e0c9fa4b8e5

Most recent failure was today using `docker-registry.default.svc:5000/rhcos/coreos-assembler:4.11` corresponding to https://github.com/coreos/coreos-assembler/commit/e513b1994a69a2febc4c3a57ff801e5ca54afced

So it looks like the `coreos-assembler` image needs to be rebuilt at least to get it using `HEAD` of `rhcos-4.11` branch

**Comment by miabbott** [comment]
Probably want to focus on this error:

`Original error from libvirt: internal error: process exited while connecting to monitor: 2022-06-30T11:08:07.451193Z qemu-system-ppc64: The -accel and "-machine accel=" options are incompatible [code=1 int1=-1]`

**Comment by rwmjones** [comment]
This is a bug of some kind in libvirt, it's not using the right options when starting the ppc guest.  What Linux distro / version of libvirt etc is this?

**Comment by rwmjones** [comment]
Suggestion it might be connected to this change: https://gitlab.com/libvirt/libvirt/-/commit/d20ebdda28fe254727989102bd5522aafe42cc25  We really need detailed logs & version of libvirt and othe packages.

**Comment by berrange** [comment]
> Suggestion it might be connected to this change: https://gitlab.com/libvirt/libvirt/-/commit/d20ebdda28fe254727989102bd5522aafe42cc25 We really need detailed logs & version of libvirt and other packages.

NB, libvirt itself should be generating consistent CLI args for using -accel, but if the `/usr/bin/qemu-system-ppc64` binary has been replaced by a wrapper script that adds extra -machine args, that could cause the error seen. The `/var/log/libvirt/qemu/$GUEST.log` file should show evidence to support this theory

**Comment by ravanelli** [comment]
> NB, libvirt itself should be generating consistent CLI args for using -accel, but if the `/usr/bin/qemu-system-ppc64` binary has been replaced by a wrapper script that adds extra -machine args, that could cause the error seen. The `/var/log/libvirt/qemu/$GUEST.log` file should show evidence to support this theory

Yeah, we do have a [wrapper](https://github.com/coreos/coreos-assembler/blob/main/src/libguestfs-ppc64le-wrapper.sh) for ppc64le due the vsmt for the RHEL7 host,  it has been there for a while. 
Let me check the logs to see if I can understand more about it

**Comment by berrange** [comment]
> > NB, libvirt itself should be generating consistent CLI args for using -accel, but if the `/usr/bin/qemu-system-ppc64` binary has been replaced by a wrapper script that adds extra -machine args, that could cause the error seen. The `/var/log/libvirt/qemu/$GUEST.log` file should show evidence to support this theory
> 
> Yeah, we do have a [wrapper](https://github.com/coreos/coreos-assembler/blob/main/src/libguestfs-ppc64le-wrapper.sh) for ppc64le due the vsmt for the RHEL7 host, it has been there for a while. Let me check the logs to see if I can understand more about it

Yes, that's the root cause of the problem - we can see it doing  `-machine pseries,accel=kvm:tcg,vsmt=8,cap-fwnmi=off` which is not allowed by QEMU when libvirt is using `-accel`

**Comment by miabbott** [comment]
> Yes, that's the root cause of the problem - we can see it doing `-machine pseries,accel=kvm:tcg,vsmt=8,cap-fwnmi=off` which is not allowed by QEMU when libvirt is using `-accel`

Could it be as simple as changing our wrapper script to do?

`qemu-system-ppc64 "$@" -accel=kvm:tcg -machine pseries,vsmt=8,cap-fwnmi=off`

**Comment by berrange** [comment]
It shouldn't be selecting kvm/tcg at all - libguestfs is already setting that explicitly in the  configuration it gives. The other two options libvirt doesn't support, but I'm kind of surprised vsmt/cap-fwnmi options are needed though, as libguestfs has worked on ppc64 for years for other users without these settings.
