### ISSUE TITLE
Base image not being updated

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#908]
I'm trying to debug

```
$ oc image info registry.ci.openshift.org/rhcos-devel/rhel-coreos:latest | grep Created
Created:     6d ago
$
```

:arrow_right: today's postsubmit https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-os-master-images/1549794749240578048 says Nothing to promote, skipping...  yet https://github.com/openshift/release/commit/f793a65f5ace82ad65a24bbd95b1d29ee76b63c5 was seemingly trying to re-enable this?

---

I tried to fix this in https://github.com/openshift/release/pull/30701

**Comment by cgwalters** [comment]
cc @travier @cheesesashimi

**Comment by travier** [comment]
I've triggered a retest on a PR to see if things have improved but we might have to wait until a PR is merged to see if the fix above works?

**Comment by cgwalters** [comment]
Another attempt https://github.com/openshift/release/pull/30794

**Comment by cgwalters** [comment]
It worked!

```
$ oc image info registry.ci.openshift.org/rhcos-devel/rhel-coreos:latest
Name:        registry.ci.openshift.org/rhcos-devel/rhel-coreos:latest
Digest:      sha256:2ea468f4858bb834eb1ed2331315aa8e93bd1e2b6054718ebc019a15529cd8ae
Media Type:  application/vnd.docker.distribution.manifest.v2+json
Created:     1h ago
...
```
