### ISSUE TITLE
RHCOS 4.10 pipeline failing during iso creation

### ISSUE THREAD

**Issue by mike-nguyen** [openshift/os#916]
```
+ coreos-installer iso extract pack-minimal-iso /home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.10/tmp/buildpost-live/rhcos-410.84.202207261020-0-live.x86_64.iso /home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.10/tmp/buildpost-live/rhcos-410.84.202207261020-0-live.x86_64.iso.minimal --consume
error: The subcommand 'pack-minimal-iso' wasn't recognized

	Did you mean 'minimal-iso'?
```

**Comment by jlebon** [comment]
I'll take this.

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/3009

**Comment by mike-nguyen** [comment]
Thanks @jlebon!

I did some further digging into why we didn't see this failure earlier (we got successful live ISOs on July 14). The coreos-assembler-4.10 buildconfig last ran 4 months ago and something must have been wrong with the trigger.  We recently started use coreos-assembler from registry.ci.openshift.org as the source of truth and it picked up the new version of coreos-installer.
