### ISSUE TITLE
4.12 aarch64: `2022-08-02T12:58:32Z platform: some systemd units failed: [console-login-helper-messages-issuegen.path]`

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#927]
Somehow this is only hitting aarch64 seemingly, but I don't understand how.

**Comment by travier** [comment]
We have https://github.com/openshift/os/issues/906 too for RHEL 8.4. Maybe it's a race condition somewhere

**Comment by cgwalters** [comment]
Hmm fun.  Well...dunno.  I guess let's just close this as a likely duplicate.
