### ISSUE TITLE
Modify /etc/os-release to display Jira instead of Bugzilla

### ISSUE THREAD

**Issue by mike-nguyen** [openshift/os#950]
Once the transition to Jira is completed, change the Bugzilla references to Jira.

Example on 4.11:
https://github.com/openshift/os/blob/fa6a502f35eeda25e8a95d0a4d7eabd39836c580/manifest.yaml#L149-L151

The new bug tracker will be:  https://issues.redhat.com/projects/OCPBUGS

**Comment by travier** [comment]
We'll have to wait until the RHCOS component/board is created in this project or until we've made a short link that auto-fills the Jira issues with relevant informations.
