### ISSUE TITLE
scos: testiso with uefi get grub terminal

### ISSUE THREAD

**Issue by HuijingHei** [openshift/os#954]
Build scos locally and run `kola testiso -S --qemu-firmware uefi --scenarios iso-live-login`, get grub terminal.

```
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00011 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x5,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00011 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x5,0xFFFF,0x0)
      Minimal BASH-like line editing is supported. For the first word,    
      TAB lists possible command completions. Anywhere else TAB lists     
      possible device or file completions.                                


grub>
```
A little like https://github.com/openshift/os/issues/953, but they have different error logs

**Comment by HuijingHei** [comment]
Try to build live iso with latest grub2 (download and put under overrides/rpm/), but failed with 

```
INFO - Running command: ['/usr/bin/ostree', 'checkout', '--repo', '/srv/data/c9s-metal/tmp/repo', '--user-mode', '--subpath', '/usr/lib/bootupd/updates/EFI', '0e7fe829d8a8fa139891de0051c28f652a9a16eab87ebb3aec826c6533381e46', '/srv/data/c9s-metal/tmp/buildpost-live/efi']
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 704, in <module>
    generate_iso()
  File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 525, in generate_iso
    raise Exception(f"did not find exactly one EFI vendor ID: {vendor_ids}")
Exception: did not find exactly one EFI vendor ID: ['centos', 'redhat']
error: failed to execute cmd-buildextend-live: exit status 1
```

**Comment by HuijingHei** [comment]
Try more about the uefi, run the following commands, get result is `PASS: iso-live-login (uefi + metal) (1m46.346s)`.
```
grub> ls
(proc) (cd0) (cd0,msdos2)
grub> configfile (cd0)/EFI/redhat/grub.cfg
```
Is there any suggestion about how to fix this? Thanks!

**Comment by cgwalters** [comment]
I suspect what's going on here is related to the "EFI vendor directory" being `redhat` for scos when it should be `centos`.  Specifically, we need to fix https://github.com/openshift/os/tree/master/live/EFI/redhat to be dynamically switched.

Note we have a separate copy of this in https://github.com/coreos/fedora-coreos-config/tree/testing-devel/live/EFI/fedora - if we changed e.g. coreos-assembler to support dynamically generating this based on the distribution name, then we wouldn't need a separate copy in openshift/os for rhel/centos.

**Comment by cgwalters** [comment]
To say this another way, does it work to do: `mv src/config/live/EFI/{redhat,centos}` before doing a build for scos?

**Comment by HuijingHei** [comment]
> To say this another way, does it work to do: `mv src/config/live/EFI/{redhat,centos}` before doing a build for scos?

Yes, it works, thanks! Seems also fix https://github.com/openshift/os/issues/953
```
[coreos-assembler]$ mv src/config/live/EFI/redhat src/config/live/EFI/centos
[coreos-assembler]$ ls src/config/live/EFI/centos/grub.cfg
[coreos-assembler]$ cosa fetch && cosa build && cosa buildextend-metal && cosa buildextend-metal4k && cosa buildextend-live

$ kola testiso -S --qemu-firmware uefi --scenarios iso-live-login,iso-as-disk --output-dir tmp/kola-uefi/insecure
Testing scenarios: [iso-as-disk iso-live-login]
Ignoring verification of signature on metal image
PASS: iso-live-login (uefi + metal) (39.666s)
PASS: iso-as-disk (uefi + metal) (34.479s)

[coreos-assembler]$ kola testiso -S --qemu-native-4k --qemu-multipath --scenarios iso-install --output-dir tmp/kola-metal4k
Testing scenarios: [iso-install]
Ignoring verification of signature on metal image
PASS: iso-install (uefi + metal4k + multipath) (2m52.826s)
```

**Comment by HuijingHei** [comment]
> if we changed e.g. coreos-assembler to support dynamically generating this based on the distribution name, then we wouldn't need a separate copy in openshift/os for rhel/centos.

Agree, maybe can add this based on https://github.com/coreos/coreos-assembler/pull/2934

**Comment by HuijingHei** [comment]
Silly question, the root cause here is by default `boot/efi/EFI/centos/grubx64.efi` only find `live/EFI/centos/grub.cfg` instead of `live/EFI/redhat/grub.cfg`?

**Comment by cgwalters** [comment]
Yep, that's my understanding!

**Comment by HuijingHei** [comment]
@cgwalters much appreciated for your guidance! :+1:

**Comment by travier** [comment]
It's probably not for the variant support but could we a distinct PR for COSA to add support in image.yaml.

**Comment by HuijingHei** [comment]
> It's probably not for the variant support but could we a distinct PR for COSA to add support in image.yaml.

Do you mean add config in `image.yaml`, and parse it in `cmd-buildextend-live`?

**Comment by travier** [comment]
Yes, I'm thinking of something like https://github.com/coreos/coreos-assembler/pull/2971
